### ISSUE TITLE
Error on HAML-file

### ISSUE THREAD

**Issue by LeEnno** [SublimeLinter/SublimeLinter#1001]
When saving an haml-file (contents seem to not matter), a window pops up at the bottom saying:

```
SublimeLinter: ERROR:

 Lint task failed.
Traceback (most recent call last):
  File "lint.backend in /Users/Enno/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 201, in await_futures
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "lint.backend in /Users/Enno/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 96, in execute_lint_task
  File "lint.linter in /Users/Enno/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 816, in lint
  File "lint.linter in /Users/Enno/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 536, in get_cmd
  File "lint.linter in /Users/Enno/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 576, in build_cmd
  File "lint.linter in /Users/Enno/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 616, in insert_args
  File "linter in /Users/Enno/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-contrib-haml-lint.sublime-package", line 38, in build_args
AttributeError: 'module' object has no attribute 'find_file'
```

1. Am I missing something?
2. Since when does this window pop up on error? Setting `debug` to `false` in settings doesn't prevent this.

**Comment by kaste** [comment]
So, basically, haml-lint is not compatible with SL4 yet. It needs to get fixed over there. We introduced this breakage here https://github.com/SublimeLinter/SublimeLinter/releases/tag/4.0.0-rc.9.9.8

This is trivial to fix, and I can maybe help with that.
