### ISSUE TITLE
Not linting

### ISSUE THREAD

**Issue by Mattiaslndstrm** [SublimeLinter/SublimeLinter#1005]
I tried installing the beta, but couldn't get it to work. I ended up reverting to the old version. I tried without any settings, and with my old linter settings. I tried many different linters. On the off chance that this is helpful for anyone here is the console output:

`Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 538, in on_activated_async
    callback.on_activated_async(v)
  File "status_bar_view in /Users/Mattias/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 48, in on_activated_async
  File "status_bar_view in /Users/Mattias/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 104, in get_we_count
KeyError: 140
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 538, in on_activated_async
    callback.on_activated_async(v)
  File "sublime_linter in /Users/Mattias/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 96, in on_activated_async
AttributeError: 'module' object has no attribute 'is_lintable'`

**Comment by kaste** [comment]
You probably needed a restart of Sublime Text here.

**Comment by Mattiaslndstrm** [comment]
I did restart Sublime, of course. I didn't restart my computer, but I restarted Sublime multiple times.

**Comment by kaste** [comment]
Unfortunately you don't have the full console output. (What happened before the crash.)

Did SublimeLinter prompt you to restart? Did it say that it did backup your old settings?

**Comment by Mattiaslndstrm** [comment]
Sorry about that. I thought I copied the whole output. 

The Package Control message from SublimeLinter said that I should restart. After the restart it said that it had backed up my old settings. I tried without settings, and also with my old linter settings, restarting after every try.

**Comment by kaste** [comment]
That's just unfortunate, but it seems that Package Control cannot update our package, maybe bc the linters are separate plugins, and Package Control has no notion of such dependencies afaik. So, my own experience was I had to restart like forever to get it work.  

But, if you see something like `on_activated_async callback.on_activated_async(v)` (this comes from the initial activate event when (re-)loading the plugin) or general `'module' object has no attribute 'xxx'` you can bet it hasn't loaded everything in the correct order. (here: our module/package util seems to be empty or whatever; at least it doesn't have a function we clearly defined.)

We just merged #1006 which maybe can help here. (This is on master, not yet released.)
