### ISSUE TITLE
Error when opening a file to be linted.

### ISSUE THREAD

**Issue by shulard** [SublimeLinter/SublimeLinter#1008]
Hello,

I use the beta of SL4 and I got an error when I open a file to be linted :

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "sublime_linter in /Users/shulard/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 64, in plugin_loaded
  File "sublime_linter in /Users/shulard/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 182, in hit
  File "sublime_linter in /Users/shulard/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 251, in check_syntax
  File "lint.linter in /Users/shulard/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 486, in assign
  File "lint.linter in /Users/shulard/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 490, in <setcomp>
  File "./python3.3/functools.py", line 251, in wrapper
  File "lint.linter in /Users/shulard/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 1065, in can_lint
  File "lint.linter in /Users/shulard/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 1108, in fulfills_version_requirement
AttributeError: 'property' object has no attribute 'replace'
Traceback: error.
```

I don't think I've played with some configuration since the SL4 install and it worked some days ago. I tried to figure out what's this error is but I can't find any clue (I'm not really familiar with Python...).

Is there someone with that kind of error ?

**Comment by shulard** [comment]
I use the package version 4.0.0-rc.9.9.9.2, I hope this'll help 😄.

**Comment by kaste** [comment]
Thanks for reporting. Sorry for that, I mixed my PR's. The fix is actually already part of a PR (994), so I just cherry-picked the one commit from there. Hopefully the right one. Published as 'rc.9.9.9.3'.

**Comment by shulard** [comment]
Thank you for the very quick reply and action 😄 !
