### ISSUE TITLE
TypeError: 'NoneType' object is not iterable (await_futures)

### ISSUE THREAD

**Issue by thislogancall** [SublimeLinter/SublimeLinter#1013]
Note: I am using SublimeLinter 4

I've never looked into the linter's code before (or python), not really sure if i'm doing something wrong here or if this is a bug?

## Error
```
SublimeLinter: ERROR:

 Lint task failed.
Traceback (most recent call last):
  File "lint.backend in /Users/logan/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 201, in await_futures
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "lint.backend in /Users/logan/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 96, in execute_lint_task
  File "lint.linter in /Users/logan/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 812, in lint
  File "lint.linter in /Users/logan/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 523, in get_cmd
TypeError: 'NoneType' object is not iterable
```

## .eslintrc.json
```
{
    "env": {
        "browser": true,
        "es6": true,
		"jquery": true
    },
    "extends": "eslint:recommended",
    "rules": {
        "linebreak-style": [
            "error",
            "unix"
        ]
    }
}
```

**Comment by kaste** [comment]
Hi :wave:! 

Please enable debug mode and post the log. It is unlikely that eslint is throwing here.

**Comment by thislogancall** [comment]
Thank you. The debug output is what's in the error message above.

**Comment by kaste** [comment]
No, that's just the error which pops up. You have to open the console for full log what happened.

**Comment by thislogancall** [comment]
Gothca. Thanks for clarifying. Here it is...
```
SublimeLinter: SublimeLinter.sublime-package:476: detected syntax: javascript
[2018-02-23 15:20:24,475 - INFO     - SublimeLinter.lint.linter] detected syntax: javascript
SublimeLinter: #5 SublimeLinter.sublime-package:800: 'eslint' is linting 'global.js'
[2018-02-23 15:20:24,795 - INFO     - SublimeLinter.lint.linter] 'eslint' is linting 'global.js'
SublimeLinter: #6 SublimeLinter.sublime-package:800: 'flow' is linting 'global.js'
[2018-02-23 15:20:24,804 - INFO     - SublimeLinter.lint.linter] 'flow' is linting 'global.js'
SublimeLinter: #5 SublimeLinter.sublime-package:1205: eslint: global.js ['/Users/logan/code/shopify/project/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '/Users/logan/code/shopify/project/src/scripts/global.js']
[2018-02-23 15:20:24,805 - INFO     - SublimeLinter.lint.linter] eslint: global.js ['/Users/logan/code/shopify/project/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '/Users/logan/code/shopify/project/src/scripts/global.js']
SublimeLinter: #5 SublimeLinter.sublime-package:1208: eslint: cwd: /Users/logan/code/shopifyproject/
[2018-02-23 15:20:24,805 - INFO     - SublimeLinter.lint.linter] eslint: cwd: /Users/logan/code/shopifyproject/
SublimeLinter: #6 SublimeLinter.sublime-package:104: PATH:
    /Users/logan/.nvm/versions/node/v9.5.0/bin
    /usr/local/sbin
    /Users/logan/bin
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    /Applications/VMware Fusion.app/Contents/Public
    /Users/logan/.composer/vendor/bin
    /Users/logan/Library/Android/sdk/tools
    /Users/logan/Library/Android/sdk/platform-tools
    /Users/logan/Library/Android/sdk/tools
    /Users/logan/Library/Android/sdk/platform-tools
    /Applications/MAMP/Library/bin/
[2018-02-23 15:20:24,815 - INFO     - SublimeLinter.lint.util] PATH:
    /Users/logan/.nvm/versions/node/v9.5.0/bin
    /usr/local/sbin
    /Users/logan/bin
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    /Applications/VMware Fusion.app/Contents/Public
    /Users/logan/.composer/vendor/bin
    /Users/logan/Library/Android/sdk/tools
    /Users/logan/Library/Android/sdk/platform-tools
    /Users/logan/Library/Android/sdk/tools
    /Users/logan/Library/Android/sdk/platform-tools
    /Applications/MAMP/Library/bin/
SublimeLinter: #7 SublimeLinter.sublime-package:800: 'sublimesyntax' is linting 'global.js'
[2018-02-23 15:20:24,820 - INFO     - SublimeLinter.lint.linter] 'sublimesyntax' is linting 'global.js'
SublimeLinter: flow attempting to run from: ['/usr/local/bin/flow', 'check-contents', '@', '--show-all-errors', '--json'] 
SublimeLinter: did not find @flow pragma 
SublimeLinter: #5 SublimeLinter.sublime-package:827: eslint output:
    /Users/logan/code/shopify/project/src/scripts/global.js: line 3, col 3, Error - Unexpected console statement. (no-console)

    1 problem
[2018-02-23 15:20:25,160 - INFO     - SublimeLinter.lint.linter] eslint output:
    /Users/logan/code/shopify/project/src/scripts/global.js: line 3, col 3, Error - Unexpected console statement. (no-console)

    1 problem
SublimeLinter: #5 SublimeLinter.sublime-package:868: eslint: No match for line: ''
[2018-02-23 15:20:25,160 - INFO     - SublimeLinter.lint.linter] eslint: No match for line: ''
SublimeLinter: #5 SublimeLinter.sublime-package:868: eslint: No match for line: '1 problem'
[2018-02-23 15:20:25,160 - INFO     - SublimeLinter.lint.linter] eslint: No match for line: '1 problem'
```

**Comment by kaste** [comment]
That's not the complete log. Anyway try to narrow down which plugin is causing this. Start with sublimesyntax. Disable it and see if you still have the error.

BTW you have a plugin here which causes double logging.

**Comment by kaste** [comment]
You probably lost interest or solved it. Closing now.

**Comment by thislogancall** [comment]
Thanks @kaste it looks like the flow linter was causing me some grief, and since I'm not using it anymore I just removed it. No more SublimeLinter errors.
