### ISSUE TITLE
ImportError: cannot import name util

### ISSUE THREAD

**Issue by ellipticaldoor** [SublimeLinter/SublimeLinter#1016]
I cloned the master branch on my package folder.

I'm on the commit 684730c476c676ecd829dc00c3d3381f5c817941

I'm using a new Sublime Text installation from scratch without any other plugin.

Sublime Text version: 3143
OS: Macos 10.13.3

This is the error of the log that I'm getting.

```
startup, version: 3143 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/miguel/Library/Application Support/Sublime Text 3/Packages
state path: /Users/miguel/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/miguel/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.174959
using gpu buffer for window
startup time: 0.246572
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-eslint.linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in /Users/miguel/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-eslint.sublime-package", line 16, in <module>
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/__init__.py", line 6, in <module>
    from . import (
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 13, in <module>
    from . import persist, util
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/persist.py", line 6, in <module>
    from .settings import Settings
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 5, in <module>
    from jsonschema.validators import validate
ImportError: No module named 'jsonschema'
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/busy_indicator_view.py", line 6, in <module>
    from .lint.const import STATUS_BUSY_KEY
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/__init__.py", line 6, in <module>
    from . import (
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 13, in <module>
    from . import persist, util
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/persist.py", line 6, in <module>
    from .settings import Settings
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 4, in <module>
    from . import util
ImportError: cannot import name util
reloading plugin SublimeLinter.commands
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/commands.py", line 3, in <module>
    from .lint import persist
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/__init__.py", line 6, in <module>
    from . import (
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 13, in <module>
    from . import persist, util
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/persist.py", line 6, in <module>
    from .settings import Settings
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 4, in <module>
    from . import util
ImportError: cannot import name util
reloading plugin SublimeLinter.goto_commands
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/goto_commands.py", line 5, in <module>
    from .lint import persist
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/__init__.py", line 6, in <module>
    from . import (
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 13, in <module>
    from . import persist, util
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/persist.py", line 6, in <module>
    from .settings import Settings
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 4, in <module>
    from . import util
ImportError: cannot import name util
reloading plugin SublimeLinter.highlight_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/highlight_view.py", line 7, in <module>
    from .lint import persist, events
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/__init__.py", line 6, in <module>
    from . import (
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 13, in <module>
    from . import persist, util
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/persist.py", line 6, in <module>
    from .settings import Settings
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 4, in <module>
    from . import util
ImportError: cannot import name util
reloading plugin SublimeLinter.log_handler
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/log_handler.py", line 4, in <module>
    from .lint import util
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/__init__.py", line 6, in <module>
    from . import (
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 13, in <module>
    from . import persist, util
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/persist.py", line 6, in <module>
    from .settings import Settings
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 4, in <module>
    from . import util
ImportError: cannot import name util
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/panel_view.py", line 5, in <module>
    from .lint import persist, events
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/__init__.py", line 6, in <module>
    from . import (
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 13, in <module>
    from . import persist, util
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/persist.py", line 6, in <module>
    from .settings import Settings
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 4, in <module>
    from . import util
ImportError: cannot import name util
reloading plugin SublimeLinter.status_bar_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/status_bar_view.py", line 6, in <module>
    from .lint import persist
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/__init__.py", line 6, in <module>
    from . import (
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 13, in <module>
    from . import persist, util
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/persist.py", line 6, in <module>
    from .settings import Settings
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 4, in <module>
    from . import util
ImportError: cannot import name util
reloading plugin SublimeLinter.sublime_linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 10, in <module>
    from . import log_handler
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/log_handler.py", line 4, in <module>
    from .lint import util
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/__init__.py", line 6, in <module>
    from . import (
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 13, in <module>
    from . import persist, util
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/persist.py", line 6, in <module>
    from .settings import Settings
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 4, in <module>
    from . import util
ImportError: cannot import name util
reloading plugin SublimeLinter.tooltips_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/tooltips_view.py", line 6, in <module>
    from .lint import persist
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/__init__.py", line 6, in <module>
    from . import (
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 13, in <module>
    from . import persist, util
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/persist.py", line 6, in <module>
    from .settings import Settings
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 4, in <module>
    from . import util
ImportError: cannot import name util
plugins loaded
Package Control: Installing 1 missing dependency
Package Control: The dependency 'jsonschema' is not available
Package Control: Skipping automatic upgrade, last run at 2018-02-24 08:48:52, next run at 2018-02-24 09:48:52 or after
environment variables loaded using: /bin/zsh -l
```

**Comment by ellipticaldoor** [comment]
How I can do that?

I did pip install jsonschema but it looks like it doesn't work

**Comment by braver** [comment]
Use the “satisfy dependencies” command. Also restart ST a few times.

**Comment by kaste** [comment]
Use the command palette in Sublime. ctrl-shift-P

**Comment by ellipticaldoor** [comment]
I still get this error running “satisfy dependencies”

```
Package Control: The dependency 'jsonschema' is not currently installed; installing...
Package Control: The dependency 'jsonschema' is not available
Package Control: The dependency 'jsonschema' could not be installed or updated
error: Package Control

One or more dependencies could not be installed or updated.

Please check the console for details.
```

**Comment by kaste** [comment]
As it seems, Package Control is currently broken. Follow https://github.com/wbond/package_control/issues/1334
