### ISSUE TITLE
[Version 4] ImportError: cannot import name log_handler. in lint if hit_time and persist.last_hit_times.get(view_id, 0) > hit_time: AttributeError: 'NoneType' object has no attribute 'last_hit_times

### ISSUE THREAD

**Issue by AtomicCoding** [SublimeLinter/SublimeLinter#1040]
Not sure how to reproduce exactly, but it happened when I was using SublimeLinter-pyflakes.

1st Error:
``
Traceback (most recent call last): File "./python3.3/threading.py", line 901, in _bootstrap_inner File "./python3.3/threading.py", line 1142, in run File "/Users/AtomicOwner/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 35, in worker callback(vid, hit_time) File "/Users/AtomicOwner/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 225, in lint if hit_time and persist.last_hit_times.get(view_id, 0) > hit_time: AttributeError: 'NoneType' object has no attribute 'last_hit_times'
``
2nd Error:
``
Traceback (most recent call last):
  File "/Users/AtomicOwner/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 76, in on_update
    from ..sublime_linter import SublimeLinter
  File "/Users/AtomicOwner/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/sublime_linter.py", line 11, in <module>
ImportError: cannot import name log_handler
``

**Comment by braver** [comment]
Was it just once or does it happen continuously?

**Comment by kaste** [comment]
This is just another update problem. persist is a module and should never be None. This is basically old loaded code running in an undefined environment. 

We need to unload the queue.debounce on unload or before update.

**Comment by mciastek** [comment]
This can be a similar problem:
```
SublimeLinter: ERROR: Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/mciastek/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/mciastek/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 794, in lint
  File "lint.linter in /Users/mciastek/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 505, in get_cmd
TypeError: 'NoneType' object is not iterable
```

It appeared after last update to v4.0.0.

**Comment by braver** [comment]
@mciastek that looks more like #1041. Please check the other open issues, or report a new one with more info (e.g. what linter you're using)
