### ISSUE TITLE
[Version 4] Total crash after upgrading to version 4

### ISSUE THREAD

**Issue by shindler** [SublimeLinter/SublimeLinter#1043]
When I'm starting SL after latest upgrade to version 4 I get a lot of errors
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter-contrib-eslint_d.sublime-package", line 16, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 5, in <module>
ImportError: No module named 'jsonschema.validators'
reloading plugin SublimeLinter-contrib-tslint.linter
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter-contrib-tslint.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter-eslint.linter
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter-eslint.sublime-package", line 16, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter-jscs.linter
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter-jscs.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter-jshint.linter
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter-jshint.sublime-package", line 15, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter-json.linter
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter-json.sublime-package", line 19, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "busy_indicator_view in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.commands
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "commands in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 3, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.goto_commands
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "goto_commands in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 5, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.highlight_view
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "highlight_view in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 9, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.log_handler
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "log_handler in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "panel_view in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 5, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.status_bar_view
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "status_bar_view in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.sublime_linter
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "sublime_linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 12, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "log_handler in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.tooltips_view
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "tooltips_view in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /home/max/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
```

Sublime: 3.0b3143
OS: Linux Mint 18.3
Installed OS Python version: 2.7.6

As far I can understand this trace a local version of Python 3.3 is used. Unfortunately I'm not a Python developer and this trace means to me nothing. Any help appreciated.

**Comment by braver** [comment]
So, is this every time you restart SublimeText?

**Comment by shindler** [comment]
Yes, each time I restart SL (and I've done it many times)

**Comment by braver** [comment]
Could you run the "Satisfy Dependencies" command from the command palette? It seems the jsonschema dependency wasn't installed for some reason.

**Comment by shindler** [comment]
Done SL output:
```
Package Control: The dependency 'backrefs' is installed, but out of date; upgrading to latest release 1.6.0 from 1.4.0...
Package Control: The dependency 'backrefs' has successfully been installed or updated
Package Control: All dependencies have been satisfied
```
SL restarted > still getting the same set of errors.

**Comment by shindler** [comment]
I've reinstalled the package n-th time and in SL console I can saw:
```
Package Control: The dependency 'jsonschema' is not currently installed; installing...
Package Control: The dependency 'jsonschema' has successfully been installed or updated
```
so it should be there. No errors are reported during startup, however no liniting is going on right now, I will check my configuration and get back

**Comment by braver** [comment]
Reading your log it fails importing something from jsonschema and then it completely breaks down (as I would expect).

**Comment by kaste** [comment]
FWIW tslint is broken. I made a PR two weeks ago but they did not respond.

**Comment by shindler** [comment]
@kaste that explains why no linting seems to happen in my case. Closing issue as it seems that n-th reinstall solved my problem. Thx for support.

**Comment by kaste** [comment]
From what I've seen a n-th reinstall does often do less than a n-th re-start 😄
