### ISSUE TITLE
[contrib-haml-lint] Linter crashed

### ISSUE THREAD

**Issue by nhoffmann** [SublimeLinter/SublimeLinter#1058]
The [haml-lint](https://github.com/jeroenj/SublimeLinter-contrib-haml-lint) plugin is not playing nicely with SublimeLinter v4. 

The linter just crashes when linting haml files: 

```
SublimeLinter: #5 hamllint _user_menu.html.haml ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/nho/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/nho/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 794, in lint
  File "lint.linter in /Users/nho/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 514, in get_cmd
  File "lint.linter in /Users/nho/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 554, in build_cmd
  File "lint.linter in /Users/nho/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 594, in insert_args
  File "linter in /Users/nho/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-contrib-haml-lint.sublime-package", line 38, in build_args
AttributeError: 'module' object has no attribute 'find_file'
```

I am not too surprised though, since this plugin did not get any updates since the last two years.

**Comment by braver** [comment]
The maintainer is still active on GitHub though, so you could try opening an issue in that repo, see if he's able to fix it.

**Comment by nhoffmann** [comment]
You are absolutely right! Did just that: jeroenj/SublimeLinter-contrib-haml-lint#8
