### ISSUE TITLE
SL 4 constantly crashes when highlighting

### ISSUE THREAD

**Issue by urbandrone** [SublimeLinter/SublimeLinter#1067]
After upgrading to SL4, it seems all linters crash constantly when highlighting errors/warnings. Console output tells me "AttributeError: NoneType object has no attribute split".

**Console output**
```
reloading settings Packages/User/SublimeLinter.sublime-settings
current triggername: 'javascript-complete-names'
Traceback (most recent call last):
  File "lint.events in C:\Users\XXX\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 28, in broadcast
  File "highlight_view in C:\Users\XXX\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 91, in on_lint_result
  File "highlight_view in C:\Users\XXX\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 308, in prepare_highlights_data
  File "highlight_view in C:\Users\XXX\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 350, in get_scope
  File "lint.style in C:\Users\XXX\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 54, in wrapper
  File "lint.style in C:\Users\XXX\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in get_val
AttributeError: 'NoneType' object has no attribute 'split'
``` 

**User settings file**
```
{
    "user": {
        "debug": true,
        "linters": {
            "csslint": {
                "disable": false,
                "args": [
                    "--config",
                    "F:\\SublimeLinters\\.csslintrc"
                ],
                "errors": "",
                "excludes": [],
                "ignore": "",
                "warnings": ""
            },
            "jshint": {
                "disable": false,
                "args": [
                    "--config",
                    "F:\\SublimeLinters\\.jshintrc"
                ],
                "excludes": [
                    "node_modules/**"
                ]
            }
        },
        "gutter_theme": "Default",
        "no_column_highlights_line": true,
        "styles": [
	        {
	            "mark_style": "outline",
	            "priority": 1,
	            "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
	            "icon": "warning",
	            "types": [
	                "warning"
	            ]
	        },
	        {
	            "mark_style": "outline",
	            "priority": 1,
	            "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
	            "icon": "error",
	            "types": [
	                "error"
	            ]
	        }
	    ]
    }
}
```

**Comment by braver** [comment]
Your user settings aren’t correct. Please check the [upgrade doc]h(https://raw.githubusercontent.com/SublimeLinter/SublimeLinter/master/messages/4.0.0-rc.1.txt), fix your settings, enable debug mode and share the entire output of it after a restart.

**Comment by urbandrone** [comment]
OK, removed the "user" field in settings and flattened everything. My user settings now look like this:

**Settings**
```
{
    "debug": true,
    "linters": {
        "csslint": {
            "disable": false,
            "args": [
                "--config",
                "F:\\SublimeLinters\\.csslintrc"
            ],
            "errors": "",
            "excludes": [],
            "ignore": "",
            "warnings": ""
        },
        "jshint": {
            "disable": false,
            "args": [
                "--config",
                "F:\\SublimeLinters\\.jshintrc"
            ],
            "excludes": [
                "node_modules/**"
            ]
        }
    },
    "gutter_theme": "Default",
    "no_column_highlights_line": true,
    "styles": [
        {
            "mark_style": "outline",
            "priority": 1,
            "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
            "icon": "warning",
            "types": [
                "warning"
            ]
        },
        {
            "mark_style": "outline",
            "priority": 1,
            "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
            "icon": "error",
            "types": [
                "error"
            ]
        }
    ]
}
```

Which I assume should be fine. At least, I can see the linter starts linting now.

Sadly, the "NoneType object" error keeps occuring:

**Console**
```
SublimeLinter: #8 SublimeLinter.sublime-package:782: 'jshint' is linting 'Maybe.js'
SublimeLinter: #8 SublimeLinter.sublime-package:1178: jshint: Maybe.js ['C:\\Users\\XXX\\AppData\\Roaming\\npm\\jshint.cmd', '--verbose', '--filename', 'F:\\node-packages\\futils\\sources\\monads\\Maybe.js', '--config', 'F:\\SublimeLinters\\.jshintrc', '-']
SublimeLinter: #8 SublimeLinter.sublime-package:1181: jshint: cwd: F:\node-packages\futils
SublimeLinter: #8 SublimeLinter.sublime-package:809: jshint output:
    F:\node-packages\futils\sources\monads\Maybe.js: line 23, col 1, Expected an assignment or function call and instead saw an expression. (W030)
    F:\node-packages\futils\sources\monads\Maybe.js: line 467, col 14, 'Some' was used before it was defined. (W003)
    F:\node-packages\futils\sources\monads\Maybe.js: line 483, col 14, 'None' was used before it was defined. (W003)
    F:\node-packages\futils\sources\monads\Maybe.js: line 23, col 1, 'foo' is not defined. (W117)

    4 errors
SublimeLinter: #8 SublimeLinter.sublime-package:850: jshint: No match for line: ''
SublimeLinter: #8 SublimeLinter.sublime-package:850: jshint: No match for line: '4 errors'
Traceback (most recent call last):
  File "lint.events in C:\Users\XXX\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 28, in broadcast
  File "highlight_view in C:\Users\XXX\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 91, in on_lint_result
  File "highlight_view in C:\Users\XXX\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 308, in prepare_highlights_data
  File "highlight_view in C:\Users\XXX\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 350, in get_scope
  File "lint.style in C:\Users\XXX\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 54, in wrapper
  File "lint.style in C:\Users\XXX\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in get_val
AttributeError: 'NoneType' object has no attribute 'split'

```

**Comment by urbandrone** [comment]
OK, sorry! After another restart it seems to work fine, so I guess this ticket should be closed. Thanks alot!

**Comment by braver** [comment]
🎉
