### ISSUE TITLE
Optionally disable the fall back to outlines (for underlines)

### ISSUE THREAD

**Issue by Djspaceg** [SublimeLinter/SublimeLinter#1105]
I've been tinkering around with the `mark_style` options, and some of them don't appear to be working for me. What _does_ appear when any of the `solid_underline`, `stippled_underline`, or `squiggly_underline` styles are selected is `"outline"` instead. `"fill"`, `"outline"` and `"none"` each work as expected, so it seems likely that the system is generally working but something is amiss.

I noticed that the docs mentioned `ST > 3148.` in the `region.colorish` section, and discovered that I'm on macOS version `3143`. Even after running "Check for Updates", it says there are none available.

SublimeLinter used to display the squiggly underline on this version, just not anymore. Have I misconfigured something?

**Comment by kaste** [comment]
Sublime can't draw squiggles on whitespace, so we draw an outline instead. All typical errors should use underline et.al.

**Comment by Djspaceg** [comment]
Ah, I see. It looks like if there are _any_ whitespaces in the highlighted line, it's converted to `outline`.

A misspelled word is squiggly underlined but if there's a space in it, the whole line becomes outlined.

Was this a recent change? It didn't seem familiar to me.

**Comment by kaste** [comment]
Yes, that's a pretty new.

**Comment by Djspaceg** [comment]
Bummer. Ok.

I assume it's also not possible to draw just the bottom solid line of the outline for the designated text.

Could be helpful to include a sentence about this in the Default Settings template file.

**Comment by braver** [comment]
> Could be helpful to include a sentence about this in the Default Settings template file.

Good idea!

**Comment by dangh** [comment]
Is there anyway I can set it to underline the first word only? Outline the whole code block because of a warning is distracting.

**Comment by braver** [comment]
There’s an option to “demote” (hide) highlights that contain white space when your editing. That’s a bit of an experiment, but you could try that to see if it helps.

**Comment by dangh** [comment]
Hi @braver, demoting only help when you're typing, but most of the time you spending is reading code.

I don't see much benefit from highlighting the whole code block. The error message and the start location is enough to help spotting out the error. Highlighting the whole block is just adding noise. (I blame the way ST outlining the text).

As you can see in my screenshot below, my generator is missing `yield` statement. Highlight the function keyword is enough in this case while outlining the whole function makes it unbearable to read the code. Also it overlaps two other warnings and make them hard to spoting out.

<img width="680" alt="screen shot 2018-03-06 at 3 27 38 pm" src="https://user-images.githubusercontent.com/1020347/37019587-ca601480-2153-11e8-9c9d-1fc735d5004f.png">

**Comment by braver** [comment]
@dangh Aha, that does look annoying. If I'm right we're highlighting what the linter tells us to. Could you perhaps share what the linter prints out for this? You can run it with debug on and the full message will be printed to the console.

**Comment by dangh** [comment]
@braver Here's the console output:

```
SublimeLinter: #85 linter.py:809: eslint output:
    [{"filePath":"/Users/dang/Desktop/wip/cnms/src/sagas/flow-manager.js","messages":[{"ruleId":"no-unused-vars","severity":1,"message":"'next' is assigned a value but never used.","line":37,"column":9,"nodeType":"Identifier","source":"  const next = function*(event) {","endLine":37,"endColumn":13},{"ruleId":"require-yield","severity":1,"message":"This generator function does not have 'yield'.","line":48,"column":10,"nodeType":"FunctionExpression","source":"  return function*(payload, reduxAction) {","endLine":65,"endColumn":4},{"ruleId":"no-unused-vars","severity":1,"message":"'event' is assigned a value but never used.","line":51,"column":11,"nodeType":"Identifier","source":"    const event = {","endLine":51,"endColumn":16},{"ruleId":"no-unused-vars","severity":1,"message":"'handleStepActions' is assigned a value but never used.","line":59,"column":11,"nodeType":"Identifier","source":"    const handleStepActions = function*(state, params) {","endLine":59,"endColumn":28}],"errorCount":0,"warningCount":4,"fixableErrorCount":0,"fixableWarningCount":0,"source":"import {Machine} from 'xstate'\nimport {call} from 'redux-saga/effects'\nimport invariant from 'invariant'\nimport {is} from '~/util'\n\nexport function createStore() {\n  const store = new Map()\n\n  return {\n    has: id => store.has(id),\n    get: id => store.get(id),\n    set: (id, state) => store.set(id, state)\n  }\n}\n\nconst defaultStore = createStore()\n\n/**\n * transition: (state, chart, event) -> (state, actions)\n * step: (state, chart, event) -> state // continuous transition and execute actions\n * flow: (chart, state, reduxAction) -> state // step with provided action as event, inject [payload, action] as event params\n */\n\n/**\n * Transition from one state to another.\n * Equivalent to machine.transition()\n */\nexport function step(chart, currentState, event) {\n  const machine = Machine(chart)\n  const nextState = machine.transition(currentState, event)\n  return nextState\n}\n\nexport function* walk(chart, currentState, event, command) {\n  let nextState = yield call(step, chart, currentState, event)\n\n  const next = function*(event) {\n    yield call(step, chart, nextState, event)\n  }\n\n  const finalState = yield call(command, nextState, event.params)\n  return finalState\n}\n\nexport function flow(chart, actionMap, identity, store = defaultStore) {\n  const machine = Machine(chart)\n\n  return function*(payload, reduxAction) {\n    const id = identity(payload, reduxAction)\n    const currentState = store.has(id) ? store.get(id) : machine.initialState\n    const event = {\n      type: reduxAction.type,\n      params: [payload, reduxAction]\n    }\n    let state = currentState\n    const transitionShortHand = function*(event) {\n      state = yield call(walk, chart, state, event)\n    }\n    const handleStepActions = function*(state, params) {\n      for (const action of state.actions) {\n        yield call(actionMap[action], payload, reduxAction, {next: transitionShortHand})\n      }\n      return state\n    }\n  }\n}\n\n/**\n * Given events, produces actions\n */\nexport function* transition(chart, actionMap, currentState, event, extendedState, onTransition) {\n  const machine = Machine(chart)\n\n  let nextState = machine.transition(currentState, event, extendedState)\n  if (is.func(onTransition)) yield call(onTransition, nextState)\n\n  const params = event.params || []\n\n  const continueTransition = function*(nextEvent) {\n    if (is.string(nextEvent)) {\n      nextEvent = {\n        type: nextEvent,\n        params\n      }\n    } else if (is.object(nextEvent) && is.string(nextEvent.type)) {\n      nextEvent = {\n        ...nextEvent,\n        params\n      }\n    } else {\n      throw new Error(`Invalid event type: ${nextEvent}`)\n    }\n\n    nextState = yield call(transition, chart, actionMap, nextState, nextEvent, extendedState, {\n      onTransition\n    })\n  }\n\n  for (const action of nextState.actions) {\n    yield call(actionMap[action], ...params, {transition: continueTransition})\n  }\n\n  return nextState\n}\n\nexport function create(chart, actionMap, identity, store = defaultStore) {\n  guardActionsHandled(chart, actionMap)\n\n  const machine = Machine(chart)\n\n  return function* handleExternalAction(payload, action) {\n    const id = identity(payload, action)\n    const currentState = store.has(id) ? store.get(id) : machine.initialState\n    const event = {\n      type: action.type,\n      params: [action.payload, action]\n    }\n\n    yield call(transition, machine, actionMap, currentState, event, null, state =>\n      store.set(id, state)\n    )\n  }\n}\n\nexport default {\n  create\n}\n\n/**\n * Helper functions\n */\n\nfunction guardActionsHandled(chart, actionMap) {\n  const unhandledActions = findUnhandledActions(chart, actionMap)\n  invariant(is.empty(unhandledActions), 'Unhandled actions: %s', unhandledActions.join(', '))\n}\n\nfunction getAllActionsFromChart(chart) {\n  const states = Object.values(chart.states)\n  return [].concat(...states.map(getAllActionsFromState))\n}\n\nfunction getAllActionsFromState(state) {\n  if (!is.object(state)) return []\n\n  let result = []\n\n  if (is.array(state.onEntry)) result = result.concat(state.onEntry)\n  if (is.array(state.onExit)) result = result.concat(state.onExit)\n  if (is.object(state.on)) {\n    const transitions = Object.values(state.on)\n    result = result.concat(...transitions.map(getAllActionsFromTransition))\n  }\n\n  return result\n}\n\nfunction getAllActionsFromTransition(transition) {\n  if (!is.object(transition)) return []\n\n  const state = Object.keys(transition)[0]\n  const actions = transition[state].actions\n\n  return is.array(actions) ? actions : []\n}\n\nfunction findUnhandledActions(chart, actionMap) {\n  const actions = getAllActionsFromChart(chart)\n  const actionTypes = actions.map(x => (is.object(x) ? x.type : x))\n  const uniqueActionTypes = [...new Set(actionTypes)]\n  const unhandledActionTypes = uniqueActionTypes.filter(x => !is.func(actionMap[x]))\n  return unhandledActionTypes\n}\n"}]
SublimeLinter: #85 SublimeLinter-eslint.sublime-package:56: eslint output:
[{'errorCount': 0,
  'filePath': '/Users/dang/Desktop/wip/cnms/src/sagas/flow-manager.js',
  'fixableErrorCount': 0,
  'fixableWarningCount': 0,
  'messages': [{'column': 9,
                'endColumn': 13,
                'endLine': 37,
                'line': 37,
                'message': "'next' is assigned a value but never used.",
                'nodeType': 'Identifier',
                'ruleId': 'no-unused-vars',
                'severity': 1,
                'source': '  const next = function*(event) {'},
               {'column': 10,
                'endColumn': 4,
                'endLine': 65,
                'line': 48,
                'message': "This generator function does not have 'yield'.",
                'nodeType': 'FunctionExpression',
                'ruleId': 'require-yield',
                'severity': 1,
                'source': '  return function*(payload, reduxAction) {'},
               {'column': 11,
                'endColumn': 16,
                'endLine': 51,
                'line': 51,
                'message': "'event' is assigned a value but never used.",
                'nodeType': 'Identifier',
                'ruleId': 'no-unused-vars',
                'severity': 1,
                'source': '    const event = {'},
               {'column': 11,
                'endColumn': 28,
                'endLine': 59,
                'line': 59,
                'message': "'handleStepActions' is assigned a value but never used.",
                'nodeType': 'Identifier',
                'ruleId': 'no-unused-vars',
                'severity': 1,
                'source': '    const handleStepActions = function*(state, params) {'}],
  'source': "import {Machine} from 'xstate'\nimport {call} from 'redux-saga/effects'\nimport invariant from 'invariant'\nimport {is} from '~/util'\n\nexport function createStore() {\n  const store = new Map()\n\n  return {\n    has: id => store.has(id),\n    get: id => store.get(id),\n    set: (id, state) => store.set(id, state)\n  }\n}\n\nconst defaultStore = createStore()\n\n/**\n * transition: (state, chart, event) -> (state, actions)\n * step: (state, chart, event) -> state // continuous transition and execute actions\n * flow: (chart, state, reduxAction) -> state // step with provided action as event, inject [payload, action] as event params\n */\n\n/**\n * Transition from one state to another.\n * Equivalent to machine.transition()\n */\nexport function step(chart, currentState, event) {\n  const machine = Machine(chart)\n  const nextState = machine.transition(currentState, event)\n  return nextState\n}\n\nexport function* walk(chart, currentState, event, command) {\n  let nextState = yield call(step, chart, currentState, event)\n\n  const next = function*(event) {\n    yield call(step, chart, nextState, event)\n  }\n\n  const finalState = yield call(command, nextState, event.params)\n  return finalState\n}\n\nexport function flow(chart, actionMap, identity, store = defaultStore) {\n  const machine = Machine(chart)\n\n  return function*(payload, reduxAction) {\n    const id = identity(payload, reduxAction)\n    const currentState = store.has(id) ? store.get(id) : machine.initialState\n    const event = {\n      type: reduxAction.type,\n      params: [payload, reduxAction]\n    }\n    let state = currentState\n    const transitionShortHand = function*(event) {\n      state = yield call(walk, chart, state, event)\n    }\n    const handleStepActions = function*(state, params) {\n      for (const action of state.actions) {\n        yield call(actionMap[action], payload, reduxAction, {next: transitionShortHand})\n      }\n      return state\n    }\n  }\n}\n\n/**\n * Given events, produces actions\n */\nexport function* transition(chart, actionMap, currentState, event, extendedState, onTransition) {\n  const machine = Machine(chart)\n\n  let nextState = machine.transition(currentState, event, extendedState)\n  if (is.func(onTransition)) yield call(onTransition, nextState)\n\n  const params = event.params || []\n\n  const continueTransition = function*(nextEvent) {\n    if (is.string(nextEvent)) {\n      nextEvent = {\n        type: nextEvent,\n        params\n      }\n    } else if (is.object(nextEvent) && is.string(nextEvent.type)) {\n      nextEvent = {\n        ...nextEvent,\n        params\n      }\n    } else {\n      throw new Error(`Invalid event type: ${nextEvent}`)\n    }\n\n    nextState = yield call(transition, chart, actionMap, nextState, nextEvent, extendedState, {\n      onTransition\n    })\n  }\n\n  for (const action of nextState.actions) {\n    yield call(actionMap[action], ...params, {transition: continueTransition})\n  }\n\n  return nextState\n}\n\nexport function create(chart, actionMap, identity, store = defaultStore) {\n  guardActionsHandled(chart, actionMap)\n\n  const machine = Machine(chart)\n\n  return function* handleExternalAction(payload, action) {\n    const id = identity(payload, action)\n    const currentState = store.has(id) ? store.get(id) : machine.initialState\n    const event = {\n      type: action.type,\n      params: [action.payload, action]\n    }\n\n    yield call(transition, machine, actionMap, currentState, event, null, state =>\n      store.set(id, state)\n    )\n  }\n}\n\nexport default {\n  create\n}\n\n/**\n * Helper functions\n */\n\nfunction guardActionsHandled(chart, actionMap) {\n  const unhandledActions = findUnhandledActions(chart, actionMap)\n  invariant(is.empty(unhandledActions), 'Unhandled actions: %s', unhandledActions.join(', '))\n}\n\nfunction getAllActionsFromChart(chart) {\n  const states = Object.values(chart.states)\n  return [].concat(...states.map(getAllActionsFromState))\n}\n\nfunction getAllActionsFromState(state) {\n  if (!is.object(state)) return []\n\n  let result = []\n\n  if (is.array(state.onEntry)) result = result.concat(state.onEntry)\n  if (is.array(state.onExit)) result = result.concat(state.onExit)\n  if (is.object(state.on)) {\n    const transitions = Object.values(state.on)\n    result = result.concat(...transitions.map(getAllActionsFromTransition))\n  }\n\n  return result\n}\n\nfunction getAllActionsFromTransition(transition) {\n  if (!is.object(transition)) return []\n\n  const state = Object.keys(transition)[0]\n  const actions = transition[state].actions\n\n  return is.array(actions) ? actions : []\n}\n\nfunction findUnhandledActions(chart, actionMap) {\n  const actions = getAllActionsFromChart(chart)\n  const actionTypes = actions.map(x => (is.object(x) ? x.type : x))\n  const uniqueActionTypes = [...new Set(actionTypes)]\n  const unhandledActionTypes = uniqueActionTypes.filter(x => !is.func(actionMap[x]))\n  return unhandledActionTypes\n}\n",
  'warningCount': 4}]
no command for selector: noop:
```

**Comment by jtheletter** [comment]
I opened https://github.com/SublimeLinter/SublimeLinter/issues/1112, but it was closed in favor of this ticket. Here's what I added over there: 

I prefer stippled underlines rather than outlines. So I added the following code to my `~/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings` (the only change is to "mark_style"): 
```
    "styles": [
        {
            "mark_style": "stippled_underline",
            "priority": 1,
            "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
            "icon": "dot",
            "types": [
                "warning"
            ]
        },
        {
            "mark_style": "stippled_underline",
            "priority": 1,
            "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
            "icon": "dot",
            "types": [
                "error"
            ]
        }
    ]
```

The result is a mix of styles (solid underlines, stippled underlines, and outlines): 
![pic 2018-03-05 at 16 44 28](https://user-images.githubusercontent.com/4712441/37007994-e970c3e8-2094-11e8-88ac-fcb34e2748aa.png)

If I remove the above code from my user config, the styles revert to all being simply outlines: 
![pic 2018-03-05 at 16 45 20](https://user-images.githubusercontent.com/4712441/37008017-ffb0a1aa-2094-11e8-8a2c-4e59ceef9513.png)

SublimeLinter 4.0.2
Sublime Text 3.0
macOS 10.13.3

**Comment by braver** [comment]
So, the actionable content here is to introduce a setting to disable the fallback to outlines.

**Comment by FichteFoll** [comment]
I think the more reasonable action is to only highlight the first word, as happened in SL3? That's at least what I think is being requested.

**Comment by braver** [comment]
Ehm, yeah, that too because otherwise you visually create multiple highlights for one problem.

**Comment by Djspaceg** [comment]
Is it possible to tell Sublime Text to highlight as a simpler rectangle shape, rather than contouring to the trailing side? Seems like that would be less visually annoying while still highlighting the entire block. If the highlight area is more than say, 2 lines, switch to a full-window-width rectangle.

**Comment by braver** [comment]
Nopes, it doesn't do that.

**Comment by kaste** [comment]
I have two questions. @jtheletter showed the following

![image](https://user-images.githubusercontent.com/8558/37085706-048c840c-21f6-11e8-9648-2c08a5627e74.png)

Is this still eslint with a custom plugin?

What is that yellow underscore on the beginning of most lines?

**Comment by braver** [comment]
The underscore is how ST renders a zero length region at col 0. We use that in the panel too, remember?

**Comment by kaste** [comment]
But I also remember that we always try to have a length of 1.

**Comment by braver** [comment]
Good point. I’ve always had those underscores in some linters though (stylelint IIRC).

**Comment by jtheletter** [comment]
> Is this still eslint with a custom plugin?

@kaste: As I demonstrated on https://github.com/eslint/eslint/issues/9981, I've no custom plugins installed. Also, the screenshot above in this ticket is from a CSS file.

**Comment by jtheletter** [comment]
> The underscore is how ST renders a zero length region at col 0. 

@braver: Why does the underscore (solid underline) only appear in the screenshot of mixed marks?

**Comment by braver** [comment]
So, you’re linting a stylesheet using eslint without plugins? How does that work? I need to know more about your setup before I can say anything useful about it, and we shouldn’t be doing that in this thread.

**Comment by jtheletter** [comment]
I'm not linting a stylesheet using ESLint, with or without plugins. I was answering @kaste's question of "Is this still eslint with a custom plugin?", the answer to which is no, that's a separate issue.

**Comment by braver** [comment]
@jtheletter right now to me it looks like you're confusing everyone and mixing up eslint and SublimeLinter and plugins. Just please share your SL user settings and a full debug log (enable debug and restart ST), so I can understand what your setup looks like.

**Comment by jtheletter** [comment]
Again, please, my issue here, which was moved from https://github.com/SublimeLinter/SublimeLinter/issues/1112, has nothing to do with ESLint. I only mentioned ESLint to answer the question of whether my concern involves ESLint, which it doesn't. 

Here's my complete `/Users/JP/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings` (now with the `"styles"` array, which appears above, removed): 

```
{
    "delay": 0,

    "linters": {
        "scss": {
            "excludes": [
                "*.css"
            ]
        }
    }
}
```

If I add to the above file `"debug": false,` (the "Debug" menu command is now gone from Sublime Text), restart Sublime, this is in my ST console: 

```
startup, version: 3143 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: [~]/Library/Application Support/Sublime Text 3/Packages
state path: [~]/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: [~]/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.724549
startup time: 0.791376
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin AlignTab.aligner
reloading plugin AlignTab.aligntab
reloading plugin AlignTab.hist
reloading plugin AlignTab.parser
reloading plugin AlignTab.table
reloading plugin AlignTab.wclen
reloading plugin Case Conversion.case_conversion
reloading plugin Case Conversion.case_parse
reloading plugin Colorsublime.colorsublime-plugin
reloading plugin GitHub Flavored Markdown Preview.GHMarkdownPreview
reloading plugin LESS.less_completions
reloading plugin LiveStyle.livestyle
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-contrib-htmlhint.linter
reloading plugin SublimeLinter-contrib-scss-lint.linter
reloading plugin SublimeLinter-csslint.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-jshint.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-php.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
reloading plugin Babel.Babel
reloading plugin LiveStyle.livestyle-plugin
reloading plugin Speak Selected Text.SpeakSelectedText
reloading plugin sublime-cross.cross
sublime-cross init
plugins loaded
LiveStyle: Start app
LiveStyle: Client connection error: [Errno 61] Connection refused
LiveStyle: Create own server on port 54000
LiveStyle: Starting LiveStyle server on port 54000
LiveStyle: Client connected
environment variables loaded using: /bin/bash -l
Package Control: Skipping automatic upgrade, last run at 2018-03-07 11:13:37, next run at 2018-03-07 12:13:37 or after
```

**Comment by braver** [comment]
Debugging works better when you set it to `true` 😉 I'm kinda curious as to what your linter reports when it produces the highlights you see in the screenshot, and those should be in the log.

Also, scss-lint is a dead project right? Have you tried stylelint?

**Comment by jtheletter** [comment]
Apologies, multitasking failure. Debug now most assuredly set to `true`, quit/relaunch ST, console: 

```
startup, version: 3143 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: [~]/Library/Application Support/Sublime Text 3/Packages
state path: [~]/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: [~]/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 1.07533
startup time: 1.25546
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin AlignTab.aligner
reloading plugin AlignTab.aligntab
reloading plugin AlignTab.hist
reloading plugin AlignTab.parser
reloading plugin AlignTab.table
reloading plugin AlignTab.wclen
reloading plugin Case Conversion.case_conversion
reloading plugin Case Conversion.case_parse
reloading plugin Colorsublime.colorsublime-plugin
reloading plugin GitHub Flavored Markdown Preview.GHMarkdownPreview
reloading plugin LESS.less_completions
reloading plugin LiveStyle.livestyle
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-contrib-htmlhint.linter
reloading plugin SublimeLinter-contrib-scss-lint.linter
reloading plugin SublimeLinter-csslint.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-jshint.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-php.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
reloading plugin Babel.Babel
reloading plugin LiveStyle.livestyle-plugin
reloading plugin Speak Selected Text.SpeakSelectedText
reloading plugin sublime-cross.cross
sublime-cross init
plugins loaded
SublimeLinter: SublimeLinter.sublime-package:71: Logging installed; log level INFO
SublimeLinter: SublimeLinter.sublime-package:62: debug mode: on
SublimeLinter: SublimeLinter.sublime-package:63: version: 4.0.5
LiveStyle: Start app
LiveStyle: Client connection error: [Errno 61] Connection refused
LiveStyle: Create own server on port 54000
LiveStyle: Starting LiveStyle server on port 54000
LiveStyle: Client connected
environment variables loaded using: /bin/bash -l
Package Control: Skipping automatic upgrade, last run at 2018-03-07 13:43:55, next run at 2018-03-07 14:43:55 or after
```

Re-add the `"styles"` array  as above, re-open that CSS file, mixed marks re-appear, ST console shows: 

```
SublimeLinter: #12 csslint [filename].css ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in [~]/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in [~]/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 813, in lint
  File "lint.linter in [~]/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 847, in find_errors
  File "linter in [~]/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-csslint.sublime-package", line 57, in split_match
TypeError: 'NoneType' object is not iterable
```

And yes, scss-lint is abandoned by two years. I've not yet tried stylelint. I tried sass-lint, but couldn't get the config to work (https://github.com/sasstools/sass-lint/issues/1178).

**Comment by braver** [comment]
I’ve used stylelint for a while now, with complete satisfaction. The plugin seems to behave well too.

This issue though, is just becoming a rabbit hole. I’m not even sure what we’re trying to fix here.

**Comment by jtheletter** [comment]
Thanks for the recommendation on a new SCSS linter. 

I agree this ticket is getting long; that was not my intention. I reported (https://github.com/SublimeLinter/SublimeLinter/issues/1112) that mixed mark styles appeared upon choosing a new mark style. That ticket was closed in favor of this one, so I copied my report here. That is all.

**Comment by braver** [comment]
Ok, I’m going to remove some comments then. If you want help with something specific, please open a new issue.

**Comment by kaste** [comment]
So, that's all funny enough. 

So, basically the workaround was made for multiline errors. And for that it will stay bc imagine the nice picture @dangh showed if it would squiggle 10 lines of code. 😨 

Now, multiline errors are actually opt-in by plugins and only flake8 (mildly) and eslint do that (these are the showcase plugins to try the new API). flake8 people probably won't complain here. 

I switched eslint to just take the complete available output/info it provides and that's really something else to what we had before, but we have an issue there and it must be resolved over there. 

I'm closing.

**Comment by kaste** [comment]
If someone can confirm that we have visual errors on the first column (solid underline), I think that's a bug.

**Comment by braver** [comment]
I’ll keep an eye out for those.

**Comment by Fingel** [comment]
For anyone else finding this issue, setting mark style to "none" in the `mark_style` key in the `styles` section of the Sublimelinter config is the only way I could find to remove the outlines (which I find extremely distracting, as they appear as I'm still typing). I'll look forward to getting my squiggly lines back, but for now I'll just have to do with the gutter marks.

**Comment by jtheletter** [comment]
I'm unsure why this was closed, since it seems we still can't change the mark style?

**Comment by braver** [comment]
There is some discussion in #1171

**Comment by Slapbox** [comment]
It's hard to articulate just how distracting this is when entire blocks of your code light up with these outlines. Clicking within the outline doesn't even provide context on what's wrong.

**Comment by Slapbox** [comment]
Possible workaround for those interested (only for Javascript using ESLint_d) https://github.com/SublimeLinter/SublimeLinter/issues/1171#issuecomment-375021599

**Comment by JeanMertz** [comment]
Putting my vote down for a fallback that's less "ugly"/distracting than the full outlines.

Another "workaround" for linters that often span multiple words (such as the [write-good](https://github.com/ckaznocha/SublimeLinter-contrib-write-good) linter), is to disable any inline styles only for that specific linter as suggested by @braver here:

https://github.com/SublimeLinter/SublimeLinter/issues/1171#issuecomment-371966859
