### ISSUE TITLE
Linter crashing only on certain errors

### ISSUE THREAD

**Issue by jarodccrowe** [SublimeLinter/SublimeLinter#1108]
I am receiving this error occasionally when the linter finds something, most things are working fine. Using eslint. Probably something wrong in my config for version 4 but not sure what to change, have been through the supplied docs. 

```
SublimeLinter: #155 eslint FileName.js ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /home/user/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /home/user/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 813, in lint
  File "linter in /home/user/.config/sublime-text-3/Installed Packages/SublimeLinter-eslint.sublime-package", line 67, in find_errors
KeyError: 'ruleId'
```

**Comment by kaste** [comment]
Please file against eslint with full log output.

**Comment by kaste** [comment]
Hi @jarodccrowe . Maybe that was a bit rude, not detailed enough yesterday. But this bug is relevant, and I wanted to fix it (probably easy to do) today. I would need the full log, essentially the output that eslint itself produces. 

(I really hope you didn't file it against eslint core, bc I meant our SublimeLinter-eslint 😢 )

**Comment by FichteFoll** [comment]
For reference, it's this one: https://github.com/SublimeLinter/SublimeLinter-eslint
