### ISSUE TITLE
4.0.3 crashes

### ISSUE THREAD

**Issue by kgizdov** [SublimeLinter/SublimeLinter#1117]
Hi,

Just upgraded to 4.0.3 and the whole linter crashes with:
```sh
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "highlight_view in /home/gizdov/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 158, in on_selection_modified_async
  File "lint.settings in /home/gizdov/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 33, in get
  File "lint.settings in /home/gizdov/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 25, in settings
AttributeError: 'NoneType' object has no attribute 'load_settings'
```

**Comment by braver** [comment]
Does the problem remain after a restart?

**Comment by kgizdov** [comment]
needed to reinstall, but now it works

**Comment by zoheiry** [comment]
I have the same issue, after the upgrade nothing is working anymore
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "status_bar_view in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 55, in on_activated_async
  File "status_bar_view in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 76, in draw
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 33, in get
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 25, in settings
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "sublime_linter in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 122, in on_activated_async
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 33, in get
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 25, in settings
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "status_bar_view in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 55, in on_activated_async
  File "status_bar_view in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 76, in draw
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 33, in get
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 25, in settings
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "sublime_linter in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 122, in on_activated_async
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 33, in get
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 25, in settings
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "highlight_view in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 158, in on_selection_modified_async
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 33, in get
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 25, in settings
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "highlight_view in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 158, in on_selection_modified_async
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 33, in get
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 25, in settings
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "highlight_view in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 158, in on_selection_modified_async
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 33, in get
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 25, in settings
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "status_bar_view in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 55, in on_activated_async
  File "status_bar_view in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 76, in draw
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 33, in get
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 25, in settings
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "sublime_linter in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 122, in on_activated_async
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 33, in get
  File "lint.settings in /Users/ali/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 25, in settings
AttributeError: 'NoneType' object has no attribute 'load_settings'
```

**Comment by zoheiry** [comment]
After Uninstalling and Installing it again it work, thanks!

**Comment by braver** [comment]
💯
