### ISSUE TITLE
SublimeLinter 4.0.3 broken, doesn't update to v4.0.4

### ISSUE THREAD

**Issue by laukstein** [SublimeLinter/SublimeLinter#1141]
Recent ST3 autoupdate to SublimeLinter 4.0.3 returns errors, doesn't works.
Checking for updated doesn't update to v4.0.4.

![grabilla em5476](https://user-images.githubusercontent.com/183966/37076948-557a82ac-21e1-11e8-9c56-7f0eaa6ff1dc.png)

```
...
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.lint
NO RELOAD SublimeLinter.lint.const
NO RELOAD SublimeLinter.lint.util
NO RELOAD SublimeLinter.lint.linter
NO RELOAD SublimeLinter.lint.base_linter
NO RELOAD SublimeLinter.lint.base_linter.python_linter
NO RELOAD SublimeLinter.lint.base_linter.ruby_linter
NO RELOAD SublimeLinter.lint.base_linter.node_linter
NO RELOAD SublimeLinter.lint.base_linter.composer_linter
NO RELOAD SublimeLinter.lint.backend
NO RELOAD SublimeLinter.lint.events
NO RELOAD SublimeLinter.lint.persist
NO RELOAD SublimeLinter.lint.queue
NO RELOAD SublimeLinter.lint.reloader
NO RELOAD SublimeLinter.lint.settings
NO RELOAD SublimeLinter.lint.style
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.lint
Traceback (most recent call last):
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 57, in reload_package
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 143, in reload_modules
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 107, in reload_plugin
    m = imp.reload(m)
  File "./python3.3/imp.py", line 276, in reload
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
RuntimeError: maximum recursion depth exceeded during compilation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 59, in reload_package
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 143, in reload_modules
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 107, in reload_plugin
    m = imp.reload(m)
  File "./python3.3/imp.py", line 276, in reload
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
RuntimeError: maximum recursion depth exceeded during compilation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 157, in reload_plugin
    m.plugin_loaded()
  File "sublime_linter in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 55, in plugin_loaded
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 25, in reload_everything
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 30, in reload_core
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 61, in reload_package
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 75, in ensure_loaded
ValueError: too many values to unpack (expected 2)
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-contrib-stylelint.linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 157, in reload_plugin
    m.plugin_loaded()
  File "sublime_linter in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 55, in plugin_loaded
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 26, in reload_everything
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 35, in reload_linter_plugins
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 48, in reload_plugin
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 107, in reload_plugin
    m = imp.reload(m)
  File "./python3.3/imp.py", line 276, in reload
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 853, in _load_module
  File "<frozen importlib._bootstrap>", line 980, in get_code
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
RuntimeError: maximum recursion depth exceeded during compilation
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-contrib-stylelint.linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 157, in reload_plugin
    m.plugin_loaded()
  File "sublime_linter in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 55, in plugin_loaded
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 26, in reload_everything
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 35, in reload_linter_plugins
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 48, in reload_plugin
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 107, in reload_plugin
    m = imp.reload(m)
  File "./python3.3/imp.py", line 276, in reload
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 853, in _load_module
  File "<frozen importlib._bootstrap>", line 980, in get_code
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
RuntimeError: maximum recursion depth exceeded during compilation
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-contrib-stylelint.linter
...
```

**Comment by braver** [comment]
The meat of it seems to be this: 

```
Traceback (most recent call last):
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 57, in reload_package
  File "lint.reloader in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 143, in reload_modules
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 107, in reload_plugin
    m = imp.reload(m)
  File "./python3.3/imp.py", line 276, in reload
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
RuntimeError: maximum recursion depth exceeded during compilation
```

Something wrong with the reloader?

**Comment by laukstein** [comment]
@braver in additional ST3 startup showed error

> WARNING: eslint cannot locate 'eslint'

after `npm -g i eslint` errors went away (eslint previously wasn't installed globally, and worked fine also with this errors).

On `npm remove eslint` running ESLint in ST3 will show error:

```
module.js:557
    throw err;
    ^

Error: Cannot find module 'eslint'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\Sublime Text 3\Packages\ESLint\linter.js:21:12)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
[Finished in 0.4s]
```

So I am required to use both `npm -g i eslint` and `npm i eslint` to make it work without errors.

**Comment by braver** [comment]
yeah, that’s not necessarily a bug. Please check over at the SublimeLinter-eslint repo for more info on configuring eslint,

**Comment by laukstein** [comment]
@braver this seems related to https://github.com/SublimeLinter/SublimeLinter-eslint/issues/220

**Comment by laukstein** [comment]
Who closed this issue when still haven't been fixed (or perhaps this is different bug)? Having:

    internal/modules/cjs/loader.js:583
        throw err;
        ^

    Error: Cannot find module 'eslint'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
        at Function.resolve (internal/modules/cjs/helpers.js:30:19)
        at Object.<anonymous> (C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\ESLint\linter.js:19:13)
        at Module._compile (internal/modules/cjs/loader.js:689:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
        at startup (internal/bootstrap/node.js:279:19)
    [Finished in 0.2s]

**Comment by kaste** [comment]
The above traceback does not come from SublimeLinter.
