### ISSUE TITLE
version 4.0.5 is broken when start

### ISSUE THREAD

**Issue by Jakitto** [SublimeLinter/SublimeLinter#1146]
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 72, in on_selection_modified_async
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 84, in draw
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in messages_under_cursor
KeyError: 19
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 72, in on_selection_modified_async
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 84, in draw
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in messages_under_cursor
KeyError: 20
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 72, in on_selection_modified_async
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 84, in draw
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in messages_under_cursor
KeyError: 17
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 72, in on_selection_modified_async
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 84, in draw
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in messages_under_cursor
KeyError: 15
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 72, in on_selection_modified_async
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 84, in draw
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in messages_under_cursor
KeyError: 20
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 72, in on_selection_modified_async
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 84, in draw
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in messages_under_cursor
KeyError: 19

**Comment by goodrank** [comment]
confirm

**Comment by braver** [comment]
Is that just right after the upgrade or does it persist after restarts?

**Comment by kaste** [comment]
Thanks for reporting. 

@braver If you do wild PRs you MUST squash merge otherwise `git blame` becomes useless. See:

![image](https://user-images.githubusercontent.com/8558/37083095-be19f88a-21ee-11e8-9fa6-90eb708754a8.png)

**Comment by braver** [comment]
@kaste thanks for the pointer, I'll look out for that in the future.
