### ISSUE TITLE
CSSLinter not working with latest SublimeLinter update

### ISSUE THREAD

**Issue by leem32** [SublimeLinter/SublimeLinter#1151]
I've updated CSSLinter to latest 1.0.5 and restarted Sublime text a few times after SublimeLinter update, but the error still appears.

```
SublimeLinter: #133 csslint styleold.css ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\Lee\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in C:\Users\Lee\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 813, in lint
  File "lint.linter in C:\Users\Lee\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 847, in find_errors
  File "linter in C:\Users\Lee\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-csslint.sublime-package", line 57, in split_match
TypeError: 'NoneType' object is not iterable

**Comment by kaste** [comment]
I made this 🐛 😞 😢

**Comment by minitauros** [comment]
I'm getting a same sort of error:

`AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "sublime_linter in /home/stephan/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 122, in on_activated_async
  File "lint.settings in /home/stephan/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 33, in get
  File "lint.settings in /home/stephan/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 25, in settings
AttributeError: 'NoneType' object has no attribute 'load_settings'`

**Comment by kaste** [comment]
@minitauros  That's not the same error it has a completely different stack trace and different error.

**Comment by minitauros** [comment]
> @minitauros That's not the same error it has a completely different stack trace and different error.

Woops you're totally right. I'll create a separate issue.

**Comment by minitauros** [comment]
Also, after a restart the issue has been resolved. Supah weird. Sorry for the wasting of time!
