### ISSUE TITLE
Bootlint not working with latest SublimeLinter update

### ISSUE THREAD

**Issue by cyoung502** [SublimeLinter/SublimeLinter#1157]
`SublimeLinter: #6 bootlint index.html ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\chriyou\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in C:\Users\chriyou\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 813, in lint
  File "lint.linter in C:\Users\chriyou\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 847, in find_errors
  File "linter in C:\Users\chriyou\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-contrib-bootlint.sublime-package", line 39, in split_match
TypeError: 'NoneType' object is not iterable`

**Comment by braver** [comment]
Try some stuff from the [troubleshooting guide](https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/troubleshooting.rst) and tell us how that worked out. Also, full debug logs are super useful.

**Comment by nvtkaszpir** [comment]
This error hits also other plugins, the culprit is in https://github.com/SublimeLinter/SublimeLinter/blob/master/lint/linter.py#L1169
because `cmd` is set as None and thus is not iterable.

**Comment by kaste** [comment]
Super confusing bc there is no line 39 in that file https://github.com/thomas-lebeau/SublimeLinter-contrib-bootlint/blob/master/linter.py

**Comment by nvtkaszpir** [comment]
The error message is pretty awful:
- line 97 is in backend.py
- line 813 is in lint.py
- line 847 in lint.py
...
I assume line 39 is somwhere in imported class? :D

**Comment by kaste** [comment]
It's an older version, master does not have this line.

**Comment by kaste** [comment]
So, I probably close. Maybe @braver takes the linter.

**Comment by braver** [comment]
If there are problems with the contrib plugin, first try complaining there. We can always talk about moving it into the org, but I currently don’t want to do so if there is a chance of someone else actually maintaining their stuff.
