### ISSUE TITLE
'NoneType' object has no attribute 'load_settings' on v4.0.5

### ISSUE THREAD

**Issue by nicklolsen** [SublimeLinter/SublimeLinter#1161]
I'm getting this error:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 496, in on_modified_async
    callback.on_modified_async(v)
  File "sublime_linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 104, in on_modified_async
  File "lint.settings in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 33, in get
  File "lint.settings in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 25, in settings
AttributeError: 'NoneType' object has no attribute 'load_settings'
```

I can't find any other issues that address this. Not sure where to start. debug mode is on, but I'm not getting anything else.

**Comment by nicklolsen** [comment]
Here is a whole bunch of other stuff I found in the console once I restarted:

```
startup, version: 3143 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/nick/Library/Application Support/Sublime Text 3/Packages
state path: /Users/nick/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["0_package_control_loader", "Vintage"]
Errors parsing theme:
icon_file_type is missing layer0.opacity, setting to 1.0 for backwards compatibility
icon_folder is missing layer0.opacity, setting to 1.0 for backwards compatibility
icon_folder_loading is missing layer0.opacity, setting to 1.0 for backwards compatibility
pre session restore time: 0.389479
using gpu buffer for window
using gpu buffer for window
startup time: 0.52398
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Cucumber.GherkinAutoComplete
reloading plugin Cucumber.table_cleaner
reloading plugin Cucumber.table_commons
reloading plugin Cucumber.table_import
reloading plugin EditorConfig.EditorConfig
reloading plugin Emmet.emmet-plugin
reloading plugin File Navigator.File Navigator
reloading plugin Git.git_commands
reloading plugin LESS.less_completions
reloading plugin Origami.origami
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin React IDE.ReactIDE
reloading plugin SublimeLinter-eslint.linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-eslint.sublime-package", line 16, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 5, in <module>
ImportError: No module named 'jsonschema.validators'
reloading plugin SublimeLinter-flow.linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-flow.sublime-package", line 17, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "busy_indicator_view in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.commands
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "commands in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 3, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.goto_commands
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "goto_commands in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 5, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.highlight_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "highlight_view in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 9, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.log_handler
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "log_handler in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "panel_view in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 5, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.status_bar_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "status_bar_view in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.sublime_linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "sublime_linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 12, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "log_handler in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin SublimeLinter.tooltips_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "tooltips_view in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 13, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in /Users/nick/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name util
reloading plugin Babel.Babel
reloading plugin JsPrettier.JsPrettier
reloading plugin Terminal.Terminal
plugins loaded
Emmet: No need to update PyV8
Indexing gherkin phrases done
environment variables loaded using: /bin/bash -l
Package Control: The package 0_package_control_loader is being re-enabled after a Package Control operation was interrupted
ignored packages updated to: ["Vintage"]
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.55-jsonschema
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: No updated packages
```

**Comment by kaste** [comment]
> Package Control: The package 0_package_control_loader is being re-enabled after a Package Control operation was interrupted
ignored packages updated to: ["Vintage"]
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.55-jsonschema

You need to restart again bc `jsonschema` was not ready at atrtup

**Comment by nicklolsen** [comment]
Thank you!
