### ISSUE TITLE
[Version 4](windows) Linter does not work after upgrade

### ISSUE THREAD

**Issue by leerssej** [SublimeLinter/SublimeLinter#1164]
SublimeLinter has fallen off of the tools menu.
Here is the console output:

```DPI scale: 1
startup, version: 3143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Koyot/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Koyot/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Koyot/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.16359
startup time: 0.24159
first paint time: 0.24159
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin Clang Format.clang_format
reloading plugin Git.git_commands
reloading plugin Github Tools.github
reloading plugin Github Tools.github_blame
reloading plugin Github Tools.github_copy_link
reloading plugin Github Tools.github_create_pr
reloading plugin Github Tools.github_file_history
reloading plugin Github Tools.github_issues
reloading plugin Github Tools.github_open
reloading plugin Github Tools.github_plugin_settings
reloading plugin Github Tools.github_pulls
reloading plugin Github Tools.github_repository
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin Pretty JSON.PrettyJson
reloading plugin SendCode.commands
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "commands in C:\Users\Koyot\AppData\Roaming\Sublime Text 3\Installed Packages\SendCode.sublime-package", line 4, in <module>
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "textgetter in C:\Users\Koyot\AppData\Roaming\Sublime Text 3\Installed Packages\SendCode.sublime-package", line 3, in <module>
ImportError: cannot import name SettingManager
reloading plugin SendCode.settings
reloading plugin SendCode.textgetter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "textgetter in C:\Users\Koyot\AppData\Roaming\Sublime Text 3\Installed Packages\SendCode.sublime-package", line 3, in <module>
ImportError: cannot import name SettingManager
reloading plugin SendCode.textsender
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "textsender in C:\Users\Koyot\AppData\Roaming\Sublime Text 3\Installed Packages\SendCode.sublime-package", line 6, in <module>
ImportError: cannot import name SettingManager
reloading plugin SendCode.update_resources
reloading plugin SPARQL Runner.SPARQLRunner
reloading plugin sublime-text-2-buildview.commands
reloading plugin sublime-text-2-buildview.pipe_views
reloading plugin sublime-text-2-buildview.settings
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
reloading plugin SublimeTextGitX.SublimeTextGitX
reloading plugin View In Browser.ViewInBrowserCommand
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin Babel.Babel
reloading plugin Pretty JSON.PrettyJsonListeners
reloading plugin SendCode.choose_prog
reloading plugin SendCode.install_xdotool
reloading plugin SendCode.send_code
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
plugins loaded
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "sublime_linter in C:\Users\Koyot\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 47, in plugin_loaded
  File "sublime_linter in C:\Users\Koyot\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 40, in backup_old_settings
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Koyot\\AppData\\Roaming\\Sublime Text 3\\Packages\\User\\SublimeLinter (old).sublime-settings'
Package Control: Skipping automatic upgrade, last run at 2018-03-07 13:12:23, next run at 2018-03-07 14:12:23 or after```

**Comment by braver** [comment]
- what do you need the tools menu for exactly?
- please upgrade your settings and remove the old backup
- your sendcommand plugins looks like it’s broken
- read this: https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0.txt
- report back after a few restarts of ST and it still doesn’t work

**Comment by leerssej** [comment]
- what do you need the tools menu for exactly?
    - [ ] So I can adjust settings (as seen here):
![image](https://user-images.githubusercontent.com/10225972/37122376-33250694-2215-11e8-9bbb-759bd7209f2a.png) 
    - [ ] In fact, just `user settings` to start... though I think I can burrow down to those through the `preferences > package settings` menu selection.
- please upgrade your settings and remove the old backup
    - [ ] Do you have a default template I can work off of? It seems that my old settings actually disappeared with 4.0.3, and other examples I can find online are from the old version, and don't work in the new one. How should the new settings file be set up? Do you have a template or possibly a standard drop-in setup for windows that can be shared? 
- your sendcommand plugins looks like it’s broken
    - [ ] Is that related to the settings file?
- read this: https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0.txt
    - [ ] I have: several times. Per above, I don't know what I am aiming for as a working settings file.
- report back after a few restarts of ST and it still doesn’t work.
    - I have modified and restarted more than a dozen times already. I have uninstalled and reinstalled twice: being more thorough each time. It seems that is not the way to go: there doesn't seem to be a working set of defaults supplied upon initialization of the package. If drop in versions of the setup files are going to be some time in coming, is there a way I may get the old linter working again? - specifically, how may I `move VERSION to lint/init` (as seen here): https://github.com/SublimeLinter/SublimeLinter/releases/tag/v3.10.10
Thank you again for your help and work on all this!

**Comment by leerssej** [comment]
Here is what my current `SublimeLinter.sublime-settings` file looks like. 
I am still not getting any linting action happening. (Though to be honest, without a menu selection showing me that the package is enabled, I am not really sure I even have it switched on.)
Is there anything I am missing still?
Or is something else just not catching and starting up the linting?

**Comment by leerssej** [comment]
Update:
I uninstalled and reinstalled `SublimeLinter-eslint`.

It is now linting. Now to dig into the `.eslintrc` file and turn it down a tad.

Thank you for all your help and work on this! 
Very happy to get SublimeLinter up and running again 😂:metal:

**Comment by kaste** [comment]
🤘

**Comment by braver** [comment]
Just to answer some of the questions here:

> Do you have a default template I can work off of?

If you open your settings, the defaults are shown on the left along with explanations etc. 

> So I can adjust settings 

That can no longer be done via menus. More info here: https://forum.sublimetext.com/t/sublimelinter-4-beta/34022/37?u=braver

> or even just be able to turn SL on and off.

We're working on bringing this back.
