### ISSUE TITLE
KeyError: 196

### ISSUE THREAD

**Issue by evandrocoan** [SublimeLinter/SublimeLinter#1165]
Just showed up when I started Sublime Text:
```
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 521, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "F:\SublimeText\Data\Packages\SublimeLinter\status_bar_view.py", line 72, in on_selection_modified_async
    draw(**State)
  File "F:\SublimeText\Data\Packages\SublimeLinter\status_bar_view.py", line 84, in draw
    msgs = messages_under_cursor(errors_per_line, current_pos)
  File "F:\SublimeText\Data\Packages\SublimeLinter\status_bar_view.py", line 97, in messages_under_cursor
    error['msg'] for error in errors[line]
KeyError: 196
```

<details>
<p>

```
DPI scale: 1
startup, version: 3157 windows x32 channel: dev
executable: /F/SublimeText/sublime_text.exe
working dir: /D/User/Dropbox/SoftwareVersioning/ComputerScienceGraduation/GraphicsComputing/Trabalho01CG
packages path: /F/SublimeText/Data/Packages
state path: /F/SublimeText/Data/Local
zip path: /F/SublimeText/Packages
zip path: /F/SublimeText/Data/Installed Packages
ignored_packages: ["ApplySyntax", "BracketHighlighter", "BuildView", "C++ Completions", "C++ Qt Completions", "C++ Snippets", "CodeIntel", "ColorHelper", "DictionaryAutoComplete", "FileManager", "Find++", "FuzzyFilePath", "Gist", "Git", "GitGutter", "GotoLastEditEnhanced", "Javatar", "LocalHistory", "MatlabCompletions", "MatlabFilenameAutoComplete", "MySQLSnippets", "ProjectSpecificSyntax", "ScopeAlways", "SublimeLinter-javac", "SyncedSideBar", "Vintage", "WordHighlight"]
top level value must be an array
pre session restore time: 5.53627
loading dictionary Packages/Language - English and Portuguese/EN_PT.dic
startup time: 7.55727
first paint time: 7.56527
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_packages_manager_loader.00-package_control
reloading plugin 0_packages_manager_loader.01-package_setting_context
reloading plugin 0_packages_manager_loader.01-pygments
reloading plugin 0_packages_manager_loader.08-PortalockerFiles
reloading plugin 0_packages_manager_loader.09-ConcurrentLogHandler
reloading plugin 0_packages_manager_loader.10-DebugTools
reloading plugin 0_packages_manager_loader.15-coverage
reloading plugin 0_packages_manager_loader.20-EstimatedTimeLeft
reloading plugin 0_packages_manager_loader.30-ChannelManager
reloading plugin 0_packages_manager_loader.50-backrefs
reloading plugin 0_packages_manager_loader.50-markupsafe
reloading plugin 0_packages_manager_loader.50-PlantUmlConnection
reloading plugin 0_packages_manager_loader.50-pymdownx
reloading plugin 0_packages_manager_loader.50-python-markdown
reloading plugin 0_packages_manager_loader.50-python-pywin32
reloading plugin win32com
reloading plugin win32
reloading plugin win32/lib
reloading plugin win32comext
reloading plugin 0_packages_manager_loader.50-pyyaml
reloading plugin 0_packages_manager_loader.50-regex
reloading plugin 0_packages_manager_loader.51-python-jinja2
reloading plugin 0_packages_manager_loader.55-jsonschema
reloading plugin 0_packages_manager_loader.55-mdpopups
reloading plugin tests
reloading plugin 0_settings_loader.install_package_control_extended
reloading plugin 0_settings_loader.synced_side_bar_watcher
reloading plugin A File Icon.A File Icon
reloading plugin AceJump.ace_jump
reloading plugin ActiveViewJumpBack.active_view_jump_back
reloading plugin AddFolderToProject.AddFolderToProject
reloading plugin AdvancedCSV.csvplugin
reloading plugin Alignment.Alignment
reloading plugin AlignTab.aligner
reloading plugin AlignTab.aligntab
reloading plugin AlignTab.hist
reloading plugin AlignTab.parser
reloading plugin AlignTab.table
reloading plugin AlignTab.wclen
reloading plugin AllAutocomplete.all_views_completions
reloading plugin AltUp.run_multiple_commands
reloading plugin Amxmodx.Amxmodx
reloading plugin AmxxChannel.commands
reloading plugin AmxxChannel.fix_main_menus
reloading plugin AmxxChannel.settings
reloading plugin ANSIescape.ansi
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin AutomaticPackageReloader.package_reloader
reloading plugin AutoRefresh.AutoRefresh
reloading plugin AutoWrap.autowrap
reloading plugin BetterCoffeeScript.CoffeeScript
reloading plugin BetterFindBuffer.find_results
reloading plugin BufferScroll.BufferScroll
reloading plugin CaseConversion.case_conversion
reloading plugin CaseConversion.case_parse
reloading plugin CaseConversion.ToggleTitleCase
reloading plugin ChainOfCommand.chain
reloading plugin ChangeQuotes.change_quotes
reloading plugin ChannelRepositoryTools.ordereddict
reloading plugin ChannelRepositoryTools.tests
reloading plugin ChannelRepositoryTools.upgrade
reloading plugin ClearCursorsCarets.clear_cursors_carets
reloading plugin ClickableURLs.clickable_urls
reloading plugin ClipboardScopeCopy.clipboard_scope_copy
reloading plugin Color Highlighter.color_converter
reloading plugin Color Highlighter.color_highlighter
reloading plugin Color Highlighter.color_hover_listener
reloading plugin Color Highlighter.color_scheme
reloading plugin Color Highlighter.color_scheme_color_highlighter
reloading plugin Color Highlighter.color_searcher
reloading plugin Color Highlighter.color_selection_listener
reloading plugin Color Highlighter.colors
reloading plugin Color Highlighter.content_listener
reloading plugin Color Highlighter.convert_color_command
reloading plugin Color Highlighter.css_colors
reloading plugin Color Highlighter.dummy_event_listener
reloading plugin Color Highlighter.gutter_icons_color_highlighter
reloading plugin Color Highlighter.load_resource
reloading plugin Color Highlighter.main
reloading plugin Color Highlighter.path
reloading plugin Color Highlighter.phantoms_color_highlighter
reloading plugin Color Highlighter.pick_color_command
reloading plugin Color Highlighter.regex_compiler
reloading plugin Color Highlighter.regions
reloading plugin Color Highlighter.set_setting_command
reloading plugin Color Highlighter.settings
reloading plugin Color Highlighter.st_helper
reloading plugin Color Highlighter.topsort
reloading plugin ColorSchemeEditor.ColorSchemeEditor-ST2
reloading plugin ColorSchemeUnit.plugin
reloading plugin ColumnSelect.column_select
reloading plugin ConcurrentLogHandler.setup
reloading plugin ConvertToUTF8.ConvertToUTF8
reloading plugin CopyFilepathWithLineNumbers.CopyFilepathWithLineNumbers
reloading plugin CopyWithLineNumbersReloaded.copy_with_line_numbers
reloading plugin DebugTools.setup
reloading plugin DefaultSyntax.default_syntax
reloading plugin DeleteCurrentFile.DeleteCurrentFile
reloading plugin DistractionFreeWindow.distraction_free_window
reloading plugin DocBlockr.jsdocs
reloading plugin DocBlockr.test_runner
reloading plugin DuplicateSelections.duplicate_selections
reloading plugin EditPreferences.__init__
reloading plugin EditPreferences.commands_base
reloading plugin EditPreferences.edit_package_files
reloading plugin EditPreferences.extract_snippets
reloading plugin EditPreferences.helper_commands
reloading plugin EditPreferences.helpers
reloading plugin EditPreferences.insert_binding_repr
reloading plugin EditPreferences.jsonix
reloading plugin EditPreferences.list_commands
reloading plugin EditPreferences.list_menu_bindings
reloading plugin EditPreferences.list_settings
reloading plugin EditPreferences.list_shortcut_keys
reloading plugin EditPreferences.list_theme_selectors
reloading plugin EditPreferences.package_resources
reloading plugin EditPreferences.quick_panel_cols
reloading plugin EditPreferences.scheduler
reloading plugin Emmet.emmet-plugin
reloading plugin EvaluateInlinePython.inline_python
reloading plugin EvaluatePrinter.EvalPrinter
reloading plugin EvaluatePrinter.KillableCmd
reloading plugin EvaluateShell.evaluate
reloading plugin ExpandRegion.__init__
reloading plugin ExpandRegion.expand_region_handler
reloading plugin ExpandRegion.expand_to_indent
reloading plugin ExpandRegion.expand_to_line
reloading plugin ExpandRegion.expand_to_quotes
reloading plugin ExpandRegion.expand_to_regex_set
reloading plugin ExpandRegion.expand_to_semantic_unit
reloading plugin ExpandRegion.expand_to_subword
reloading plugin ExpandRegion.expand_to_symbols
reloading plugin ExpandRegion.expand_to_word
reloading plugin ExpandRegion.expand_to_word_with_dots
reloading plugin ExpandRegion.expand_to_xml_node
reloading plugin ExpandRegion.ExpandRegion
reloading plugin ExpandRegion.html
reloading plugin ExpandRegion.javascript
reloading plugin ExpandRegion.latex
reloading plugin ExpandRegion.python
reloading plugin ExpandRegion.utils
reloading plugin ExportHtml.ExportBbcode
reloading plugin ExportHtml.ExportHtml
reloading plugin ExportHtml.HtmlAnnotations
reloading plugin ExportHtml.support
reloading plugin ExtendedTabSwitcher.ExtendedSwitcher
reloading plugin ExtractText.clean_save_file_modifications
reloading plugin ExtractText.extract_to_file
reloading plugin FileDiffs.file_diffs
reloading plugin FileHistory.file_history
reloading plugin FileRename.file_rename
reloading plugin FindKeyConflicts.find_key_conflicts
reloading plugin FixProjectSwitchRestartBug.fix_project_switch_restart_bug
reloading plugin FixSelectionAfterIndent.fix_selection_after_indent
reloading plugin ForceRewriteSublimeSettings.force_rewrite_sublime_settings
reloading plugin FuzzyFileNav.fuzzy_file_nav
reloading plugin FuzzyFileNav.multiconf
reloading plugin FuzzyFileNav.notify
reloading plugin Glue.__init__
reloading plugin Glue.Glue
reloading plugin Glue.GlueBrowser
reloading plugin Glue.GlueCmds
reloading plugin Glue.GlueIO
reloading plugin Glue.GlueSidebarOpener
reloading plugin GoogleSpellCheck.google-spell-check
reloading plugin HighlightBuildErrors.HighlightBuildErrors
reloading plugin HighlightWords.HighlightWords
reloading plugin HorizontalScroll.scroll_width
reloading plugin HungryBackspace.hungry_backspace
reloading plugin Incrementor.incrementor
reloading plugin IncrementSelection.IncrementSelection
reloading plugin IndentAndBraces.indent-and-braces
reloading plugin IndentSize.IndentSizeCommand
reloading plugin InsertNums.InsertNums
reloading plugin InvertSelection.invertselection
reloading plugin JumpAlongIndent.file_scanner
reloading plugin JumpAlongIndent.jump_along_indent
reloading plugin JumpAlongIndent.view_helper
reloading plugin KeepPastedTextSelected.keep_pasted_text_selected
reloading plugin LanguageTool.LanguageList
reloading plugin LanguageTool.LanguageTool
reloading plugin LanguageTool.LTServer
reloading plugin LaTeXSmartQuotes.getTeXRoot
reloading plugin LaTeXSmartQuotes.smartquotes
reloading plugin LaTeXTools.01_reload_submodules
reloading plugin LaTeXTools.02_temp_file_cleanup
reloading plugin LaTeXTools.03_reset_phantoms
reloading plugin LaTeXTools.auto_label
reloading plugin LaTeXTools.biblatex_crossref_completions
reloading plugin LaTeXTools.biblatex_field_name_completions
reloading plugin LaTeXTools.biblatex_name_completions
reloading plugin LaTeXTools.biblatex_snippet_completions
reloading plugin LaTeXTools.biblatex_syntax_listener
reloading plugin LaTeXTools.change_environment
reloading plugin LaTeXTools.context_provider
reloading plugin LaTeXTools.create_mousemap
reloading plugin LaTeXTools.delete_temp_files
reloading plugin LaTeXTools.detect_spellcheck
reloading plugin LaTeXTools.getTeXRoot
reloading plugin LaTeXTools.jumpto_anywhere
reloading plugin LaTeXTools.jumpto_tex_file
reloading plugin LaTeXTools.jumpToPDF
reloading plugin LaTeXTools.kpsewhich
reloading plugin LaTeXTools.latex_cite_completions
reloading plugin LaTeXTools.latex_cwl_completions
reloading plugin LaTeXTools.latex_directive_completions
reloading plugin LaTeXTools.latex_env_completions
reloading plugin LaTeXTools.latex_fill_all
reloading plugin LaTeXTools.latex_glossary_completions
reloading plugin LaTeXTools.latex_input_completions
reloading plugin LaTeXTools.latex_installed_packages
reloading plugin LaTeXTools.latex_own_command_completions
reloading plugin LaTeXTools.latex_ref_completions
reloading plugin LaTeXTools.latexCommand
reloading plugin LaTeXTools.latexDocumentationViewer
reloading plugin LaTeXTools.latexEnvCloser
reloading plugin LaTeXTools.latexEnvironment
reloading plugin LaTeXTools.latextools_cache_listener
reloading plugin LaTeXTools.latextools_default_settings
reloading plugin LaTeXTools.latextools_plugin
reloading plugin LaTeXTools.makePDF
reloading plugin LaTeXTools.migrate
reloading plugin LaTeXTools.open_detexify
reloading plugin LaTeXTools.parseTeXlog
reloading plugin LaTeXTools.reveal_folders
reloading plugin LaTeXTools.search_commands
reloading plugin LaTeXTools.smart_paste
reloading plugin LaTeXTools.system_check
reloading plugin LaTeXTools.texcount
reloading plugin LaTeXTools.texMacro
reloading plugin LaTeXTools.texSections
reloading plugin LaTeXTools.texSyntaxListener
reloading plugin LaTeXTools.toc_quickpanel
reloading plugin LaTeXTools.toggle_settings
reloading plugin LaTeXWordCount.WordCount
reloading plugin LESS.less_completions
reloading plugin LineEndingsUnify.LineEndingsUnify
reloading plugin LinesMultisets.choose_view
reloading plugin LinesMultisets.execute_operation
reloading plugin LSP.boot
reloading plugin MarkdownPreview.helper
reloading plugin MarkdownPreview.markdown_settings
reloading plugin MarkdownPreview.markdown_wrapper
reloading plugin MarkdownPreview.MarkdownPreview
reloading plugin MarkdownToBBCode.MarkdownToBBCode
reloading plugin Maven.config_generator
reloading plugin Maven.import
reloading plugin Maven.maven
reloading plugin MaxPane.layouts_doc
reloading plugin MaxPane.max_pane
reloading plugin MoveText.move_text
reloading plugin MultiEditUtils.MultiEditUtils
reloading plugin MultiEditUtils.selection_fields
reloading plugin NumberKing.king
reloading plugin OpenAutoCompletion.open_auto_completion
reloading plugin Origami.origami
reloading plugin OverrideAudit.override_audit
reloading plugin OverrideCommitCompletion.overwrite_commit_completion
reloading plugin OverrideEditSettingsDefaultContents.override_edit_settings_default_contents
reloading plugin OverrideUnpackedPackages.override_unpacked_packages
reloading plugin package_setting_context.__init__
reloading plugin PackageDev._logging
reloading plugin PackageDev.main
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin PackagesManager.1_reloader
reloading plugin PackagesManager.2_bootstrap
reloading plugin PackagesManager.PackagesManager
reloading plugin PanelManager.main
reloading plugin PathTranslator.PathTranslator
reloading plugin PlantUmlConnection.setup
reloading plugin PlantUmlDiagrams.diagram_plugin
reloading plugin PowerCursors.power_cursors
reloading plugin PrettyJSON.PrettyJson
reloading plugin PrettyJSON.PrettyJsonListeners
reloading plugin QuickSettings.quick_settings
reloading plugin RandomEverything.__init__
reloading plugin RandomEverything.random
reloading plugin REG.jumptoregkey
reloading plugin ReIndent.ReIndent
reloading plugin RememberCommandPaletteInput.fixed_command_palette_input_history
reloading plugin REPL.__init__
reloading plugin REPL.completions
reloading plugin REPL.lang_integration
reloading plugin REPL.run_existing_command
reloading plugin REPL.sublimerepl
reloading plugin REPL.sublimerepl_build_system_hack
reloading plugin REPL.text_transfer
reloading plugin ScopeHunter.scope_hunter
reloading plugin ScopeHunter.scope_hunter_notify
reloading plugin ScopeHunter.support
reloading plugin SelectAll.select_all_by_current_scope
reloading plugin SelectAllSpellingErrors.select_all_spelling_errors
reloading plugin SelectUntil.edit
reloading plugin SelectUntil.select-until
reloading plugin SemanticLineWrap.semantic_wrap
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBySideCompare.sbs_compare
reloading plugin SideBySideSettings.sxs_settings
reloading plugin SQLExec.SQLExec
reloading plugin SQLKeywordUppercase.sql_keyword_uppercase
reloading plugin SQLTools.SQLTools
reloading plugin StickySearch.StickySearch
reloading plugin StudioChannel.commands
reloading plugin StudioChannel.settings
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
reloading plugin SublimeTutorial.sublime_tutor
reloading plugin SyncViewScroll.syncscroll
reloading plugin SyntaxManager.syntaxmgr
reloading plugin TabsExtra.support
reloading plugin TabsExtra.tab_menu
reloading plugin TabsExtra.tab_sort_helper
reloading plugin TabsExtra.tabs_extra
reloading plugin TerminalShortcuts.Terminal
reloading plugin TextPastry.text_pastry
reloading plugin TextPastry.text_pastry_addons
reloading plugin TextPastry.text_pastry_clipboard
reloading plugin TextPastry.text_pastry_selection
reloading plugin ToggleWords.ToggleWords
reloading plugin Trimmer.Trimmer
reloading plugin TypeScript.main
reloading plugin UnitTesting.ut
reloading plugin ViewSettingsFreely.view_settings_freely
reloading plugin Whitespace.Whitespace
reloading plugin WordCount.WordCount
reloading plugin WrapPlus.wrap_plus
plugins loaded
PlantUMLDiagrams: ERROR, cannot find Java
PlantUMLDiagrams: ERROR, PlantUML does not appear functional: b"'java' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
[LSP] 18:45:36:0098757 Logging to the file F:\SublimeText\debug2.txt
reloading plugin AmxxChannel.commands
reloading plugin StudioChannel.commands
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 521, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "F:\SublimeText\Data\Packages\SublimeLinter\status_bar_view.py", line 72, in on_selection_modified_async
    draw(**State)
  File "F:\SublimeText\Data\Packages\SublimeLinter\status_bar_view.py", line 84, in draw
    msgs = messages_under_cursor(errors_per_line, current_pos)
  File "F:\SublimeText\Data\Packages\SublimeLinter\status_bar_view.py", line 97, in messages_under_cursor
    error['msg'] for error in errors[line]
KeyError: 196
PackagesManager: No updated packages
reloading plugin SublimeLinter.sublime_linter
reloading settings Packages/SublimeLinter/SublimeLinter.sublime-settings
reloading plugin SublimeLinter.tooltips_view
top level value must be an array
reloading plugin SublimeLinter.status_bar_view
reloading settings Packages/SublimeLinter/SublimeLinter.sublime-settings
```
</p>
</details><br>

**Comment by evandrocoan** [comment]
Just merged the lasted version from master, and noticed you updated the file `status_bar_view`. Perhaps this was fixed?

**Comment by kaste** [comment]
Hope it is fixed. 🤞
