### ISSUE TITLE
SublimeLinter 4 crashes SublimeLinter-csslint: "TypeError: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by jtheletter** [SublimeLinter/SublimeLinter#1166]
Since updating from SL 3 to 4, [csslint](https://github.com/SublimeLinter/SublimeLinter-csslint) is behaving erratically: 

1) In one repo, it highlights warnings, but it ignores my config file (it warns about rules I've said to ignore). Debug ST console for this repo's CSS appears simply to list the lint warnings. 

```
SublimeLinter: SublimeLinter.sublime-package:256: detected syntax: css
INFO:SublimeLinter.sublime_linter:detected syntax: css
SublimeLinter: SublimeLinter.sublime-package:189: scss skipped '/Users/JP/Code/dateclock/dateclock.css', excluded by '*.css'
INFO:SublimeLinter.lint.backend:scss skipped '/Users/JP/Code/dateclock/dateclock.css', excluded by '*.css'
SublimeLinter: #8 SublimeLinter.sublime-package:782: 'csslint' is linting 'dateclock.css'
INFO:SublimeLinter.lint.linter:'csslint' is linting 'dateclock.css'
SublimeLinter: #8 SublimeLinter.sublime-package:1206: csslint: dateclock.css ['/usr/local/bin/csslint', '--format=compact']
INFO:SublimeLinter.lint.linter:csslint: dateclock.css ['/usr/local/bin/csslint', '--format=compact']
SublimeLinter: #8 SublimeLinter.sublime-package:1209: csslint: cwd: /Users/JP/Code/dateclock
INFO:SublimeLinter.lint.linter:csslint: cwd: /Users/JP/Code/dateclock
SublimeLinter: #8 SublimeLinter.sublime-package:809: csslint output:
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 17, col 5, Warning - Unknown property 'unicode-range'. (known-properties)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 17, col 5, Warning - @font-face declaration doesn't follow the fontspring bulletproof syntax. (bulletproof-font-face)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 25, col 5, Warning - Unknown property 'unicode-range'. (known-properties)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 25, col 5, Warning - @font-face declaration doesn't follow the fontspring bulletproof syntax. (bulletproof-font-face)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 33, col 5, Warning - Unknown property 'unicode-range'. (known-properties)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 33, col 5, Warning - @font-face declaration doesn't follow the fontspring bulletproof syntax. (bulletproof-font-face)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 36, col 5, Warning - The box-sizing property isn't supported in IE6 and IE7. (box-sizing)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 109, col 5, Warning - Using height with padding can sometimes make elements larger than you expect. (box-model)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 109, col 5, Warning - Using width with padding can sometimes make elements larger than you expect. (box-model)
INFO:SublimeLinter.lint.linter:csslint output:
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 17, col 5, Warning - Unknown property 'unicode-range'. (known-properties)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 17, col 5, Warning - @font-face declaration doesn't follow the fontspring bulletproof syntax. (bulletproof-font-face)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 25, col 5, Warning - Unknown property 'unicode-range'. (known-properties)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 25, col 5, Warning - @font-face declaration doesn't follow the fontspring bulletproof syntax. (bulletproof-font-face)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 33, col 5, Warning - Unknown property 'unicode-range'. (known-properties)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 33, col 5, Warning - @font-face declaration doesn't follow the fontspring bulletproof syntax. (bulletproof-font-face)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 36, col 5, Warning - The box-sizing property isn't supported in IE6 and IE7. (box-sizing)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 109, col 5, Warning - Using height with padding can sometimes make elements larger than you expect. (box-model)
    /var/folders/lh/7x94_z9x1xbddxjwxkc9g7c00000gn/T/tmpis58ow.css: line 109, col 5, Warning - Using width with padding can sometimes make elements larger than you expect. (box-model)
SublimeLinter: #8 SublimeLinter.sublime-package:850: csslint: No match for line: ''
INFO:SublimeLinter.lint.linter:csslint: No match for line: ''
```

2) In another repo, SL continually opens the Sublime console with every keystroke I make (which is rather annoying), showing this error: 

```
SublimeLinter: #7 csslint jp.css ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 813, in lint
  File "lint.linter in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 847, in find_errors
  File "linter in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-csslint.sublime-package", line 57, in split_match
TypeError: 'NoneType' object is not iterable
```

Its debug console appears to list the lint warnings for a split second (I had to record the screen to get an image)…

![pic 2018-03-07 at 18 08 02](https://user-images.githubusercontent.com/4712441/37129298-3478122a-2233-11e8-829b-e49d66123dbd.png)

…it then clears the console and shows the above "NoneType" error. 

I've confirmed all my software is up to date (versions below), and I've rebooted and relaunched Sublime. I've confirmed my HTML and JS linters don't have this problem. 

My `~/.csslintrc` config file is: 

```
{
    "ignore": [
        "box-model",
        "box-sizing",
        "bulletproof-font-face"
    ],
    "ignore_match": [
        "Unknown property 'unicode-range'"
    ]
}
```

SublimeLinter settings (/Users/JP/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings): 
```
{
    "delay": 0,

    "linters": {
        "scss": {
            "excludes": [
                "*.css"
            ]
        }
    }
}
```

SL debug mode shows this in the console on launch: 

```
startup, version: 3143 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/JP/Library/Application Support/Sublime Text 3/Packages
state path: /Users/JP/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 1.84883
startup time: 1.96778
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin AlignTab.aligner
reloading plugin AlignTab.aligntab
reloading plugin AlignTab.hist
reloading plugin AlignTab.parser
reloading plugin AlignTab.table
reloading plugin AlignTab.wclen
reloading plugin Case Conversion.case_conversion
reloading plugin Case Conversion.case_parse
reloading plugin Colorsublime.colorsublime-plugin
reloading plugin GitHub Flavored Markdown Preview.GHMarkdownPreview
reloading plugin LESS.less_completions
reloading plugin LiveStyle.livestyle
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-contrib-htmlhint.linter
reloading plugin SublimeLinter-contrib-scss-lint.linter
reloading plugin SublimeLinter-csslint.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-jshint.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-php.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
reloading plugin Babel.Babel
reloading plugin LiveStyle.livestyle-plugin
reloading plugin Speak Selected Text.SpeakSelectedText
reloading plugin sublime-cross.cross
sublime-cross init
plugins loaded
SublimeLinter: SublimeLinter.sublime-package:71: Logging installed; log level INFO
SublimeLinter: SublimeLinter.sublime-package:62: debug mode: on
INFO:SublimeLinter.sublime_linter:debug mode: on
SublimeLinter: SublimeLinter.sublime-package:63: version: 4.0.5
INFO:SublimeLinter.sublime_linter:version: 4.0.5
LiveStyle: Start app
LiveStyle: Client connection error: [Errno 61] Connection refused
LiveStyle: Create own server on port 54000
LiveStyle: Starting LiveStyle server on port 54000
LiveStyle: Client connected
environment variables loaded using: /bin/bash -l
Package Control: Skipping automatic upgrade, last run at 2018-03-07 17:26:40, next run at 2018-03-07 18:26:40 or after
```

Software versions: 
- SublimeLinter 4.0.5
- SublimeLinter-csslint 1.1.6
- csslint 1.0.4
- Sublime Text 3.0, build 3143
- macOS 10.13.3

**Comment by hihahihahoho** [comment]
me three, just crash now
 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\tungn\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in C:\Users\tungn\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 813, in lint
  File "lint.linter in C:\Users\tungn\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 847, in find_errors
  File "linter in C:\Users\tungn\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-csslint.sublime-package", line 57, in split_match
TypeError: 'NoneType' object is not iterable

**Comment by kaste** [comment]
Yeah, sorry about that, I fixed this yesterday ❤️ 

@braver will surely do a release very soon.
