### ISSUE TITLE
Multiple import/loading errors when starting Sublime

### ISSUE THREAD

**Issue by kaiyoma** [SublimeLinter/SublimeLinter#1170]
Another day, another SublimeLinter error. :-/

Upon starting Sublime this morning, I received this error message:

![sublime-linter-error](https://user-images.githubusercontent.com/10719780/37169242-3719bc5c-22bc-11e8-9758-847f1cb5182b.png)

Here's what the console has:

```
DPI scale: 1.25
startup, version: 3143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text/sublime_text.exe
working dir: /C/Program Files/Sublime Text
packages path: /C/Users/.../AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/.../AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text/Packages
zip path: /C/Users/.../AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.427797
startup time: 0.547798
first paint time: 0.550798
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin LESS.less_completions
reloading plugin LineEndings.LineEndings
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pyflakes.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
reloading plugin TrailingSpaces.trailing_spaces
reloading plugin Babel.Babel
plugins loaded
Package Control: Installing 2 upgrades
ignored packages updated to: ["SublimeLinter", "SublimeLinter-eslint", "Vintage"]
unloading plugin SublimeLinter-eslint.linter
unloading plugin SublimeLinter.__init__
unloading plugin SublimeLinter.busy_indicator_view
unloading plugin SublimeLinter.commands
unloading plugin SublimeLinter.goto_commands
unloading plugin SublimeLinter.highlight_view
unloading plugin SublimeLinter.log_handler
unloading plugin SublimeLinter.message_view
unloading plugin SublimeLinter.panel_view
unloading plugin SublimeLinter.status_bar_view
unloading plugin SublimeLinter.sublime_linter
reloading settings Packages/SublimeLinter/SublimeLinter.sublime-settings
unloading plugin SublimeLinter.tooltips_view
generating syntax summary
error: Error loading syntax file "Packages/SublimeLinter/panel/panel.sublime-syntax": Unable to read Packages/SublimeLinter/panel/panel.sublime-syntax
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Upgraded SublimeLinter to 4.0.6
Package Control: Upgraded SublimeLinter-eslint to 4.0.2
ignored packages updated to: ["SublimeLinter-eslint", "Vintage"]
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin SublimeLinter.__init__
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in C:\Users\...\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\sublime_plugin.py", line 157, in reload_plugin
    m.plugin_loaded()
  File "sublime_linter in C:\Users\...\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 61, in plugin_loaded
  File "lint.settings in C:\Users\...\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 21, in load
  File "lint.settings in C:\Users\...\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 75, in on_update
  File "lint.style in C:\Users\...\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 23, in read_gutter_theme
  File "./python3.3/ntpath.py", line 249, in basename
  File "./python3.3/ntpath.py", line 220, in split
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()
reloading settings Packages/SublimeLinter/SublimeLinter.sublime-settings
reloading plugin SublimeLinter.tooltips_view
generating syntax summary
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin SublimeLinter-eslint.linter
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

As with all these SublimeLinter 4.0 errors I've been seeing lately, restarting Sublime fixes the issue. I have to do this at least once a day now.

**Comment by braver** [comment]
Yeah, we’re working the reloading thing, it’s not dealing well with upgrades. But we also have to bring you the bugfixes.

**Comment by taylorthurlow** [comment]
I see that you're aware of the issue so I'm not sure if any extra info is beneficial, but I'm also experiencing the issue on macOS. Glad to see it's being worked on.

**Comment by braver** [comment]
Ok, this seems very similar to #1167. We don't call the reloader anymore and it's giving issues here. Perhaps the 4.0.5 to 4.0.6 upgrade was especially rough, but that should be over now. 

We're tracking the panel-syntax thing elsewhere, but it seems an especially tricky thing about the way ST and package control deal with this. 

All of this should be gone after a restart. We're already getting less and less bug reports, so with a few days we won't be doing updates every day anymore and it'll settle down for everyone.
