### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'folders'

### ISSUE THREAD

**Issue by sowizz** [SublimeLinter/SublimeLinter#1187]
Hi, after running Sublime today I got the following error:

```
SublimeLinter: #14310 eslint_d SwBehaviorProgram.js ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/amarkiewicz/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/amarkiewicz/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 797, in lint
  File "lint.linter in /Users/amarkiewicz/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 1147, in run
  File "linter in /Users/amarkiewicz/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-contrib-eslint_d.sublime-package", line 73, in communicate
AttributeError: 'NoneType' object has no attribute 'folders'
```

What is really strange it only happens when linting some of the project files, not all of them.

**Comment by kaste** [comment]
That's a bug in `eslint_d` which is not in our org.

**Comment by kaste** [comment]
You can probably just use `eslint` here and set the executable via the linter settings.

```
linters: {
	eslint: {
		executable: 'path/to/eslint_d'
	}
}
```
