### ISSUE TITLE
ERROR: Linter crashed. TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by joshlangner** [SublimeLinter/SublimeLinter#1207]
GEtting this with Version 4.1
Sublime 3, running Windows 10.

traceback:
SublimeLinter.sublime-package", line 97, in execute_lint_task
SublimeLinter.sublime-package", line 754, in lint
SublimeLinter.sublime-package", line 475, in get_cmd

I'd also encourage folks to hop over and vote this issue up: https://github.com/wbond/package_control/issues/1349 (Add support for pinning / installing specific package versions, for cases where the latest is failing)

**Comment by chuckrincon** [comment]
Same +1

**Comment by kaste** [comment]
Full debug log please.

**Comment by kaste** [comment]
Actually, I only need the linter plugins that cause this

**Comment by pszucs** [comment]
```
SublimeLinter: #1 php payments.php ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /home/peters/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /home/peters/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 754, in lint
  File "lint.linter in /home/peters/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 475, in get_cmd
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by willrowe** [comment]
I'm getting this error for SublimeLinter-php.

**Comment by Kotzilla** [comment]
same here, i got this in debug log
it's happen when lint ***.php** file for me but not in _*.js, *.css_

`SublimeLinter: #88 __init__.py:1273: ERROR: Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /###/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /###/SublimeLinter.sublime-package", line 754, in lint
  File "lint.linter in /###/SublimeLinter.sublime-package", line 475, in get_cmd
TypeError: argument of type 'NoneType' is not iterable`

**Comment by joshlangner** [comment]
Folks on this thread, I'd also encourage to pop over and vote this issue up: https://github.com/wbond/package_control/issues/1349

**Comment by MusikAnimal** [comment]
I'm seeing this error only for SublimeLinter-php and SublimeLinter-eslint. SublimeLinter-contrib-scss-lint seems to be unaffected.

**Comment by intrepidws** [comment]
I'm getting this same error and I only have SublimeLinter-php.

**Comment by kaste** [comment]
Okay, proposed fix in #1209 . We need testers to approve before we ship.

**Comment by teolopez** [comment]
im using jshint and php:

`SublimeLinter: #5 php page-home-update.php ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/teodoro.lopez/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/teodoro.lopez/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 754, in lint
  File "lint.linter in /Users/teodoro.lopez/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 475, in get_cmd
TypeError: argument of type 'NoneType' is not iterable`

**Comment by joshlangner** [comment]
@kaste who are these testers? Let's hunt them down... and buy them 🍻 😄

**Comment by braver** [comment]
I beat all of you just so I can get myself some beer 😎 4.1.1 is out there with a fix.

**Comment by braver** [comment]
@intrepidws For future reference: it involves manually git cloning this repo into Packages (remove the one installed via package control first), and then merging the branch of the PR into that clone.

**Comment by MusikAnimal** [comment]
I use Package Control. How long do updates typically take to show up there? Not that there's an urgent rush :) I've tried uninstalling SublimeLinter and reinstalling, still 4.1.0, and no updates available when I use "Upgrade Package". Many thanks for the quick fix.

**Comment by intrepidws** [comment]
Thanks for the quick fix everyone!

**Comment by frankpaul142** [comment]
Hello, when is going to be this fix on package control ? thanks for the quick fix.

**Comment by braver** [comment]
package control usually takes up to an hour maximum.

**Comment by pbergner** [comment]
I'm still seeing this and no upgrades available.

**Comment by Jarvvski** [comment]
Still an issue for me in 4.1.1

**Comment by kaste** [comment]
Which linters are you using? We have a relatively good fix in master ready for release.

**Comment by pbergner** [comment]
jshint

**Comment by kaste** [comment]
jshint doesn't use the API discussed here.

**Comment by gretel** [comment]
just reinstalled latest version, getting crashed on `yaml` files.

```
SublimeLinter: #4 pyyaml .gitlab-ci.yml ERROR:
==============================================

Linter crashed.

Traceback (most recent call last):
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 87, in execute_lint_task
    errors = linter.lint(code, view_has_changed, settings) or []
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 747, in lint
    output = self.run(None, code)     # type: str
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1054, in run
    return self.communicate(cmd, code)
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1064, in communicate
    cmd, ctx, at_value=self.filename, auto_append=code is None)
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1085, in finalize_cmd
    if '@' in cmd:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by kaste** [comment]
`pyyaml`plugin is not compatible with SL4 and has been deprecated.

**Comment by gretel** [comment]
i was mixing up `SL3` and `ST3`. you are right on me using `SublimeLinter 3` - but i have been using the exact contrib package you are referring to.
