### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by juliuswz** [SublimeLinter/SublimeLinter#1210]
SublimeLinter: 2 php Auth.php ERROR:

 ```
Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\Julius\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in C:\Users\Julius\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 754, in lint
  File "lint.linter in C:\Users\Julius\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 475, in get_cmd
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by braver** [comment]
What version of SublimeLinter is this?

**Comment by daguej** [comment]
Also seeing this after an update.  package-metadata.json in the installed package says v4.1.1.

**Comment by braver** [comment]
Does a restart of Sublime Text help?

**Comment by kaste** [comment]
Restart Sublime.

**Comment by daguej** [comment]
Seems better, thanks.

**Comment by juliuswz** [comment]
I tried: restart sublime text, reinstall packages (SublimeLinter, sublimelinter-php removing settings).
SublimeLinter 4.1.1

**Comment by juliuswz** [comment]
I also reinstalled the sublime text and now it is working properly, thanks.

**Comment by bendiy** [comment]
Looks like a fix a was just pushed:
https://github.com/SublimeLinter/SublimeLinter/releases/tag/4.1.1
