### ISSUE TITLE
Linter crashed

### ISSUE THREAD

**Issue by darrencoen** [SublimeLinter/SublimeLinter#1211]
Getting this in the sublime console, Browsing the documentation here to see how I can provide more information and will add to the ticket.

```
SublimeLinter: #28 php home.php ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\Darren\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in C:\Users\Darren\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 754, in lint
  File "lint.linter in C:\Users\Darren\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 475, in get_cmd
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by bendiy** [comment]
Same issue. SublimeLinter just updated on restart and now this on every file I open.

```
SublimeLinter: #1 jshint some-file.js ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\me\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in C:\Users\me\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 754, in lint
  File "lint.linter in C:\Users\me\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 475, in get_cmd
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by juliuswz** [comment]
Try this #1210.

**Comment by bendiy** [comment]
Looks like a fix a was just pushed:
https://github.com/SublimeLinter/SublimeLinter/releases/tag/4.1.1

**Comment by darrencoen** [comment]
This seems resolved now. I performed "Package Control: Upgrade/Overwrite All Packages" after comments saying a fix was pushed.

Thanks everyone!
