### ISSUE TITLE
[php/jshint] Crash report

### ISSUE THREAD

**Issue by jagroop** [SublimeLinter/SublimeLinter#1214]
```bash
SublimeLinter: #82 php User.php ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /home/jagroop/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /home/jagroop/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 794, in lint
  File "lint.linter in /home/jagroop/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 511, in get_cmd
TypeError: argument of type 'NoneType' is not iterable
```

sublime text : 3143
Sublime linter : v4.1.1
OS : Ubuntu 16.04

**Comment by eparisio** [comment]
Same error but on jshint

**Comment by braver** [comment]
Full debug log please, I need to know what version of SL you're on and if you restarted recently.

**Comment by mbrodala** [comment]
@braver Good call. Here I was just enabling debug logging, restarted Sublime and the issue was gone. That that seems to have fixed it for me.

**Comment by kaste** [comment]
On line 511 we're already in the `build_cmd` method. So, basically you need to restart bc PackageControl/Sublime could not reload/activate the updated SublimeLinter

**Comment by braver** [comment]
Ok, we're not investigating this further until we know for sure a restart *doesn't* fix it.

**Comment by jagroop** [comment]
@braver restarting Sublime Text doesn't fix the problem

**Comment by kaste** [comment]
@jagroop Post full console log beginning with a restart of Sublime.

**Comment by jshado1** [comment]
Since v4.0.1 installed itself, I get this error after **every** system login (very annoying). The error does not re-appear after restarting Sublime itself.

The full console is not open when Sublime starts up after a system login, and when I open it after the error appears, there is no output above the error.

I'm working in a Javascript project, so the file referenced in the error's first line is different, but the rest of the error message in OP is identical.

OSX 10.11.6
SublimeText 3 build 3143

Relevant console output from after restarting Sublime (no error):

```
startup, version: 3143 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/[…]/Library/Application Support/Sublime Text 3/Packages
state path: /Users/[…]/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/[…]/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.195065
using gpu buffer for window
using gpu buffer for window
using gpu buffer for window
startup time: 0.295392

// …

reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
```

**Comment by braver** [comment]
> Since SublimeLinter v4.0.1 installed itself

And what version is SL at right now for you?

**Comment by jshado1** [comment]
It just updated to 4.10.0 this morning.

**Comment by braver** [comment]
Sorry, but `4.10.0` isn't a thing. If that's a typo and you mean `4.1.0`, you're one version behind.

**Comment by undermuz** [comment]
I have the same error, pops up at any change in the file, followed by another similar one, pop up at the same time:

OS: Window 10 v1709 build 16299.309
IDE: SublimeText v3.0 build 3143
SublimeLinter: v4.1.1

```
SublimeLinter: ERROR: Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 794, in lint
  File "lint.linter in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 511, in get_cmd
TypeError: argument of type 'NoneType' is not iterable
SublimeLinter: ERROR: Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 794, in lint
  File "lint.linter in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 511, in get_cmd
TypeError: argument of type 'NoneType' is not iterable
```

And more:

```
SublimeLinter: #1102 eslint backend.php ERROR:

 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint
```

**Comment by mbrodala** [comment]
A few hints for my system where everything works fine:

```
OS Name:	Microsoft Windows 10 Pro
Version:	10.0.16299 Build 16299
Sublime: Dev Channel, Build 3157
SublimeLinter: v4.1.1
```

**Comment by ptkdev** [comment]
+1

**Comment by jshado1** [comment]
@braver, yes sorry. 4.1.0, which auto-updated this morning and I did not get the error 🎉

**Comment by braver** [comment]
Ok, looks like the patch needs some time to reach everyone, but when it does it seems to solve the problem. 

@undermuz The first thing seems like the same problem, but I need more info. What linter are you running? Can you share more debug logging (e.g. turn on debug, restart ST, then try to lint a file, and share the entire thing).
The second thing is just eslint bothering you about config files. More info here: https://github.com/SublimeLinter/SublimeLinter-eslint#ive-got-sublimelinter-eslint-error-eslint-couldnt-find-a-configuration-file-when-i-am-editing-a-javascript-file

**Comment by undermuz** [comment]
@braver 
I do not understand what kind of debug mode you mean. Please give instructions how to turn it on.
For the time being I am attaching the console output from the moment of start to the occurrence of errors:

```
DPI scale: 1
startup, version: 3143 windows x64 channel: stable
executable: /E/IDE/Sublime Text 3/sublime_text.exe
working dir: /E/IDE/Sublime Text 3
packages path: /C/Users/User/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/User/AppData/Roaming/Sublime Text 3/Local
zip path: /E/IDE/Sublime Text 3/Packages
zip path: /C/Users/User/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["GitGutter", "Markdown", "Smarty", "Vintage"]
Errors parsing theme:
icon_file_type is missing layer0.opacity, setting to 1.0 for backwards compatibility
pre session restore time: 0.868166
warning: mnemonic n not found in menu caption Документация
startup time: 0.914166
first paint time: 0.920166
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-numpy
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.50-regex
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.A File Icon
reloading plugin Advanced CSV.csvplugin
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin Alignment.Alignment
reloading plugin AlignTab.aligner
reloading plugin AlignTab.aligntab
reloading plugin AlignTab.hist
reloading plugin AlignTab.parser
reloading plugin AlignTab.table
reloading plugin AlignTab.utils
reloading plugin AlignTab.wclen
reloading plugin All Autocomplete.all_views_completions
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
>>> sublime.log_commands(True)
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin BufferScroll.BufferScroll
reloading plugin Chain of Command.chain
reloading plugin Clickable URLs.clickable_urls
reloading plugin Console Wrap.console_wrap
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin FileHeader.FileHeader
reloading plugin HexViewer.hex_checksum
Hex Viewer: md2 hash is not available!
reloading plugin HexViewer.hex_common
reloading plugin HexViewer.hex_editor
reloading plugin HexViewer.hex_finder
reloading plugin HexViewer.hex_highlighter
reloading plugin HexViewer.hex_inspector
reloading plugin HexViewer.hex_notify
reloading plugin HexViewer.hex_viewer
reloading plugin HexViewer.hex_writer
reloading plugin HexViewer.sum_hashes
reloading plugin HexViewer.support
reloading plugin HexViewer.tiger
reloading plugin HexViewer.whirlpool
reloading plugin LESS.less_completions
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin ParentalControl.parental_control
reloading plugin PHP Companion.PHP Companion
reloading plugin PHPIntel.intel
reloading plugin PHPIntel.phpintel
reloading plugin PHPIntel.phpparser
reloading plugin RegReplace.rr_edit
reloading plugin RegReplace.rr_notify
reloading plugin RegReplace.rr_plugin
reloading plugin RegReplace.rr_replacer
reloading plugin RegReplace.rr_sequencer
reloading plugin RegReplace.rr_upgrade
reloading plugin RegReplace.support
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Simple Import.ReloadPlugin
reloading plugin Simple Import.SimpleImportCommand
reloading plugin SublimeLinter-csslint.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-php.linter
reloading plugin SublimeLinter-phplint.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
reloading plugin SummitLinter.linter
reloading plugin Tag.Edit
reloading plugin Tag.Tag
reloading plugin Tag.tag_classes
reloading plugin Tag.tag_close_tag
reloading plugin Tag.tag_close_tag_on_slash
reloading plugin Tag.tag_indent
reloading plugin Tag.tag_insert_as_tag
reloading plugin Tag.tag_lint
reloading plugin Tag.tag_remove
reloading plugin Tag.tag_remove_attributes
reloading plugin Toggle Words.ToggleWords
reloading plugin Tpl.tpl
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Autoprefixer.node_bridge
reloading plugin Babel.Babel
reloading plugin JavaScript Completions._generated_2018_02_11_at_20_21_24
reloading plugin JavaScript Completions.reloader
plugins loaded
[Console Wrap] ****************************** loaded ******************************
Emmet: No need to update PyV8
Exception in thread DownloadCanIuseJsonData:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\_generated_2018_02_11_at_20_21_24.py", line 786, in donwload_can_i_use_json_data
    os.rename(path_to_test_can_i_use_data, path_to_can_i_use_data)
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'C:\\Users\\User\\AppData\\Roaming\\Sublime Text 3\\Packages\\JavaScript Completions\\helper\\can_i_use\\can_i_use_data.json'

Package Control: No updated packages
SublimeLinter: WARNING: phplint cannot locate 'phpl'
SublimeLinter: WARNING: htmltidy cannot locate 'tidy'
SublimeLinter: WARNING: htmltidy cannot locate 'tidy'
SublimeLinter: WARNING: phplint cannot locate 'phpl'
SublimeLinter: ERROR: 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint


SublimeLinter: ERROR: 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint


SublimeLinter: WARNING: htmltidy cannot locate 'tidy'
SublimeLinter: WARNING: phplint cannot locate 'phpl'
SublimeLinter: WARNING: phplint cannot locate 'phpl'
SublimeLinter: WARNING: htmltidy cannot locate 'tidy'
SublimeLinter: ERROR: 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint


SublimeLinter: ERROR: 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint


SublimeLinter: WARNING: phplint cannot locate 'phpl'
SublimeLinter: WARNING: htmltidy cannot locate 'tidy'
SublimeLinter: ERROR: 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint


SublimeLinter: ERROR: 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint


SublimeLinter: WARNING: phplint cannot locate 'phpl'
SublimeLinter: WARNING: htmltidy cannot locate 'tidy'
SublimeLinter: ERROR: 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint


SublimeLinter: ERROR: 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint


SublimeLinter: WARNING: phplint cannot locate 'phpl'
SublimeLinter: WARNING: htmltidy cannot locate 'tidy'
SublimeLinter: ERROR: 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint


SublimeLinter: ERROR: 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint
```

**Comment by braver** [comment]
@undermuz this one: https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/troubleshooting.rst#debug-mode

This caught my eye:

```
SublimeLinter: WARNING: phplint cannot locate 'phpl'
SublimeLinter: WARNING: htmltidy cannot locate 'tidy'
SublimeLinter: WARNING: htmltidy cannot locate 'tidy'
SublimeLinter: WARNING: phplint cannot locate 'phpl'
```

Do you have those executables installed and available in your PATH?

**Comment by undermuz** [comment]
@braver 
>Do you have those executables installed and available in your PATH?

hmm. Not installed

>Can you share more debug logging

Here is part of the console output with the debug mode turned on, and apparently I did not get an error from the comment: https://github.com/SublimeLinter/SublimeLinter/issues/1214#issuecomment-373683934

```
SublimeLinter: SublimeLinter.sublime-package:292: detected syntax: html
SublimeLinter: #1 SublimeLinter.sublime-package:747: 'htmltidy' is linting 'backend.php'
SublimeLinter: #1 SublimeLinter.sublime-package:103: PATH:
    C:\ProgramData\Oracle\Java\javapath
    C:\Python33\
    C:\Program Files (x86)\Intel\iCLS Client\
    C:\Program Files\Intel\iCLS Client\
    C:\Windows\system32
    C:\Windows
    C:\Windows\System32\Wbem
    C:\Windows\System32\WindowsPowerShell\v1.0\
    C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
    E:\servers\xampp\php
    E:\Program Files\Git\cmd
    C:\ProgramData\ComposerSetup\bin
    E:\Program Files\nwjs-v0.19.5-win-x64
    E:\Android\sdk\tools
    C:\WINDOWS\system32
    C:\WINDOWS
    C:\WINDOWS\System32\Wbem
    C:\WINDOWS\System32\WindowsPowerShell\v1.0\
    C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\
    C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
    C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
    C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
    C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
    C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
    E:\Program Files\nodejs\
    E:\Program Files (x86)\QuickTime\QTSystem\
    C:\Users\User\AppData\Local\Microsoft\WindowsApps
    C:\Users\User\AppData\Roaming\Composer\vendor\bin
    C:\Users\User\AppData\Local\atom\bin
    C:\Users\User\AppData\Local\Microsoft\WindowsApps
    C:\Users\User\AppData\Roaming\npm
    E:\Android\platform-tools

    E:\IDE\Microsoft VS Code\bin
SublimeLinter: #2 SublimeLinter.sublime-package:747: 'phplint' is linting 'backend.php'
SublimeLinter: #3 SublimeLinter.sublime-package:747: 'eslint' is linting 'backend.php'
SublimeLinter: #4 SublimeLinter.sublime-package:747: 'eslint' is linting 'backend.php'
SublimeLinter: #5 SublimeLinter.sublime-package:747: 'php' is linting 'backend.php'
SublimeLinter: #2 SublimeLinter.sublime-package:515: WARNING: phplint cannot locate 'phpl'
SublimeLinter: #1 SublimeLinter.sublime-package:515: WARNING: htmltidy cannot locate 'tidy'
SublimeLinter: #5 SublimeLinter.sublime-package:1045: php: backend.php ['E:\\servers\\xampp\\php\\php.exe', '-l', '-n', '-d', 'display_errors=On', '-d', 'log_errors=Off']
SublimeLinter: #5 SublimeLinter.sublime-package:1048: php: cwd: E:\Develops\Bolt-System\new-don-telefon
SublimeLinter: #4 SublimeLinter.sublime-package:1045: eslint: backend.php ['C:\\Users\\User\\AppData\\Roaming\\npm\\eslint.cmd', '--format', 'json', '--stdin', '--stdin-filename', 'E:\\Develops\\Bolt-System\\new-don-telefon\\yii2\\views\\layouts\\backend.php']
SublimeLinter: #3 SublimeLinter.sublime-package:1045: eslint: backend.php ['C:\\Users\\User\\AppData\\Roaming\\npm\\eslint.cmd', '--format', 'json', '--stdin', '--stdin-filename', 'E:\\Develops\\Bolt-System\\new-don-telefon\\yii2\\views\\layouts\\backend.php']
SublimeLinter: #4 SublimeLinter.sublime-package:1048: eslint: cwd: E:\Develops\Bolt-System\new-don-telefon
SublimeLinter: #3 SublimeLinter.sublime-package:1048: eslint: cwd: E:\Develops\Bolt-System\new-don-telefon
SublimeLinter: #3 SublimeLinter.sublime-package:774: eslint output:

    Oops! Something went wrong! :(

    ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

        eslint --init

    ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

    If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint
SublimeLinter: #3 SublimeLinter-eslint.sublime-package:44: ERROR: 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint


SublimeLinter: #5 SublimeLinter.sublime-package:774: php output:
    No syntax errors detected in -
SublimeLinter: #5 SublimeLinter.sublime-package:815: php: No match for line: 'No syntax errors detected in -'
SublimeLinter: #4 SublimeLinter.sublime-package:774: eslint output:

    Oops! Something went wrong! :(

    ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

        eslint --init

    ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

    If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint
SublimeLinter: #4 SublimeLinter-eslint.sublime-package:44: ERROR: 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint


SublimeLinter: #6 SublimeLinter.sublime-package:747: 'htmltidy' is linting 'backend.php'
SublimeLinter: #7 SublimeLinter.sublime-package:747: 'phplint' is linting 'backend.php'
SublimeLinter: #8 SublimeLinter.sublime-package:747: 'eslint' is linting 'backend.php'
SublimeLinter: #9 SublimeLinter.sublime-package:747: 'eslint' is linting 'backend.php'
SublimeLinter: #10 SublimeLinter.sublime-package:747: 'php' is linting 'backend.php'
SublimeLinter: #7 SublimeLinter.sublime-package:515: WARNING: phplint cannot locate 'phpl'
SublimeLinter: #8 SublimeLinter.sublime-package:1045: eslint: backend.php ['C:\\Users\\User\\AppData\\Roaming\\npm\\eslint.cmd', '--format', 'json', '--stdin', '--stdin-filename', 'E:\\Develops\\Bolt-System\\new-don-telefon\\yii2\\views\\layouts\\backend.php']
SublimeLinter: #10 SublimeLinter.sublime-package:1045: php: backend.php ['E:\\servers\\xampp\\php\\php.exe', '-l', '-n', '-d', 'display_errors=On', '-d', 'log_errors=Off']
SublimeLinter: #8 SublimeLinter.sublime-package:1048: eslint: cwd: E:\Develops\Bolt-System\new-don-telefon
SublimeLinter: #9 SublimeLinter.sublime-package:1045: eslint: backend.php ['C:\\Users\\User\\AppData\\Roaming\\npm\\eslint.cmd', '--format', 'json', '--stdin', '--stdin-filename', 'E:\\Develops\\Bolt-System\\new-don-telefon\\yii2\\views\\layouts\\backend.php']
SublimeLinter: #10 SublimeLinter.sublime-package:1048: php: cwd: E:\Develops\Bolt-System\new-don-telefon
SublimeLinter: #9 SublimeLinter.sublime-package:1048: eslint: cwd: E:\Develops\Bolt-System\new-don-telefon
SublimeLinter: #6 SublimeLinter.sublime-package:515: WARNING: htmltidy cannot locate 'tidy'
SublimeLinter: #10 SublimeLinter.sublime-package:774: php output:
    No syntax errors detected in -
SublimeLinter: #8 SublimeLinter.sublime-package:774: eslint output:

    Oops! Something went wrong! :(

    ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

        eslint --init

    ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

    If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint
SublimeLinter: #10 SublimeLinter.sublime-package:815: php: No match for line: 'No syntax errors detected in -'
SublimeLinter: #8 SublimeLinter-eslint.sublime-package:44: ERROR: 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in E:\Develops\Bolt-System\new-don-telefon\yii2\views\layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint
```

**Comment by braver** [comment]
Ok, that all looks pretty good then. You *do* need to do something about that eslint config thing. Here's a tip: https://github.com/SublimeLinter/SublimeLinter-eslint#ive-got-sublimelinter-eslint-error-eslint-couldnt-find-a-configuration-file-when-i-am-editing-a-javascript-file

**Comment by kaste** [comment]
The initial issue has been resolved, so I'm closing.
