### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by carrola7** [SublimeLinter/SublimeLinter#1215]
```bash
SublimeLinter: #2 htmltidy index.html ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /home/adrian/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /home/adrian/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 759, in lint
  File "lint.linter in /home/adrian/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 464, in get_cmd
  File "linter in /home/adrian/.config/sublime-text-3/Installed Packages/SublimeLinter-html-tidy.sublime-package", line 31, in cmd
TypeError: which() missing 1 required positional argument: 'cmd'
```

Settings:
https://gist.github.com/carrola7/9c56506da21b69a50732557cba6776ca

**Comment by goodrank** [comment]
Сonfirm! Pls fix this.

**Comment by neurospochtsfroind** [comment]
Confirmed on macOs 10.12.6, SublimeText DevChanell, Build 3157. Maybe of missing jscs:

SublimeLinter: WARNING: jscs cannot locate 'jscs' 
SublimeLinter: ERROR: Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/arne/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/arne/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 794, in lint
  File "lint.linter in /Users/arne/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 511, in get_cmd
TypeError: argument of type 'NoneType' is not iterable
indexing: crawldb not available, indexing abandoned

**Comment by kaste** [comment]
Fix is https://github.com/SublimeLinter/SublimeLinter-html-tidy/pull/50

**Comment by kaste** [comment]
Please test and approve.

**Comment by kaste** [comment]
@neurospochtsfroind Restart Sublime

**Comment by kaste** [comment]
Merged and released a new html-tidy.

**Comment by neurospochtsfroind** [comment]
@kaste 

Hi!

First: Thank you for your support.

Restarted SublimeText, no traceback, but still not working, here is a (shortened) startup-dump:

```
startup, version: 3157 osx x64 channel: dev
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/xxx/Library/Application Support/Sublime Text 3/Packages
state path: /Users/xxx/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/xxx/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["ActionScript", (** snip **) ,"Vintage"]
pre session restore time: 6.55002
using gpu buffer for window
startup time: 7.39627
(** snip **)
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.10-shellenv
reloading plugin 0_package_control_loader.50-dateutil
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin All Autocomplete.all_views_completions
(** snip **)
reloading plugin JsFormat.js_formatter
reloading plugin JSONLint.JSONLint
(** snip **)
reloading plugin SublimeLinter-jscs.linter
reloading plugin SublimeLinter-jshint.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-shellcheck.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
(** snip **)
reloading plugin ESLint.ESLint
(** snip **)
reloading plugin Pretty JSON.PrettyJsonListeners
(** snip **)
plugins loaded
error: unable to open crawldb (~/Library/Application Support/Sublime Text 3/Index), indexing is unavailable
indexing: crawldb not available, indexing abandoned
environment variables loaded using: /bin/bash -l
SublimeLinter: WARNING: jshint cannot locate 'jshint'
SublimeLinter: WARNING: WARNING: jscs cannot locate 'jscs'
Package Control: No updated packages
```

**Comment by carrola7** [comment]
Thanks to all involved for the speedy fix.

**Comment by braver** [comment]
@neurospochtsfroind your log doesn't indicate problems.
