### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'loads'

### ISSUE THREAD

**Issue by AlLoud** [SublimeLinter/SublimeLinter#1216]
Just turned on Sublime Text today after the update and the crash report says:

	SublimeLinter: #2 eslint inspector.js ERROR:

	 Linter crashed.

	Traceback (most recent call last):
	  File "lint.backend in C:\Users\u\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
	  File "lint.linter in C:\Users\u\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 813, in lint
	  File "linter in C:\Users\u\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-eslint.sublime-package", line 52, in find_errors
	AttributeError: 'NoneType' object has no attribute 'loads'

**Comment by uniibu** [comment]
Got same error after update. Full debug log is as follows
``` SublimeLinter: #358 SublimeLinter.sublime-package:782: 'eslint' is linting 'file.js'
SublimeLinter: #358 SublimeLinter.sublime-package:1186: eslint: file.js ['C:\\Users\\u\\AppData\\Roaming\\npm\\eslint.cmd', '--format', 'json', '--stdin', '--stdin-filename', 'D:\\projects\\src\\file.js']
SublimeLinter: #358 SublimeLinter.sublime-package:1189: eslint: cwd: D:\projects
SublimeLinter: #358 SublimeLinter.sublime-package:809: eslint output:
    [{"filePath":"D:\\projects\\src\\file.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0}]
SublimeLinter: #358 __init__.py:1273: ERROR: Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\u\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in C:\Users\u\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 813, in lint
  File "linter in C:\Users\u\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-eslint.sublime-package", line 52, in find_errors
AttributeError: 'NoneType' object has no attribute 'loads'

**Comment by kaste** [comment]
Restart sublime. That's a simple import error. A package from the python std library (json) appears empty.

**Comment by uniibu** [comment]
Restarting sublime works. Thanks @kaste.
