### ISSUE TITLE
SL 4.1.0 runs CPU to max. 

### ISSUE THREAD

**Issue by jtheletter** [SublimeLinter/SublimeLinter#1220]
Suddenly today (my SL updated to 4.1.0 this morning), as I'm writing any code, periodically I hear my fans start running, and I see my CPU is maxed by Sublime app. 

It's happened many times. It happened just now. Console this time shows this: 
```
Unable to open /Users/JP/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/SublimeLinter.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "panel_view in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 64, in on_activated_async
  File "panel_view in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 239, in ensure_panel
  File "panel_view in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 235, in get_panel
AttributeError: 'NoneType' object has no attribute 'find_output_panel'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "panel_view in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 64, in on_activated_async
  File "panel_view in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 239, in ensure_panel
  File "panel_view in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 235, in get_panel
AttributeError: 'NoneType' object has no attribute 'find_output_panel'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "panel_view in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 64, in on_activated_async
  File "panel_view in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 239, in ensure_panel
  File "panel_view in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 235, in get_panel
AttributeError: 'NoneType' object has no attribute 'find_output_panel'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "panel_view in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 64, in on_activated_async
  File "panel_view in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 239, in ensure_panel
  File "panel_view in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 235, in get_panel
AttributeError: 'NoneType' object has no attribute 'find_output_panel'
```

`/Users/JP/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings`: 
```
{
    "delay": 0
}
```

`/Users/JP/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings`:
```
{
	"added_words":
	[
		"admin",
		"endian",
		"google",
		"googol",
		"online"
	],
	"color_scheme": "Packages/User/SublimeLinter/monokai-best (SL).tmTheme",
	"detect_indentation": false,
	"draw_white_space": "all",
	"enable_tab_scrolling": false,
	"ensure_newline_at_eof_on_save": true,
	"file_exclude_patterns":
	[
		".DS_Store"
	],
	"folder_exclude_patterns":
	[
		".git",
		".hg",
		".sass-cache",
		".svn",
		"CVS",
		"node_modules"
	],
	"font_size": 12,
	"highlight_line": true,
	"hot_exit": false,
	"ignored_packages":
	[
		"LiveStyle",
		"Vintage"
	],
	"margin": -12,
	"overlay_scroll_bars": "enabled",
	"remember_open_files": true,
	"show_full_path": true,
	"tab_size": 4,
	"theme": "Adaptive.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"use_simple_full_screen": true,
	"use_tab_stops": false,
	"word_wrap": false
}
```

**Comment by jtheletter** [comment]
If I activate debug mode, quit and relaunch Sublime, then I see the console is printing this message with nearly every mouseclick or keystroke: 

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line [three-digit number here varies], in on_activated_async
    callback.on_activated_async(v)
  File "highlight_view in /Users/JP/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line [three-digit number here varies], in on_activated_async
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by braver** [comment]
I got this a few times today, so perhaps that wasn't a fluke:

```
AttributeError: 'NoneType' object has no attribute 'find_output_panel'
```

Perhaps we need better guards against windows and views that have gone missing.

**Comment by kaste** [comment]
@braver Do you know which views are usually detached (without a window) `on_activated` so we can learn from that.

**Comment by braver** [comment]
I'll peak into my console a few times today, see if I can make sense out of it. It always feels bad to just scatter `if window` all around the code.

**Comment by kaste** [comment]
Can reproduce for opening settings. 🤢 What's wrong with Sublime?

**Comment by braver** [comment]
Oh, of course today I was using using a branch that had a bunch of `if window` guards and so I didn't see the error today. 🙄

**Comment by bmomberger-bitovi** [comment]
CC-me.  I'm also having this problem.  My Linter config:
```
{
    "debug": false,
    "delay": 0.25,
    "lint_mode": "background",
    "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
    "linters": {
        "eslint": {
            "disable": true,
            "args": [],
            "excludes": []
        },
        "jshint": {
            "disable": true,
            "args": [],
            "excludes": []
        },
        "jsxhint": {
            "disable": false,
            "args": [],
            "excludes": []
        },
        "lessc": {
            "disable": false,
            "args": [],
            "excludes": []
        },
        "sass": {
            "disable": false,
            "args": [],
            "excludes": []
        },
        "standard": {
            "disable": false,
            "args": [],
            "disable_if_not_dependency": false,
            "enable_if_dependency": true,
            "excludes": []
        }
    },
    "no_column_highlights_line": true,
    "paths": {
        "linux": [],
        "osx": [],
        "windows": []
    },
    
    "show_marks_in_minimap": true
}
```

And my installed packages via "Package Control.sublime-settings":

```
{
        "bootstrapped": true,
        "in_process_packages":
        [
        ],
        "installed_packages":
        [
                "Babel",
                "Better CoffeeScript",
                "DocBlockr",
                "EditorConfig",
                "Evernote",
                "GitHub Flavored Markdown Preview",
                "GitSavvy",
                "HexViewer",
                "HTML Mustache",
                "JavaScriptNext - ES6 Syntax",
                "JSX",
                "LessImproved",
                "LiveScript",
                "Package Control",
                "Pretty JSON",
                "Sass",
                "ShellCommand",
                "SublimeLinter",
                "SublimeLinter-contrib-lessc",
                "SublimeLinter-contrib-sass-lint",
                "SublimeLinter-contrib-standard",
                "SublimeLinter-eslint",
                "SublimeLinter-jshint",
                "SublimeLinter-jsxhint",
                "Theme - Cobalt2"
        ]
}
```

**Comment by braver** [comment]
@bmomberger-bitovi can you share the contents of your console after this happens?
