### ISSUE TITLE
SublimeLinter: ERROR: Linter crashed with pyyaml.

### ISSUE THREAD

**Issue by etienned** [SublimeLinter/SublimeLinter#1245]
I'm on 4.1.1 and getting this error with pyyaml linter (v1.2.1):

```
SublimeLinter: ERROR: Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/etienne/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/etienne/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 757, in lint
  File "lint.linter in /Users/etienne/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 1006, in run
  File "lint.linter in /Users/etienne/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 1030, in communicate
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by kaste** [comment]
pyyaml https://github.com/SublimeLinter/SublimeLinter-pyyaml has been deprecated in favor of https://packagecontrol.io/packages/SublimeLinter-contrib-yamllint

**Comment by etienned** [comment]
Ho, yes. Sorry for the noise.
