### ISSUE TITLE
SublimeLinter: #71 php course.php ERROR:   Linter crashed.  Traceback (most recent call last):

### ISSUE THREAD

**Issue by zhangzheng1019** [SublimeLinter/SublimeLinter#1248]
更新之后， 当保存时，就报这个问题，，，但是代码并没有问题

![image](https://user-images.githubusercontent.com/22359290/37630888-dcf72998-2c21-11e8-8b98-000dfbfc089b.png)

**Comment by braver** [comment]
https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/troubleshooting.rst

Debug logs plus (English) description of what happened please.

**Comment by bohwaz** [comment]
Same issue. Just loading any PHP file and I get that:

```
SublimeLinter: #42 php XXX.php ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /home/bohwaz/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /home/bohwaz/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 794, in lint
  File "lint.linter in /home/bohwaz/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 511, in get_cmd
TypeError: argument of type 'NoneType' is not iterable
```

This is with debug enabled.

**Comment by derralf** [comment]
same here

**Comment by kaste** [comment]
Restart Sublime.

**Comment by braver** [comment]
/me will re-open if proof that restart didn't help.
