### ISSUE TITLE
Sublimelinter crashes

### ISSUE THREAD

**Issue by ryami333** [SublimeLinter/SublimeLinter#1256]
While trying to lint a file with SL and SL-eslint, it fails. In debug mode I get the following error:
```
SublimeLinter: #5 eslint Router.js ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/mitch/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/mitch/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 786, in lint
  File "lint.linter in /Users/mitch/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 867, in process_match
  File "lint.linter in /Users/mitch/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 77, in full_line
IndexError: list index out of range
```

**Comment by braver** [comment]
Full debug log from restart up to this error please.

**Comment by kaste** [comment]
The error basically indicates that eslint reports an error on a line that is not in the buffer. So please open the Sublime console and look what eslint outputs here and how this relates to the buffer your editing.

**Comment by ryami333** [comment]
Could you please describe how I generate a full debug?
________________________________

**Comment by kaste** [comment]
Menu View > Show console

**Comment by ryami333** [comment]
Ahyip, it seems to be a bit of an obscure Flow error which presents itself in another file for some reason. Will fix that error and if that resolves this then I will close the issue. Cheers!

**Comment by kaste** [comment]
Ah, is this eslint-plugin-flowtype? Can you still post the eslint error? Maybe there is an option to suppress such errors or we could try to suppress them.

**Comment by ryami333** [comment]
Yeah it is. Sure, though it might not be revealing without understanding the Flow error itself, which I believe to also be a Flow bug. 

Hmm, it's hard to tell where one error stops and the next begins, but looks something like this:
```
Traceback (most recent call last):
  File "lint.backend in /Users/foo/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/foo/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 786, in lint
  File "lint.linter in /Users/foo/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 867, in process_match
  File "lint.linter in /Users/foo/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 77, in full_line
IndexError: list index out of range
>>> asdasd
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'asdasd' is not defined
SublimeLinter: #4 SublimeLinter.sublime-package:747: 'eslint' is linting 'Router.js'
SublimeLinter: #4 SublimeLinter.sublime-package:1045: eslint: Router.js ['/Users/foo/sites/acc-css-app/web-app/node_modules/.bin/eslint', '--format', 'json', '--stdin', '--stdin-filename', '/Users/foo/sites/acc-css-app/web-app/packages/client/src/components/Router/Router.js']
SublimeLinter: #4 SublimeLinter.sublime-package:1048: eslint: cwd: /Users/foo/sites/acc-css-app/web-app/packages/client/src/components/Router
SublimeLinter: #4 SublimeLinter.sublime-package:774: eslint output:
    [{"filePath":"/Users/foo/sites/acc-css-app/web-app/packages/client/src/components/Router/Router.js","messages":[{"ruleId":"flowtype-errors/show-errors","severity":2,"message":"property `children` is missing in object type but exists in `ScrollToTopProps` (see ./Users/foo/sites/acc-css-app/web-app/packages/commons/components/ScrollToTop/ScrollToTop.js:12).","line":144,"column":36,"nodeType":null,"source":"","endLine":144,"endColumn":64}],"errorCount":1,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"source":"// @flow\n\nimport React, { Fragment } from 'react';\nimport { connect } from 'react-redux';\nimport { Router as ReactRouter, Route, Switch } from 'react-router-dom';\nimport history from 'commons/utils/history/history';\nimport WebAppRoutes from 'commons/components/WebAppRoutes/WebAppRoutes';\nimport { authenticatedSelector } from 'commons/store/idam/session/session.selectors';\nimport ScrollToTop from 'commons/components/ScrollToTop/ScrollToTop';\n\nimport PageNotFound from 'commons/components/pages/PageNotFound/PageNotFound.container';\n\nimport PageLogout from '../pages/PageLogout/PageLogout.container';\n\nimport PageLaunch from '../pages/PageLaunch/PageLaunch';\nimport SecondFactor from '../pages/launch/SecondFactor/SecondFactor.container';\nimport PageEmailVerification from '../pages/PageEmailVerification/PageEmailVerification.container';\n\nimport PageRegister from '../pages/register/PageRegister/PageRegister';\nimport PageVerifyCode from '../pages/reset-password/PageVerifyCode/PageVerifyCode.container';\nimport PageVerifyEmail from '../pages/reset-password/PageVerifyEmail/PageVerifyEmail.container';\nimport PageVerifyPassword from '../pages/reset-password/PageVerifyPassword/PageVerifyPassword.container';\nimport PageConfirmDetails from '../pages/register/PageConfirmDetails/PageConfirmDetails.container';\nimport PageReceipt from '../pages/register/PageReceipt/PageReceipt.container';\nimport PageVerifyContact from '../pages/register/PageVerifyContact/PageVerifyContact.container';\n\ntype StateProps = {\n    authenticated: ?boolean,\n};\n\nfunction Router({ authenticated }: StateProps) {\n    const authenticatedRoutes = authenticated\n        ? [\n              <Route\n                  path=\"/register/verify-contact\"\n                  key=\"/register/verify-contact\"\n                  component={PageVerifyContact}\n              />,\n              ...WebAppRoutes,\n          ]\n        : [];\n    return (\n        <ReactRouter history={history}>\n            <Fragment>\n                <ScrollToTop />\n                <Switch>\n                    {/* Login */}\n                    <Route exact path=\"/login\" component={PageLaunch} />\n                    <Route\n                        exact\n                        path=\"/login/verify\"\n                        component={SecondFactor}\n                    />\n                    <Route\n                        exact\n                        path=\"/login/verify-email\"\n                        component={PageEmailVerification}\n                    />\n                    <Route\n                        path=\"/login/reset-password/verify-code\"\n                        component={PageVerifyCode}\n                    />\n                    <Route\n                        path=\"/login/reset-password/verify-email\"\n                        component={PageVerifyEmail}\n                    />\n                    <Route\n                        path=\"/login/reset-password/verify-password\"\n                        component={PageVerifyPassword}\n                    />\n                    {/* Register */}\n                    <Route\n                        path=\"/register/confirm-details\"\n                        component={PageConfirmDetails}\n                    />\n                    <Route\n                        path=\"/register/realme\"\n                        component={() => <PageRegister radio=\"realme\" />}\n                    />\n                    <Route\n                        path=\"/register/email\"\n                        component={() => <PageRegister radio=\"email\" />}\n                    />\n                    <Route exact path=\"/register\" component={PageRegister} />\n                    <Route path=\"/register/receipt\" component={PageReceipt} />\n\n                    <Route path=\"/logout\" component={PageLogout} />\n                    {/* Authenticated Paths */}\n                    {authenticatedRoutes}\n                    <Route component={PageNotFound} />\n                </Switch>\n            </Fragment>\n        </ReactRouter>\n    );\n}\n\nfunction mapStateToProps(state): StateProps {\n    return {\n        authenticated: authenticatedSelector(state),\n    };\n}\n\nexport default connect(mapStateToProps)(Router);\n"}]
SublimeLinter: #4 SublimeLinter-eslint.sublime-package:60: eslint output:
[{'errorCount': 1,
  'filePath': '/Users/foo/sites/acc-css-app/web-app/packages/client/src/components/Router/Router.js',
  'fixableErrorCount': 0,
  'fixableWarningCount': 0,
  'messages': [{'column': 36,
                'endColumn': 64,
                'endLine': 144,
                'line': 144,
                'message': 'property `children` is missing in object type but exists in `ScrollToTopProps` (see ./Users/foo/sites/acc-css-app/web-app/packages/commons/components/ScrollToTop/ScrollToTop.js:12).',
                'nodeType': None,
                'ruleId': 'flowtype-errors/show-errors',
                'severity': 2,
                'source': ''}],
  'source': '// @flow\n\nimport React, { Fragment } from \'react\';\nimport { connect } from \'react-redux\';\nimport { Router as ReactRouter, Route, Switch } from \'react-router-dom\';\nimport history from \'commons/utils/history/history\';\nimport WebAppRoutes from \'commons/components/WebAppRoutes/WebAppRoutes\';\nimport { authenticatedSelector } from \'commons/store/idam/session/session.selectors\';\nimport ScrollToTop from \'commons/components/ScrollToTop/ScrollToTop\';\n\nimport PageNotFound from \'commons/components/pages/PageNotFound/PageNotFound.container\';\n\nimport PageLogout from \'../pages/PageLogout/PageLogout.container\';\n\nimport PageLaunch from \'../pages/PageLaunch/PageLaunch\';\nimport SecondFactor from \'../pages/launch/SecondFactor/SecondFactor.container\';\nimport PageEmailVerification from \'../pages/PageEmailVerification/PageEmailVerification.container\';\n\nimport PageRegister from \'../pages/register/PageRegister/PageRegister\';\nimport PageVerifyCode from \'../pages/reset-password/PageVerifyCode/PageVerifyCode.container\';\nimport PageVerifyEmail from \'../pages/reset-password/PageVerifyEmail/PageVerifyEmail.container\';\nimport PageVerifyPassword from \'../pages/reset-password/PageVerifyPassword/PageVerifyPassword.container\';\nimport PageConfirmDetails from \'../pages/register/PageConfirmDetails/PageConfirmDetails.container\';\nimport PageReceipt from \'../pages/register/PageReceipt/PageReceipt.container\';\nimport PageVerifyContact from \'../pages/register/PageVerifyContact/PageVerifyContact.container\';\n\ntype StateProps = {\n    authenticated: ?boolean,\n};\n\nfunction Router({ authenticated }: StateProps) {\n    const authenticatedRoutes = authenticated\n        ? [\n              <Route\n                  path="/register/verify-contact"\n                  key="/register/verify-contact"\n                  component={PageVerifyContact}\n              />,\n              ...WebAppRoutes,\n          ]\n        : [];\n    return (\n        <ReactRouter history={history}>\n            <Fragment>\n                <ScrollToTop />\n                <Switch>\n                    {/* Login */}\n                    <Route exact path="/login" component={PageLaunch} />\n                    <Route\n                        exact\n                        path="/login/verify"\n                        component={SecondFactor}\n                    />\n                    <Route\n                        exact\n                        path="/login/verify-email"\n                        component={PageEmailVerification}\n                    />\n                    <Route\n                        path="/login/reset-password/verify-code"\n                        component={PageVerifyCode}\n                    />\n                    <Route\n                        path="/login/reset-password/verify-email"\n                        component={PageVerifyEmail}\n                    />\n                    <Route\n                        path="/login/reset-password/verify-password"\n                        component={PageVerifyPassword}\n                    />\n                    {/* Register */}\n                    <Route\n                        path="/register/confirm-details"\n                        component={PageConfirmDetails}\n                    />\n                    <Route\n                        path="/register/realme"\n                        component={() => <PageRegister radio="realme" />}\n                    />\n                    <Route\n                        path="/register/email"\n                        component={() => <PageRegister radio="email" />}\n                    />\n                    <Route exact path="/register" component={PageRegister} />\n                    <Route path="/register/receipt" component={PageReceipt} />\n\n                    <Route path="/logout" component={PageLogout} />\n                    {/* Authenticated Paths */}\n                    {authenticatedRoutes}\n                    <Route component={PageNotFound} />\n                </Switch>\n            </Fragment>\n        </ReactRouter>\n    );\n}\n\nfunction mapStateToProps(state): StateProps {\n    return {\n        authenticated: authenticatedSelector(state),\n    };\n}\n\nexport default connect(mapStateToProps)(Router);\n',
  'warningCount': 0}]
SublimeLinter: #4 __init__.py:1273: ERROR: Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/foo/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/foo/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 786, in lint
  File "lint.linter in /Users/foo/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 867, in process_match
  File "lint.linter in /Users/foo/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 77, in full_line
IndexError: list index out of range
```

**Comment by ryami333** [comment]
The error here seems to be this:
```
property `children` is missing in object type but exists in `ScrollToTopProps`
```
Which is either due to a Flow bug or a bad libdef for `react-router-dom`, or a combination of both. Looking a bit deeper at the mo.

**Comment by kaste** [comment]
Okay that just another plugin eslint-plugin-flowtype-errors

**Comment by kaste** [comment]
Do you have a line 144 in that Router.js?

**Comment by ryami333** [comment]
No, it's 104 lines long.

**Comment by kaste** [comment]
LOL

**Comment by ryami333** [comment]
The line 144 is referring to the relevant line in the `react-router-dom` lib def.

**Comment by kaste** [comment]
Okay, that's clearly a bug on their side. If you look at the json, it just doesn't make any sense. I thought they maybe add a custom property indicating that they actually report an error in a different file.

**Comment by ryami333** [comment]
Yeah I do agree, happy to have this closed.

**Comment by ryami333** [comment]
And thanks for your help.

**Comment by reintroducing** [comment]
I'm getting this error as well. This is all I'm seeing in the console:

```
SublimeLinter: #6 eslint NavigationDesktop.jsx ERROR:
=====================================================

Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/mprzybylski/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 100, in execute_lint_task
  File "lint.linter in /Users/mprzybylski/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 777, in lint
  File "linter in /Users/mprzybylski/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-eslint.sublime-package", line 75, in find_errors
KeyError: 'line'
```

This seems to have just started happening after I saw that SublimeLinter was recently upgraded. Any ideas? What else can I do to try and help troubleshoot this?

**Comment by kaste** [comment]
@reintroducing Please open a new issue, enable debug mode, look at the actual console output (View > Show Console), here you will see the eslint output and can already reason about it. An reported error without a line is really unusual.

**Comment by reintroducing** [comment]
@kaste I did some more digging after I posted this and based on some other issues I was able to Google I somehow fixed my issue. I think it had to do with nvm and path issues to my node version. I forgot (until finding that) that I had upgraded node yesterday as well :)

**Comment by vkd** [comment]
I can reproduce this error:
```
SublimeLinter: #9 __init__.py:1273: ERROR: Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/castle/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 100, in execute_lint_task
  File "lint.linter in /Users/castle/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 785, in lint
  File "lint.linter in /Users/castle/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 866, in process_match
  File "lint.linter in /Users/castle/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 77, in full_line
IndexError: list index out of range
```

I'm using `SublimeLinter-contrib-gometalinter` and this linter return errors like:
```
file1.go:15:...
file2.go:116:...
...
```

External linter (goconst) can return errors not only by current file (file1.go) but by another files too (file2.go, ...etc). Error position from file2.go can be large then size of file1.go. As I see `Sublimelinter` not check returned filenames from another linters, and in the same time another linters cannot get current filename on `run(self, cmd, code)` functions.

**Comment by kaste** [comment]
Errors coming from other files must be filtered, often this is done in split_match. E.g. https://github.com/SublimeLinter/SublimeLinter-gotype/blob/master/linter.py

**Comment by vkd** [comment]
Thanks for your example. We find solution in `SublimeLinter-contrib-gometalinter` and it resolved my case.

**Comment by kaste** [comment]
Good to hear.
