### ISSUE TITLE
Crash TypeError:  missing argument: 'self'

### ISSUE THREAD

**Issue by shadoskill** [SublimeLinter/SublimeLinter#1257]
Everything seems to work regardless, but very annoying I cant force hide the giant white error box that pops up every time I type...
```
SublimeLinter: #23 ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\shado\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in C:\Users\shado\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 762, in lint
  File "C:\Users\jrapp\PortableApps\PortableApps\cmder\vendor\sublime3\Data\Packages\=BB= LSL\src\sublimelinter_contrib_lslint.py", line 260, in run
  File "lint.linter in C:\Users\shado\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 1037, in communicate
TypeError: get_view_settings() missing 1 required positional argument: 'self'
```

**Comment by braver** [comment]
Full debug log from restart up to this error please.

**Comment by kaste** [comment]
Hi :wave:! 

Thanks for reporting, but you must file this issue against https://github.com/XenHat/SublimeLinter-contrib-lslint

The lslint plugin does a lot of stuff on its own, in particular they call `Linter.communciate(...)` which is clearly a bug on their side.
