### ISSUE TITLE
javac linter crashes

### ISSUE THREAD

**Issue by linusr** [SublimeLinter/SublimeLinter#1276]
Possibly crash happens 4.2 update.

`SublimeLinter: #1 SublimeLinter.sublime-package:746: 'javac' is linting 'Test.java'
SublimeLinter: #1 SublimeLinter.sublime-package:337: 'executable_path' has been deprecated. Just use an ordinary binary name instead. 
SublimeLinter: #1 __init__.py:1273: ERROR: Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\user1\Documents\Apps\SublimeText\Data\Installed Packages\SublimeLinter.sublime-package", line 100, in execute_lint_task
  File "lint.linter in C:\Users\user1\Documents\Apps\SublimeText\Data\Installed Packages\SublimeLinter.sublime-package", line 758, in lint
  File "lint.linter in C:\Users\user1\Documents\Apps\SublimeText\Data\Installed Packages\SublimeLinter.sublime-package", line 482, in get_cmd
TypeError: argument of type 'NoneType' is not iterable`

And linter setting in project file,
`"SublimeLinter":
    {
        "linters":
        {
            "javac": {
                "executable": "C:/Users/user1/Documents/Apps/Java8/bin/javac",
                "lint": "all,-deprecation",
                "args": [
                    "-encoding", "UTF8",
                     "-cp", "C:/Users/user1/Documents/cc_jdk8/sbl_libs/*",
                     "-d", "C:/Users/user1/Documents/cc_jdk8/lint"
                ]
            },
        }
    }`

**Comment by braver** [comment]
You should use triple backticks for code blocks.

@kaste I think we may need to update the plugin? `'executable_path' has been deprecated`

**Comment by kaste** [comment]
🚑 https://github.com/SublimeLinter/SublimeLinter-javac/pull/18
