### ISSUE TITLE
Show warning if env is not a dict

### ISSUE THREAD

**Issue by linusr** [SublimeLinter/SublimeLinter#1280]
After fix for #1276 stack trace for crash differs. This may not be related (?) to #1276 as 'executable' is correctly used by sublimelinter-javac.
```
SublimeLinter: #2 SublimeLinter.sublime-package:746: 'javac' is linting 'Test.java'
SublimeLinter: #2 SublimeLinter.sublime-package:539: javac: wanted executable is 'C:\Users\user1\Documents\Apps\Java8\bin\javac.exe'
SublimeLinter: #2 SublimeLinter.sublime-package:1044: javac: Test.java ['C:\\Users\\user1\\Documents\\Apps\\Java8\\bin\\javac.exe', '-Xlint:all,-deprecation', '-encoding', 'UTF8', '-encoding', 'UTF8', '-cp', 'C:/Users/user1/Documents/cc_jdk8/sbl_libs/*;C:/Users/user1/Documents/cc_jdk8/Development/target/classes/', '-d', 'C:/Users/user1/Documents/cc_jdk8/lint', 'C:\\Users\\user1\\Documents\\cc_jdk8\\Development\\src\\main\\java\\com\\Test.java']
SublimeLinter: #2 SublimeLinter.sublime-package:1047: javac: cwd: C:\Users\user1\Documents\cc_jdk8
SublimeLinter: #2 __init__.py:1273: ERROR: Linter crashed.

Traceback (most recent call last):
  File "lint.util in C:\Users\user1\Documents\Apps\SublimeText\Data\Installed Packages\SublimeLinter.sublime-package", line 305, in popen
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1104, in _execute_child
  File "./python3.3/collections/abc.py", line 495, in __iter__
  File "./python3.3/collections/__init__.py", line 789, in __getitem__
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lint.backend in C:\Users\user1\Documents\Apps\SublimeText\Data\Installed Packages\SublimeLinter.sublime-package", line 100, in execute_lint_task
  File "lint.linter in C:\Users\user1\Documents\Apps\SublimeText\Data\Installed Packages\SublimeLinter.sublime-package", line 761, in lint
  File "lint.linter in C:\Users\user1\Documents\Apps\SublimeText\Data\Installed Packages\SublimeLinter.sublime-package", line 1003, in run
  File "lint.linter in C:\Users\user1\Documents\Apps\SublimeText\Data\Installed Packages\SublimeLinter.sublime-package", line 1054, in communicate
  File "lint.util in C:\Users\user1\Documents\Apps\SublimeText\Data\Installed Packages\SublimeLinter.sublime-package", line 220, in communicate
  File "lint.util in C:\Users\user1\Documents\Apps\SublimeText\Data\Installed Packages\SublimeLinter.sublime-package", line 308, in popen
  File "./python3.3/collections/__init__.py", line 795, in get
  File "./python3.3/collections/__init__.py", line 789, in __getitem__
TypeError: string indices must be integers```

**Comment by kaste** [comment]
Hm, don't know what's throwing here. First aid, restart Sublime to be sure no old code is running. Then remove your `args` overrides. Did you override `env` as well?

**Comment by linusr** [comment]
Yes, I did override `env` while trying all options for the earlier issue #1276 . After removing `env` it works fine.
My bad. Thanks for helping out.

**Comment by kaste** [comment]
If you set `env` it must be a `dict`/mapping. What type did you set?  Maybe we should add a type check here for user convenience.

**Comment by kaste** [comment]
@braver We should be able to enforce this via our schema validation, no?

**Comment by braver** [comment]
I guess so, it should be an object then probably?
