### ISSUE TITLE
error on "lint this view": Precision not allowed in integer

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#1310]
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 230, in run
    hit(self.view, reason='on_user_request')
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 251, in hit
    logger.info('Delay buffer {} for {:.2}s'.format(bid, delay))
ValueError: Precision not allowed in integer format specifier
```

**Comment by kaste** [comment]
What's your delay setting?

**Comment by braver** [comment]
My settings:

```
// SublimeLinter Settings - User
{
    // "lint_mode": "save",
    "gutter_theme": "Default",
    // "debug": true,
    "highlights.time_to_idle": 3,
    "highlights.demote_while_editing": "all",
    // "show_panel_on_save": "window",
    // "statusbar.show_active_linters": false,
    // "statusbar.messages_template": "",
    "linters": {
        "eslint": {
            // "disable": true,
            // "excludes": [
            //     "*/programmingfonts/*"
            // ]
        },
        "annotations": {
            "disable": true,
        },
        "htmltidy": {
            // "disable": true,
        },
        "stylelint": {
            // "disable": true,
        },
        "flake8": {
            // "disable": true,
        },
        "tslint": {
            "project": "",
        },
        "shellcheck": {
            // "disable": true,
            "styles": [
                {
                    "mark_style": "stippled_underline",
                    "scope": "comment",
                    "priority": 0,
                    // "icon": "triangle-outline",
                    "types": ["warning"]
                }
            ]
        },
    },
    "styles": [
        {
            "mark_style": "squiggly_underline",
            "priority": 1,
            "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
            "icon": "pointer-outline",
            "types": [
                "warning"
            ]
        },
        {
            "mark_style": "squiggly_underline",
            "priority": 1,
            "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
            "icon": "pointer",
            "types": [
                "error"
            ]
        }
    ]
}
```
