### ISSUE TITLE
SublimeLinter raising exceptions after update

### ISSUE THREAD

**Issue by tomleo** [SublimeLinter/SublimeLinter#1353]
Everything worked fine until this mornings update.

```
Exception in thread Thread-50:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 1142, in run
  File "sublime_linter in /home/tom/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 245, in lint
  File "sublime_linter in /home/tom/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 332, in get_linters_for_view
  File "sublime_linter in /home/tom/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 332, in <setcomp>
  File "lint.base_linter.node_linter in /home/tom/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 40, in __init__
  File "lint.base_linter.node_linter in /home/tom/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 166, in read_manifest
  File "./python3.3/json/__init__.py", line 271, in load
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 367, in raw_decode
ValueError: Expecting property name enclosed in double quotes: line 51 column 3 (char 1472)
```

Not sure the root cause, or other debugging info for what's happening. FWIW all linting rules are via `.flake8` and `.eslintrc.js`

**Comment by kaste** [comment]
Hi 👋

Here it throws while decoding your packages.json Likely unrelated to 4.3 at least I don't remember touching anything here for quite some time.

**Comment by kaste** [comment]
(If this is right, good catch for a really bad error message though. 😀 )

**Comment by tomleo** [comment]
:+1: I had a trailing comma after removing a package from my `package.json`, everything is working again thanks.
