### ISSUE TITLE
'NoneType' object has no attribute 'run_command'

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#1369]
I start ST, then open a file from the sidebar. Usually seems to happen just the first time, or perhaps before some process is ready.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 1142, in run
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 245, in lint
    linters = get_linters_for_view(view)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 336, in get_linters_for_view
    view.window().run_command('sublime_linter_assigned', {
AttributeError: 'NoneType' object has no attribute 'run_command'
```

**Comment by braver** [comment]
@kaste `view.window()` at https://github.com/SublimeLinter/SublimeLinter/blob/master/sublime_linter.py#L336 sometimes returns `None`

**Comment by kaste** [comment]
As per util.is_lintable (or similar named) we don't want to lint detached views. Your bug issue does not point to which event actually issues the intent to lint and why this buffer becomes detached after the debounce period.

Still, if we find a detached view we must somehow abort the lint. Not firing the event would also lead to other bugs probably harder to debug. The event here is not optional.

**Comment by braver** [comment]
Yeah I was afraid you’d say that. Take the PR as a pointer to where it goes wrong, it probably needs a different approach.

This bug is quite prevalent on my machine.

**Comment by kaste** [comment]
Cannot reproduce. Sad but true.

**Comment by braver** [comment]
Well, I can. 

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 1142, in run
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 245, in lint
    linters = get_linters_for_view(view)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 336, in get_linters_for_view
    view.window().run_command('sublime_linter_assigned', {
AttributeError: 'NoneType' object has no attribute 'run_command'

Exception in thread Thread-5:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 1142, in run
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 245, in lint
    linters = get_linters_for_view(view)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 336, in get_linters_for_view
    view.window().run_command('sublime_linter_assigned', {
AttributeError: 'NoneType' object has no attribute 'run_command'
```

So, what do you want to do?

**Comment by braver** [comment]
@kaste how about

```py
    with lock:  # We're already debounced, so races are actually unlikely.
        if view.window():
            linters = get_linters_for_view(view)
        else:
            linters = []
```
