### ISSUE TITLE
Ensure user provided `args` has type `str|List` and provide good feedback

### ISSUE THREAD

**Issue by geoidesic** [SublimeLinter/SublimeLinter#1385]
Sublime Text 3, build 3170

I see this error if I close Sublime, then open it, then open a particular VueJs component. If I close the file and re-open it the error doesn't recur but nor does any further linting work. I suspect this is a Sublime Linter error, rather than a JsHint error but I'm not 100% sure about that. 

Here's the error:

```
SublimeLinter: #6 jshint ArticleEdit.vue ERROR:
===============================================

Linter crashed.

Traceback (most recent call last):
  File "/Users/geoidesic/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1146, in _communicate
    creationflags=util.get_creationflags()
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1386, in _execute_child
TypeError: Can't convert 'dict' object to str implicitly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/geoidesic/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 87, in execute_lint_task
    errors = linter.lint(code, view_has_changed, settings) or []
  File "/Users/geoidesic/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 754, in lint
    output = self.run(cmd, code)  # type: util.popen_output
  File "/Users/geoidesic/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1054, in run
    return self.communicate(cmd, code)
  File "/Users/geoidesic/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1065, in communicate
    return self._communicate(cmd, code)
  File "/Users/geoidesic/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1152, in _communicate
    cmd, uses_stdin, cwd, view, augmented_env))
  File "/Users/geoidesic/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1245, in make_nice_log_message
    cmd=' '.join(cmd)
TypeError: sequence item 2: expected str instance, dict found
```

\<SNIPPED\>

**Comment by braver** [comment]
Hm, works just fine on my machine. Can you share the full SL debug log, from the start of ST until the error occurs? Also, is this using the Vue Syntax package?

**Comment by geoidesic** [comment]
I'm not going to re-install SublimeLinter until this is fixed because it caused me to lose most of the day. Sublime kept crashing and it wouldn't let me uninstall Sublime Linter. Eventually I managed to first disable the plugin and then remove it and now Sublime is back to normal. I can't afford to go through that again.

I did share the full SL debug log. That was all of what appeared in the console window. If you're referring so some other log then you'd need to provide information about where to find it.

I am using the Vue Syntax Highlight plugin, if that's what you mean: https://github.com/vuejs/vue-syntax-highlight

**Comment by braver** [comment]
With a full log I mean enabling debug, restarting ST and then reproducing the error. If you’re not going to install SL, I guess we’re done here. I would like to debug this with you though, so please reopen and let me know when you’ve got time.

**Comment by kaste** [comment]
That's probably just a configuration error. You may still have your SublimeLinter user settings, if yes please post them. I don't think I need a 'better' log message.
