### ISSUE TITLE
On CMD+B build, I see this error randomly instead of my build output

### ISSUE THREAD

**Issue by it6** [SublimeLinter/SublimeLinter#1402]
```
SublimeLinter: #5 eslint 180506-three-sum.js ERROR:
===================================================

Linter crashed.

Traceback (most recent call last):
  File "/Users/kotamrs/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 87, in execute_lint_task
    errors = linter.lint(code, view_has_changed, settings) or []
  File "/Users/kotamrs/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 754, in lint
    output = self.run(cmd, code)  # type: util.popen_output
  File "/Users/kotamrs/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-eslint.sublime-package/linter.py", line 111, in run
    return super().run(cmd, code)
  File "/Users/kotamrs/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1054, in run
    return self.communicate(cmd, code)
  File "/Users/kotamrs/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1065, in communicate
    return self._communicate(cmd, code)
  File "/Users/kotamrs/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1164, in _communicate
    out = proc.communicate(code)
  File "./python3.3/subprocess.py", line 920, in communicate
  File "./python3.3/subprocess.py", line 1556, in _communicate
  File "./python3.3/subprocess.py", line 1670, in _communicate_with_poll
  File "./python3.3/subprocess.py", line 1607, in close_unregister_and_remove
OSError: [Errno 9] Bad file descriptor
```

**Comment by kaste** [comment]
Hi! I have another similar report that indicates that this has been introduced with Sublime 3.1

Can you confirm this? Are you on the latest and greatest?

Second: Which build cmd are you running here?

If not already set, can you set the setting 'kill_old_processes' (or similar named) to true.

**Comment by it6** [comment]
Yes, I am on `3.1`

The build command I use is 
```
{
  "cmd": [
    "node",
    "$file"
  ],
  "selector": "source.js"
}
```
I am not sure how to set `kill_old_processes`, is this in sublime settings?

**Comment by kaste** [comment]
It's a SublimeLinter setting.

**Comment by kaste** [comment]
PR is https://github.com/SublimeLinter/SublimeLinter/pull/1404 

Can you test this?

**Comment by it6** [comment]
From my initial testing it looks good, I don't see the error. I will report if I find any, you can merge this.
