### ISSUE TITLE
ImportError: No module named 'SublimeLinter'

### ISSUE THREAD

**Issue by f1l1pp0s** [SublimeLinter/SublimeLinter#1477]
Hi,

trying to install 'SublimeLinter' in Sublime Text 3.1.1 but getting the following errors.  I've executed the steps in https://github.com/thomasmeeus/SublimeLinter-contrib-yamllint, so python is there yamllint is there: 
$ which python
/usr/bin/python

$ which pip
/usr/bin/pip

$ which yamllint
/usr/bin/yamllint

but I am getting this:

DPI mode: system
DPI scale: 1
startup, version: 3176 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /D/userdata/user/Application Data/Sublime Text 3/Packages
state path: /D/userdata/user/Application Data/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /D/userdata/user/Application Data/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.5186
startup time: 0.6796
first paint time: 0.6836
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeGit.SublimeGit
reloading plugin SublimeLinter-contrib-yaml-lint.linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "D:\userdata\user\Application Data\Sublime Text 3\Installed Packages\SublimeLinter-contrib-yaml-lint.sublime-package\linter.py", line 13, in <module>
ImportError: No module named 'SublimeLinter'
reloading plugin SublimeLinter-contrib-yamllint.linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "D:\userdata\user\Application Data\Sublime Text 3\Installed Packages\SublimeLinter-contrib-yamllint.sublime-package\linter.py", line 13, in <module>
ImportError: No module named 'SublimeLinter'
plugins loaded

**Comment by braver** [comment]
Hi! Tips:

- put triple backticks around code blocks
- install the SublimeLinter package, not just SublimeLinter-contrib-yamllint

**Comment by f1l1pp0s** [comment]
Hi,

thanks a lot ! I just realized it !

**Comment by braver** [comment]
🎉
