### ISSUE TITLE
ValueError: Precision not allowed in integer format specifier

### ISSUE THREAD

**Issue by akb0787** [SublimeLinter/SublimeLinter#1481]
```
Traceback (most recent call last):
  File "/home/akb/pytorch_learning/chap4_dogsandcats", line 110, in <module>
    epoch_loss, epoch_accuracy = fit(epoch,model,train_data_loader,phase='training')
  File "/home/akb/pytorch_learning/chap4_dogsandcats", line 103, in fit
    print(f'{phase} loss is {loss:{5}.{2}} and {phase} accuracy is {running_correct}/{len(data_loader.dataset)}{accuracy:{10}.{4}}')
  File "/home/akb/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 337, in __format__
    return self.item().__format__(format_spec)
ValueError: Precision not allowed in integer format specifier
```

i am getting this error in sublime text 3 with CPU, and why does it work fine with GPU. anyone could help?

**Comment by kaste** [comment]
Hi @akb0787!

You're in the wrong repro. This here is about SublimeLinter - the linting framework for Sublime Text.
