### ISSUE TITLE
Startup issues with v4.9.0

### ISSUE THREAD

**Issue by buildersbrewery** [SublimeLinter/SublimeLinter#1530]
```text
Traceback (most recent call last):
  File "...\ST3\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "...\ST3\sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "...\ST3\Data\Installed Packages\SublimeLinter.sublime-package\highlight_view.py", line 117, in <module>
  File "...\ST3\Data\Installed Packages\SublimeLinter.sublime-package\highlight_view.py", line 118, in UpdateErrorRegions
AttributeError: 'module' object has no attribute 'distinct_until_buffer_changed'
Traceback (most recent call last):
  File "...\ST3\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "...\ST3\sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "...\ST3\Data\Installed Packages\SublimeLinter.sublime-package\panel_view.py", line 57, in <module>
  File "...\ST3\Data\Installed Packages\SublimeLinter.sublime-package\panel_view.py", line 97, in UpdateState
AttributeError: 'module' object has no attribute 'distinct_until_buffer_changed'
Traceback (most recent call last):
  File "...\ST3\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "...\ST3\sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "...\ST3\Data\Installed Packages\SublimeLinter.sublime-package\sublime_linter.py", line 123, in <module>
  File "...\ST3\Data\Installed Packages\SublimeLinter.sublime-package\sublime_linter.py", line 124, in BackendController
AttributeError: 'module' object has no attribute 'distinct_until_buffer_changed'
Traceback (most recent call last):
  File "...\ST3\Data\Packages\SublimeLinter\lint\util.py", line 264, in generate_color_scheme_async
    plist = ElementTree.XML(scheme_text)
  File "./python3.3/xml/etree/ElementTree.py", line 1356, in XML
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```

**Comment by braver** [comment]
```
ST3\Data\Packages\SublimeLinter\lint\util.py", line 264, in generate_color_scheme_async
```

SublimeLinter 4 never had a `generate_color_scheme_async`.

- Do you have a SublimeLinter 3 installed as well? 
- Or are you upgrading from 3 to 4?
- Does it go away after restarting ST?

**Comment by buildersbrewery** [comment]
PC hadn't removed the v3 files at all after upgrade 🤷🏼‍♂️

**Comment by braver** [comment]
Weird
