### ISSUE TITLE
"TypeError: object of type 'bool' has no len()" after recent update

### ISSUE THREAD

**Issue by saneef** [SublimeLinter/SublimeLinter#1550]
No error were showing errors on the panel. In the console I could see this message.

```
>>> 
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 773, in on_post_window_command
    callback.on_post_window_command(window, name, args)
  File "/Users/anon/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/panel_view.py", line 120, in on_post_window_command
    fill_panel(window)
  File "/Users/anon/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/panel_view.py", line 394, in fill_panel
    for error in chain(*errors_by_bid.values())
  File "/Users/anon/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/panel_view.py", line 394, in <listcomp>
    for error in chain(*errors_by_bid.values())
TypeError: object of type 'bool' has no len()
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 773, in on_post_window_command
    callback.on_post_window_command(window, name, args)
  File "/Users/anon/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/panel_view.py", line 120, in on_post_window_command
    fill_panel(window)
  File "/Users/anon/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/panel_view.py", line 394, in fill_panel
    for error in chain(*errors_by_bid.values())
  File "/Users/anon/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/panel_view.py", line 394, in <listcomp>
    for error in chain(*errors_by_bid.values())
TypeError: object of type 'bool' has no len()
```

Sublime Text Version 3.1.1 build 3176
I use `SublimeLinter-eslint` and `SublimeLinter-flow`.

**Comment by kaste** [comment]
Ad-hoc fix is at #1552. Locally tested with eslint and flow.
