### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by clms2** [SublimeLinter/SublimeLinter#1575]
Hi,
    I have successfully installed sublimeLinter in the latest version of sublime, but I can\`t install it  properly in version 3061(there are  some reasons I should run it under 3061), here is the first installing console dump, and below to it is the restart of sublime text.EveryTime I restarted sublime, it would install jsonschema again. It seems like it has some problem working with jsonschema, and I have tried to put a `dependencies.json` in `/Data/Packages/` with the instruction of [jsonschema](https://github.com/kylebebak/sublime-jsonschema#how-to-use-jsonschema-as-a-dependency), but it didn`t work.
    Thanks for the great work!

```
DPI scale: 1
startup, version: 3061 windows x32 channel: dev
executable: /E/work/st3061/sublime_text.exe
working dir: /E/work/st3061
packages path: /E/work/st3061/Data/Packages
state path: /E/work/st3061/Data/Local
hardware concurrency: 4
zip path: /E/work/st3061/Packages
zip path: /E/work/st3061/Data/Installed Packages
found 9 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 10 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Cobalt2.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 1 orphaned files: 4 total files: 273 cache hits: 272
pre session restore time: 0.281761
startup time: 0.568761
first paint time: 0.568761
launching: /E/work/st3061/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.Encoding
loaded 837 snippets
reloading plugin Default.EncodingHelper
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PHP Companion.PHP Companion
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin Alignment.Alignment
reloading plugin All Autocomplete.all_views_completions
reloading plugin ChineseLocalizations.Localization
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin GoToLastEdit.GotoLastEdit
reloading plugin User.GotoLastEdit
plugins loaded
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2019-03-21 17:54:46, next run at 2019-03-21 18:54:46 or after
ignored packages updated to: [GotoLastEdit, SublimeLinter, Vintage]
found 1 files for base name Cobalt2.sublime-theme
reloading Packages/User/Package Control.sublime-settings
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Cobalt2.sublime-theme
theme loaded
Reloading /E/work/st3061/Data/Packages/User/Preferences.sublime-settings
Package Control: The dependency 'jsonschema' is not currently installed; installing...
Package Control: The dependency 'jsonschema' has successfully been installed or updated
reloading Packages/User/Package Control.sublime-settings
ignored packages updated to: [GotoLastEdit, Vintage]
found 1 files for base name Cobalt2.sublime-theme
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
Traceback (most recent call last):
  File "E:\work\st3061\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "E:\work\st3061\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "active_linters_view in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 6, in <module>
  File "E:\work\st3061\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 6, in <module>
  File "E:\work\st3061\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.linter in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 12, in <module>
  File "E:\work\st3061\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.persist in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 7, in <module>
  File "E:\work\st3061\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.settings in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 5, in <module>
ImportError: cannot import name validate
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
Traceback (most recent call last):
  File "E:\work\st3061\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "E:\work\st3061\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "goto_commands in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 6, in <module>
ImportError: cannot import name persist
reloading plugin SublimeLinter.highlight_view
Traceback (most recent call last):
  File "E:\work\st3061\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "E:\work\st3061\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "highlight_view in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 10, in <module>
  File "E:\work\st3061\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.style in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 2, in <module>
ImportError: cannot import name persist
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
Traceback (most recent call last):
  File "E:\work\st3061\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "E:\work\st3061\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "panel_view in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 6, in <module>
ImportError: cannot import name persist
reloading plugin SublimeLinter.status_bar_view
Traceback (most recent call last):
  File "E:\work\st3061\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "E:\work\st3061\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "status_bar_view in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 4, in <module>
ImportError: cannot import name persist
reloading plugin SublimeLinter.sublime_linter
Traceback (most recent call last):
  File "E:\work\st3061\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "E:\work\st3061\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "sublime_linter in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 15, in <module>
  File "E:\work\st3061\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lint.backend in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 15, in <module>
ImportError: cannot import name style
found 10 files for base name Default.sublime-keymap
found 11 files for base name Main.sublime-menu
theme loaded
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Cobalt2.sublime-theme
theme loaded
Reloading /E/work/st3061/Data/Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Cobalt2.sublime-theme
theme loaded
Reloading /E/work/st3061/Data/Packages/User/Preferences.sublime-settings

```

```
DPI scale: 1
startup, version: 3061 windows x32 channel: dev
executable: /E/work/st3061/sublime_text.exe
working dir: /E/work/st3061
packages path: /E/work/st3061/Data/Packages
state path: /E/work/st3061/Data/Local
hardware concurrency: 4
zip path: /E/work/st3061/Packages
zip path: /E/work/st3061/Data/Installed Packages
found 10 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 11 files for base name Main.sublime-menu
loading pointer bindings
found 1 files for base name Cobalt2.sublime-theme
loading bindings
theme loaded
app ready
wrote startup cache, added files: 5 orphaned files: 0 total files: 277 cache hits: 272
pre session restore time: 0.244289
startup time: 0.551289
first paint time: 0.551289
launching: /E/work/st3061/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.Encoding
loaded 837 snippets
reloading plugin Default.EncodingHelper
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PHP Companion.PHP Companion
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin Alignment.Alignment
reloading plugin All Autocomplete.all_views_completions
reloading plugin ChineseLocalizations.Localization
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin GoToLastEdit.GotoLastEdit
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin User.GotoLastEdit
plugins loaded
Traceback (most recent call last):
  File "E:\work\st3061\sublime_plugin.py", line 157, in on_api_ready
    m.plugin_loaded()
  File "panel_view in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 24, in plugin_loaded
  File "panel_view in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 310, in ensure_panel
  File "panel_view in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 306, in get_panel
AttributeError: 'Window' object has no attribute 'find_output_panel'
Traceback (most recent call last):
  File "E:\work\st3061\sublime_plugin.py", line 526, in run_
    return self.run()
  File "message_view in E:\work\st3061\Data\Installed Packages\SublimeLinter.sublime-package", line 41, in run
AttributeError: 'Window' object has no attribute 'destroy_output_panel'
Emmet: No need to update PyV8
Package Control: Installing 1 missing dependency
Package Control: Installed missing dependency jsonschema
Package Control: Skipping automatic upgrade, last run at 2019-03-21 17:54:46, next run at 2019-03-21 18:54:46 or after
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.

```

**Comment by braver** [comment]
3061 is ancient, that’s like over 4 years ago. I can’t help that it doesn’t work, if you want any packages you need to probably  get 4 year old versions of them as well.
