### ISSUE TITLE
ERROR: Unhandled exception

### ISSUE THREAD

**Issue by KrasikovaEN** [SublimeLinter/SublimeLinter#1615]
I'm receiving this error on Ubuntu 18.04 in Sublime Text 3, SublimeLinter 4.11.2 and SublimeLinter-eslint 4.1.6:

```
SublimeLinter: ERROR: Unhandled exception:
Traceback (most recent call last):
  File "/home/kate/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 157, in execute_lint_task
    errors = linter.lint(code, view_has_changed)
  File "/home/kate/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1021, in lint
    return self.filter_errors(self.parse_output(output, virtual_view))
  File "/home/kate/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1046, in filter_errors
    for error in errors
  File "/home/kate/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1045, in <listcomp>
    error
  File "/home/kate/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1084, in parse_output_via_regex
    for m in self.find_errors(output):
  File "/home/kate/.config/sublime-text-3/Installed Packages/SublimeLinter-eslint.sublime-package/linter.py", line 92, in find_errors
    line=match['line'] - 1,  # apply line_col_base manually
KeyError: 'line'
```

**Comment by kaste** [comment]
Hm, 👋,  'line' is not optional for eslint errors iirc. Which eslint + eslint-plugins does that? Will it go away by updating the dependencies.

You could look at the actual 'output' (the JSON obj we show in the console) here and find the offending 'message' without the 'line'.

**Comment by KrasikovaEN** [comment]
I'm using `babel-eslint` parser.
When I run eslint in terminal I get the same error as in sublime console with debug mode:

`
Parsing error: No Babel config file detected for /home/kate/Work/crowley/cms/assets/app/Plugins/drpdwn/parts/positionPane.js. Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files
`

All npm packages has latest versions.
If you need any additional info let me know.

**Comment by kaste** [comment]
I'm curious what JSON eslint yields here. On the terminal this would be `eslint --format json`. Otherwise, you should try to fix the config here, it will probably just work after that.

**Comment by KrasikovaEN** [comment]
I'm fixed this issue. I fulfilled a few command in terminal:
`sudo npm install eslint babel-eslint --save-dev`
`sudo npm install eslint-plugin-import@^2.14.0`
`sudo npm install eslint-config-airbnb-base`

Thanks for help.

**Comment by kaste** [comment]
That's good for you but I would have liked if you posted the actual JSON because I'm in doubt if I should expect 'line' to be mandatory or not. Should I just throw away errors without a line. Do they have any other useful information etc.
