### ISSUE TITLE
eslint error in ST3, but fine from CLI

### ISSUE THREAD

**Issue by MartinSoderholm** [SublimeLinter/SublimeLinter#1625]
I get the following error from the linter:

```
SublimeLinter: #9 linter.py:1003      eslint: linting 'model.js'
SublimeLinter: #9 linter.py:1478      Running ...

  /Users/matte/repos/mozy  (working dir)
  $ cat src/model.js | /Users/matte/repos/mozy/node_modules/.bin/eslint --format json --stdin --stdin-filename /Users/matte/repos/mozy/src/model.js

SublimeLinter: #9 linter.py:49        ERROR: /Users/matte/repos/mozy/node_modules/eslint/lib/cli-engine/cli-engine.js:257
        ...calculateStatsPerFile(messages)
        ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/matte/repos/mozy/node_modules/eslint/lib/cli-engine/index.js:3:23)
    at Module._compile (module.js:573:32)

SublimeLinter: #9 linter.py:1076      eslint: no output
SublimeLinter: sublime_linter.py:529  Linting 'model.js' took 0.23s
```

But if I take the exact command and run in the cli:
```sh
> cat src/model.js | /Users/matte/repos/mozy/node_modules/.bin/eslint --format json --stdin --stdin-filename /Users/matte/repos/mozy/src/model.js
```

I get output:
```json
[{"filePath":"/Users/matte/repos/mozy/src/model.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0}]
```

`npx eslint src/**.js` also works fine.

Linter settings:
```json
// SublimeLinter Settings - User
{
    "lint_mode": "load_save",
    "linters": {
        "eslint": {
            "disable": false
        }
    }
}
```

Using  
SublimeLinter v4.11.3  
SublimeLinter-eslint v4.1.6

**Comment by kaste** [comment]
Hi! Well from the error eslint throws it looks like a newer eslint version runs on an outdated node version bc it doesn't recognize the three dots as valid syntax. 

Maybe you have some magic like NVM on the command line? You can try to start Sublime from the command line ("subl ."). You could try pruning and reinstalling node_modules in case ... well computers.

(You run the same command here but the node resolving is implicit.) Take a peek at the eslint command to get a picture how they find the node actually.

**Comment by MartinSoderholm** [comment]
I do use NVM and ST3 was using an old macOS node version. Thanks for hinting me to the solution, updated my global node install and it worked.
