### ISSUE TITLE
ValueError: path is on mount 'C:', start on mount 'E:'

### ISSUE THREAD

**Issue by jfcherng** [SublimeLinter/SublimeLinter#1634]
## Reproduce

Probably only happens on Windows due to having a problem when calculating relative path between `C:` and `E:`.

Steps:
- Enable SL's debug mode.
- Open a ST project which is on `E:`.
- Open a file on `C:`.
- The opened file from `C:` cannot be linted.

```
SublimeLinter: #1 __init__.py:1273    ERROR: Unhandled exception:
Traceback (most recent call last):
  File "C:\Users\Clover\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/backend.py", line 155, in execute_lint_task
    errors = linter.lint(code, view_has_changed)
  File "C:\Users\Clover\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1085, in lint
    output = self.run(cmd, code)
  File "C:\Users\Clover\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1469, in run
    return self.communicate(cmd, code)
  File "C:\Users\Clover\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1480, in communicate
    return self._communicate(cmd, code)
  File "C:\Users\Clover\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1576, in _communicate
    'Running ...', cmd, uses_stdin, cwd, view, env=None))
  File "C:\Users\Clover\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1668, in make_nice_log_message
    rel_filename = os.path.relpath(filename, cwd)
  File "./python3.3/ntpath.py", line 564, in relpath
ValueError: path is on mount 'C:', start on mount 'E:'
SublimeLinter: sublime_linter.py:482  Linting 'test.cpp' took 0.05s
```

## Related?

https://github.com/SublimeLinter/SublimeLinter/issues/1179
https://github.com/SublimeLinter/SublimeLinter/issues/721
https://github.com/SublimeLinter/SublimeLinter-gcc/pull/17#issuecomment-514397950

**Comment by kaste** [comment]
Thanks for reporting! 

The lines in the trace are off by a couple of lines but this is simple to fix by catching the error.

**Comment by jfcherng** [comment]
Hmm... somehow I can no longer reproduce this. Maybe it's configuration-related.

**Comment by kaste** [comment]
This is simple to repro, e.g. you hack on SublimeLinter, usually a folder on drive C, and then open a file from another drive. It is a small bug bc you must have debug mode on otherwise we never hit that code path for pretty printing the command.
