### ISSUE TITLE
Sublime Text >= 4082 has breaking changes for the goto commands

### ISSUE THREAD

**Issue by gerardroche** [SublimeLinter/SublimeLinter#1763]
A syntax error exception is reported on startup in >= 4082:

```
...
reloading python 3.3 plugin SublimeLinter.goto_commands
Traceback (most recent call last):
  File "/home/code/sublime_text_4/Lib/python33/sublime_plugin.py", line 304, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/code/.config/sublime-text/Packages/SublimeLinter/goto_commands.py", line 3, in <module>
    from Default import history_list
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/home/code/sublime_text_4/Lib/python33/sublime_plugin.py", line 1600, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/code/sublime_text_4/Packages/Default.sublime-package/history_list.py", line 27
    return (f'JumpRecord({self.key!r}, '
                                       ^
SyntaxError: invalid syntax
```

See https://github.com/sublimelsp/LSP/pull/1257 and https://github.com/NeoVintageous/NeoVintageous/issues/741.

**Comment by kaste** [comment]
GitSavvy (dev) too.  🤷

**Comment by gerardroche** [comment]
Seems like an easy fix for you:

```
view.run_command('add_jump_record', {'selection': [(r.a, r.b) for r in view.sel()]})
```

**Comment by craigmac** [comment]
> Seems like an easy fix for you:
> 
> ```
> view.run_command('add_jump_record', {'selection': [(r.a, r.b) for r in view.sel()]})
> ```

Thanks @gerardroche but how do I actually use this snippet to fix the issue? Where do I put it?

**Comment by ihabunek** [comment]
The issue is that ST4 removed `get_jump_history_for_view`. So the fix is to replace it with the snippet above. This is how LSP project handled it in their ST4 branch: https://github.com/sublimelsp/LSP/commit/5705aee211a0c5eedfa5cd542351f2194ab0c562#diff-7f1daa77d5f4290e1d00c7477bb2dff2

Talking with some of the devs on sublime discord, they mentioned the history functions are not documented, so not officially supported. However, the `add_jump_record` command proposed above is not supported on ST3, and would just be ignored.

One thing you could do to support both st3 and st4 is test `sublime.version()` and run the old code on 3 and the above code on 4.

BTW; people on the sublime discord are very friendly and helpful for solving this kind of issue https://discord.gg/HcmwdVK

**Comment by wbond** [comment]
Just to be clear, the code in SublimeLinter that does `from Default import history_list` successfully imported in builds 4050 - 4081, but it didn't actually do anything since the Default package now runs in the Python 3.8 plugin_host. Thus any changes SublimeLinter may have been making wouldn't have actually affecting the history list.

In fact, the history list was significantly revamped in build 4059, with even more improvements in 4083, and there should be even fewer situations where a plugin should need to muck about in there.

We do have the `add_jump_record` command now, which bridges the gap of plugins running in Python 3.3 being able to affect the history list which runs in Python 3.8. However, unless you are jumping around based on links in popups shown via hover events, this really shouldn't be all that useful. The history list now tracks selection changes, sheet changes, etc all automatically. In build 4084 there will likely be some more small tweaks that should make it "just work" in more situations, such as inferring if jump records should be added based on if `sublime.TRANSIENT` is passed when opening a file.

**Comment by kaste** [comment]
FWIW, `add_jump_record` is not a replacement here (right now) because it doesn't work as I would expect.  It only *maybe* adds a record to the jump history.

**Comment by wbond** [comment]
That was true of manually calling `push_selection()` also.

But then again no one running builds 4050-4081 even noticed that the usage of the history list within SublimeLinter was doing nothing… so maybe it isn't needed as much as it was before 4059? 😄

**Comment by wbond** [comment]
If there is something deficient about the current history list implementation, I'd most prefer seeing if it makes sense to fix it in core. Then if we need an additional command for something, I'd consider that.

It isn't clear to me what SublimeLinter needs it for since the changes in 4059 and 4083. Perhaps the best path forward would be to list any failures of the implementation in 4083 and see if we can get those resolved. Since I just did a bunch of work on the history list, now would be an ideal time to detail any bugs so I can get them squashed while I am in this area of the code base.

**Comment by kaste** [comment]
ST3 `push_selection` always pushed *except* you push the exact same selection again.  BTW, here in SublimeLinter land we never receive issues or feedback about such small detail. 🤷

**Comment by wbond** [comment]
> ST3 push_selection always pushed except you push the exact same selection again.

That isn't a bug with 4083 though… that just means the old implementation was simplistic.

I'm likely going to tweak the `history_list.py` implementation to not blow up on Python 3.3, but that won't revert all of the changes that have been added, and it still won't do anything if a plugin is running in Python 3.3.

The only path forward is to report issues with the current implementation and keep improving it. It has already addressed many issues from ST3.

**Comment by braver** [comment]
> and it still won't do anything if a plugin is running in Python 3.3.

We currently have a dependency that keeps us in 3.3. An improved history implementation (or improved _anything_ really) is for me a good enough reason to drop that dependency so we can go to 3.8 though. The next hurdle though, is probably to get ST4 running reliably enough for @kaste to make the switch. I don't use history jumping etc enough to really notice anything anyway 😄
