### ISSUE TITLE
ImportError: cannot import name flash

### ISSUE THREAD

**Issue by VivienGiraud** [SublimeLinter/SublimeLinter#1768]
Hi,
I was digging for why I can't have flake8 linting since couples of weeks.
Delete it (rm -rf folder) reinstall it, still does not works I have this backtrace. Even did a `satisfy dependencies` did not change anything.

Backtrace : 
```reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading settings Packages/SublimeLinter/panel/message_view.sublime-settings
reloading settings Packages/SublimeLinter/panel/panel.sublime-settings
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.quick_actions
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/sublime_linter.py", line 24, in <module>
ImportError: cannot import name flash
reloading settings Packages/SublimeLinter/SublimeLinter.sublime-settings
generating syntax summary
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

**Comment by kaste** [comment]
Hm.  What backtrace are you showing here?  Is this on startup?  Which folder did you `rm` as I understand you installed using Package Control, so SublimeLinter is just one file actually.  (These are zip files btw so you can open them and look what's inside.)

I have no idea what could have happened here.  Usually restarting between uninstalling and installing might be good in such cases; and looking at startup at the console because maybe Package Control does some background stuff. 

Likely that you have an override in the Packages folder.  (Basically two versions installed at the same time.)

**Comment by VivienGiraud** [comment]
Backtrace is on install package.
rm is on a terminal, just did a `rm -rf /Users/vivien/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/SublimeLinter*`
I should not have two versions installed as I removed everything related to SublimeLinter using `rm`.
I will try a restart.

**Comment by VivienGiraud** [comment]
OK, after restarting, uninstall it, reinstall it I now have another console backtrace :
```Package Control: The dependency 'jsonschema' is not currently installed; installing...
Package Control: The dependency 'jsonschema' has successfully been installed or updated
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Markdown", "Vintage"]
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter._init
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/_init.py", line 1, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 15, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading plugin SublimeLinter.active_linters_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/active_linters_view.py", line 8, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 15, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading plugin SublimeLinter.busy_indicator_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/busy_indicator_view.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 15, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading plugin SublimeLinter.goto_commands
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/goto_commands.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 15, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading plugin SublimeLinter.highlight_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/highlight_view.py", line 13, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 15, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading plugin SublimeLinter.log_handler
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/log_handler.py", line 5, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 15, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading plugin SublimeLinter.message_view
reloading settings Packages/SublimeLinter/panel/message_view.sublime-settings
reloading settings Packages/SublimeLinter/panel/panel.sublime-settings
reloading plugin SublimeLinter.panel_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/panel_view.py", line 10, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 15, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading plugin SublimeLinter.quick_actions
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/quick_actions.py", line 4, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 15, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading plugin SublimeLinter.status_bar_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/status_bar_view.py", line 4, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 15, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading plugin SublimeLinter.sublime_linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/sublime_linter.py", line 14, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/log_handler.py", line 5, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 15, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/vivien/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
generating syntax summary
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

**Comment by kaste** [comment]
In `Sublime Text 3/Packages` could be an override.

**Comment by VivienGiraud** [comment]
@kaste Not sure to get your point.

**Comment by kaste** [comment]
You installed using Package Control right now into `.../Sublime Text 3/Installed Packages` but there are other folders under `Sublime Text 3` usually. There should be also `Packages`.  For example `ST3/Packages/User` should be there?.  Also maybe Cache folder.

**Comment by VivienGiraud** [comment]
Thanks for the hint, but it seems pretty empty : 
```$ ls /Users/vivien/Library/Application\ Support/Sublime\ Text\ 3/Packages/
User            jsonschema      markupsafe      natsort         pathlib         pymdownx        python-markdown pyyaml          requests
backrefs        lxml            mdpopups        numpy           pygments        python-jinja2   python-toml     rainbow_csv     sublime_lib
$ ls /Users/vivien/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/SublimeLinter
Monokai (Flake8Lint) (SL).tmTheme```

**Comment by kaste** [comment]
I have no clue.  

@braver Are there caches on Mac?

@VivienGiraud Just uninstall SL, restart and then git clone into `ST3/Packages`?  (Manual install)

**Comment by VivienGiraud** [comment]
Ho my god, did the manual way and it worked.
I just had a message once restarted : 
```Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.``` 
Restarted it and voilà !
Thanks @kaste
