### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by OKNoah** [SublimeLinter/SublimeLinter#1774]
```
SublimeLinter: ERROR: Unhandled exception:
Traceback (most recent call last):
  File "/Users/noahgray/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 155, in execute_lint_task
    finalize_errors(linter, errors, offsets)
  File "/Users/noahgray/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 235, in finalize_errors
    'priority': style.get_value('priority', error, 0),
  File "/Users/noahgray/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/style.py", line 54, in get_value
    return get_value_(key, linter, code, error_type, default)
  File "./python3.3/functools.py", line 275, in wrapper
  File "/Users/noahgray/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/style.py", line 80, in get_value_
    if error_type in style_definition.get('types', [error_type]):
AttributeError: 'str' object has no attribute 'get'
```

macOS 10.15.7

This happens even with all linter plugins removed.

**Comment by kaste** [comment]
Hm, this *should* be an issue with your settings file.  Basically *if* the key `styles` has a `str` value.  A bit strange though because we validate the settings on save, and thus if I do this here it opens a panel indicating that my settings are wrong.

**Comment by kaste** [comment]
> This happens even with all linter plugins removed.

That's especially strange because this error is triggered by `finalize_errors` as per your stacktrace; obviously if no linter adapters are installed, we can never reach this point. 🤔
