### ISSUE TITLE
 Unable to activate concurrent-ruby-ext-1.1.6, because concurrent-ruby-1.1.8 conflicts with concurrent-ruby (= 1.1.6)

### ISSUE THREAD

**Issue by jedrekdomanski** [SublimeLinter/SublimeLinter#1782]
I'm not sure if this is Sublime Linter issue or Rubocop issue. In my project I current use ruby 2.6.5, rubocop 0.89, concurrent-ruby 1.1.6, concurrent-ruby-ext 1.1.6 and I'm getting this error in Sublime Text console and my linter is not working. I do not have concurrent-ruby 1.1.8 installed on my machine at all.

```
SublimeLinter: WARNING: rubocop output:
Unable to activate concurrent-ruby-ext-1.1.6, because concurrent-ruby-1.1.8 conflicts with concurrent-ruby (= 1.1.6)
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:2298:in `raise_if_conflicts'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1415:in `activate'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:224:in `rescue in try_activate'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:217:in `try_activate'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/utility/native_extension_loader.rb:62:in `try_load_c_extension'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/utility/native_extension_loader.rb:30:in `block in load_native_extensions'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/utility/native_extension_loader.rb:30:in `each'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/utility/native_extension_loader.rb:30:in `load_native_extensions'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/synchronization.rb:5:in `<top (required)>'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/map.rb:3:in `<top (required)>'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/activesupport-6.1.2.1/lib/active_support/inflector/inflections.rb:3:in `<top (required)>'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/activesupport-6.1.2.1/lib/active_support/inflector.rb:4:in `<top (required)>'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-rails-2.6.0/lib/rubocop-rails.rb:5:in `<top (required)>'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/config_loader_resolver.rb:11:in `each'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/config_loader.rb:43:in `load_file'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/config_loader.rb:103:in `configuration_from_file'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/config_store.rb:58:in `for_dir'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/config_store.rb:48:in `for'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/target_finder.rb:183:in `block in process_explicit_path'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/target_finder.rb:182:in `reject'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/target_finder.rb:182:in `process_explicit_path'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/target_finder.rb:37:in `block in find'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/target_finder.rb:33:in `each'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/target_finder.rb:33:in `find'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/runner.rb:69:in `find_target_files'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/runner.rb:34:in `run'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/cli/command.rb:10:in `run'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/cli/environment.rb:17:in `run'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/cli.rb:65:in `run_command'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/cli.rb:72:in `execute_runners'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/cli.rb:41:in `run'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/exe/rubocop:13:in `block in <top (required)>'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/exe/rubocop:12:in `<top (required)>'
/Users/jedrek/.rvm/gems/ruby-2.6.5/bin/rubocop:23:in `load'
/Users/jedrek/.rvm/gems/ruby-2.6.5/bin/rubocop:23:in `<main>'

[2021-02-19 14:07:49,113 - WARNING  - SublimeLinter.lint.linter] rubocop output:
Unable to activate concurrent-ruby-ext-1.1.6, because concurrent-ruby-1.1.8 conflicts with concurrent-ruby (= 1.1.6)
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:2298:in `raise_if_conflicts'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1415:in `activate'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:224:in `rescue in try_activate'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:217:in `try_activate'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/utility/native_extension_loader.rb:62:in `try_load_c_extension'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/utility/native_extension_loader.rb:30:in `block in load_native_extensions'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/utility/native_extension_loader.rb:30:in `each'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/utility/native_extension_loader.rb:30:in `load_native_extensions'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/synchronization.rb:5:in `<top (required)>'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/map.rb:3:in `<top (required)>'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/activesupport-6.1.2.1/lib/active_support/inflector/inflections.rb:3:in `<top (required)>'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/activesupport-6.1.2.1/lib/active_support/inflector.rb:4:in `<top (required)>'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-rails-2.6.0/lib/rubocop-rails.rb:5:in `<top (required)>'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/config_loader_resolver.rb:11:in `each'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/config_loader.rb:43:in `load_file'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/config_loader.rb:103:in `configuration_from_file'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/config_store.rb:58:in `for_dir'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/config_store.rb:48:in `for'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/target_finder.rb:183:in `block in process_explicit_path'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/target_finder.rb:182:in `reject'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/target_finder.rb:182:in `process_explicit_path'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/target_finder.rb:37:in `block in find'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/target_finder.rb:33:in `each'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/target_finder.rb:33:in `find'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/runner.rb:69:in `find_target_files'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/runner.rb:34:in `run'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/cli/command.rb:10:in `run'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/cli/environment.rb:17:in `run'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/cli.rb:65:in `run_command'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/cli.rb:72:in `execute_runners'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/lib/rubocop/cli.rb:41:in `run'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/exe/rubocop:13:in `block in <top (required)>'
/Users/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/rubocop-0.89.0/exe/rubocop:12:in `<top (required)>'
/Users/jedrek/.rvm/gems/ruby-2.6.5/bin/rubocop:23:in `load'
/Users/jedrek/.rvm/gems/ruby-2.6.5/bin/rubocop:23:in `<main>'
```

**Comment by kaste** [comment]
Okay that's confusing for a non-ruby user. *grin* 

You *have* concurrent-ruby 1.1.8 installed as it says so in the stack trace

```
/Users/jedrek/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/...
```

So seeing `rvm` you have a complex setup on your machine where you can run probably multiple different rubies, selecting between them per run or project or so.  

*Usually* this is a problem of the environment the Sublime process is running.  The simplest test for this is to close all Sublime, and then to restart it from a terminal where everything is setup as you want it using * subl .*.  The Sublime process will then inherit the enviroment from your Terminal, and when we run rubocop we will inherit the process from Sublime and so on.

**Comment by jedrekdomanski** [comment]
@kaste You were right. I uninstalled versions 1.1.8 and 1.1.7 and it started to work.
