### ISSUE TITLE
Packages/SublimeLinter/resources/settings-schema.json not found

### ISSUE THREAD

**Issue by slifin** [SublimeLinter/SublimeLinter#1811]
```
reloading python 3.3 plugin SublimeLinter.sublime_linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 400, in load_module
    m.plugin_loaded()
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/sublime_linter.py", line 61, in plugin_loaded
    persist.settings.load()
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 23, in load
    self.on_update()
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 77, in on_update
    validate_global_settings()
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 89, in validate_global_settings
    return validate_settings(get_settings_objects())
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 95, in validate_settings
    schema = util.load_json(schema_file, from_sl_dir=True)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 316, in load_json
    return sublime.decode_value(sublime.load_resource(full_path))
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 435, in load_resource
    raise IOError('resource "%s" not found' % name)
OSError: resource "Packages/SublimeLinter/resources/settings-schema.json" not found
reloading settings Packages/User/Package Control.sublime-settings
Traceback (most recent call last):
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 77, in on_update
    validate_global_settings()
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 89, in validate_global_settings
    return validate_settings(get_settings_objects())
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 95, in validate_settings
    schema = util.load_json(schema_file, from_sl_dir=True)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 316, in load_json
    return sublime.decode_value(sublime.load_resource(full_path))
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 435, in load_resource
    raise IOError('resource "%s" not found' % name)
OSError: resource "Packages/SublimeLinter/resources/settings-schema.json" not found
generating meta info summary
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 459, in synthesize_on_activated_async
    el.on_activated_async(v)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 190, in exception_handler
    return event_handler(*args)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/status_bar_view.py", line 45, in on_activated_async
    draw(**State)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/status_bar_view.py", line 68, in draw
    message = messages_under_cursor(active_view, current_pos)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/status_bar_view.py", line 85, in messages_under_cursor
    for error in get_errors_under_cursor(view.buffer_id(), current_pos)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/status_bar_view.py", line 94, in get_errors_under_cursor
    error for error in persist.errors.get(bid, [])
AttributeError: 'module' object has no attribute 'errors'
Exception in thread Thread-36:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 1142, in run
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/sublime_linter.py", line 284, in lint
    linters = get_linters_for_view(view)
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/sublime_linter.py", line 432, in get_linters_for_view
    current_linters = persist.view_linters.get(bid, [])
AttributeError: 'module' object has no attribute 'view_linters'
```

**Comment by slifin** [comment]
I brought an upgrade license for sublime text 4 then restarted sublime text this issue resolved itself after that
