### ISSUE TITLE
Erroring in `split_match`: 

### ISSUE THREAD

**Issue by Jimbly** [SublimeLinter/SublimeLinter#1827]
Appears likely to be caused by this change: https://github.com/SublimeLinter/SublimeLinter/commit/0605874732a02d5d8cb198df030f86b448c05bd9

Full call stack:
```
SublimeLinter: ERROR: Unhandled exception:
Traceback (most recent call last):
  File "SublimeLinter.sublime-package\lint/backend.py", line 158, in execute_lint_task
    errors = linter.lint(code, view_has_changed)
  File "SublimeLinter.sublime-package\lint/linter.py", line 1162, in lint
    return self.filter_errors(self.parse_output(output, virtual_view))
  File "SublimeLinter.sublime-package\lint/linter.py", line 1188, in filter_errors
    for error in errors
  File "SublimeLinter.sublime-package\lint/linter.py", line 1187, in <listcomp>
    error
  File "SublimeLinter.sublime-package\lint/linter.py", line 1228, in parse_output_via_regex
    for m in self.find_errors(output):
  File "SublimeLinter.sublime-package\lint/linter.py", line 1275, in find_errors
    yield self.split_match(match)
  File "SublimeLinter-contrib-glsl-jimbly\linter.py", line 33, in split_match
    ret = super().split_match(self, match)
  File "SublimeLinter.sublime-package\lint/linter.py", line 1303, in split_match
    error['line'] = self.apply_line_base(error.get('line'))
TypeError: apply_line_base() missing 1 required positional argument: 'val'
```

It appears that maybe now any linter who's regex does not always capture a `line`, `end_line` and `end_col` will generate this error (previously it would leave them empty or something)?  Maybe only if the linter calls `super().split_match`?

The linter in question is as follows:
```python
from SublimeLinter.lint import Linter, util

class GLSLLint(Linter):
    """Provides an interface to glslangValidator."""
    defaults = {
      'selector': 'source.glsl,source.essl,source.GLSL'
    }
    cmd = ('glslangValidator', '-', '${file}')
    regex = (r'^ERROR:(?P<message>(?:\s.*:(?P<line>\d+):\s\'(?P<near>.*)\'\s:)?\s+.+)')
    error_stream = util.STREAM_BOTH

    @classmethod
    def split_match(self, match):
        ret = super().split_match(self, match)
        # If we captured no line, set it at line=0, so it still shows up as a
        #   highlight, for high-level parsing errors without line numbers
        if not ret.line:
            ret.line = 0
        return ret;
```

It could be I'm missing something, but without the `split_match` override, any errors lacking a line number (the most important ones!) get black-holed, never shown anywhere, so that was the previous fix for that issue, but now overriding split_match seems to cause this error :(.

**Comment by kaste** [comment]
`split_match` is not a `@classmethod`.  Removing the decorator should fix the issue, or at least give a different error.

**Comment by Jimbly** [comment]
Removing the `@classmethod` line and changing the call to `super().split_match(match)` seems to have fixed it, thanks!  I have no idea how any of this works in Python, sorry for my confusion and thanks for the help.
