### ISSUE TITLE
[Feature Request] add new field 'help', allow multiple strings to be appended to same field

### ISSUE THREAD

**Issue by LollipopFt** [SublimeLinter/SublimeLinter#1837]
currently, there is only 1 explanation: ```message``` module, ```found in SublimeLinter/linter.py```. this could be expanded to include ```help``` and ```note``` modules, which are seen in rust:
```
warning: value assigned to `z` is never read  <-- message field
  --> main.rs:12:5
   |
12 |     z = "hello";
   |     ^
   |
   = note: `#[warn(unused_assignments)]` on by default  <-- note field
   = help: maybe it is overwritten before being read?  <-- help field
```
furthermore, there can be 2 explanations with the same field:
```
warning: variable `z` is assigned to, but never used
  --> main.rs:10:9
   |
10 |     let z = "this is a relatively long string, to see the diff between strings and code.";
   |         ^
   |
   = note: `#[warn(unused_variables)]` on by default  <-- 2 note fields
   = note: consider using `_z` instead
```

is there a way to add additional modules like 'help' or 'note', and if not, is there a way to add multiple strings to the same module ```message```? thanks!

**Comment by kaste** [comment]
Hi! 👋 

Our stance on this is currently that you should construct a multiline `message` just the way you think it would look nice.  Like for git commit messages, the first line of the message is the subject, and the rest is the body.  The error panel should display the body out of the box with correct indentation.

**Comment by LollipopFt** [comment]
hi, thanks for replying! i'm new to writing sublimelinter plugins, so could i have a repository where they use multiline messages? for reference, this is the json i'm using:

{"message":**"variable `z` is assigned to, but never used"**,"code":{"code":"unused_variables","explanation":null},"level":"warning","spans":[{"file_name":"main.rs","byte_start":191,"byte_end":192,"line_start":8,"line_end":8,"column_start":9,"column_end":10,"is_primary":true,"text":[{"text":"    let z = \"this is a relatively long string, to see the diff between strings and code.\";","highlight_start":9,"highlight_end":10}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"**`#[warn(unused_variables)]` on by default**","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"**consider using `_z` instead**","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"warning: variable `z` is assigned to, but never used\n --> main.rs:8:9\n  |\n8 |     let z = \"this is a relatively long string, to see the diff between strings and code.\";\n  |         ^\n  |\n  = note: `#[warn(unused_variables)]` on by default\n  = note: consider using `_z` instead\n\n"}

how could i append the bolded parts using regex? i tried (?<message>) for all of them but regex does not allow multiple strings for a the message group.

**Comment by LollipopFt** [comment]
oh, i tried the preliminary regex where only the first bolded part is assigned to message. however, sublime text gives me this:
![image](https://user-images.githubusercontent.com/62802897/146212743-ecca1c0a-8e69-4027-9801-8889620a9058.png)
what does the `?` mean, and is there a way to view sublimelinter logs? opening sublime text console shows me the correct output, with a weird message:
![image](https://user-images.githubusercontent.com/62802897/146213056-fd7f70ce-6ac3-4289-b293-ced20a87cae6.png)
however, there is no help shown for the code itself:
![image](https://user-images.githubusercontent.com/62802897/146213191-c47e272d-8f54-40a5-8c97-632c6b60e532.png)

this is my ```linter.py``` file:
```python
from SublimeLinter.lint import Linter  # or NodeLinter, PythonLinter, ComposerLinter, RubyLinter


class __class__(Linter):
    cmd = ('rustc', '--error-format=json', '${file}')
    regex = r'''^{"message":"(?P<message>(?!could not emit MIR).*)","code":{"code":"(?P<code>.*)","explanation":.*},"level":"(?P<error_type>.*?)","spans":\[{.*"line_start":(?P<line>[0-9]+),"line_end":(?P<end_line>[0-9]+),"column_start":(?P<col>[0-9]+),"column_end":(?P<end_col>[0-9]+),.*"text":\[{"text":"(?P<near>.*)","highlight_start".*$'''
    multiline = True
    defaults = {
        'selector': 'source.rust'
    }
    name = 'rustc'
```
does anyone know why my package is not outputting anything? thanks!

**Comment by kaste** [comment]
You should not parse json with a regex.  Take a look at https://github.com/SublimeLinter/SublimeLinter-hlint/blob/master/linter.py 

Your class also has no good name.  You can turn on debugging in the SublimeLinter settings.

**Comment by LollipopFt** [comment]
hi, i tried to edit it, check out my repository [here](https://github.com/LollipopFt/SublimeLinter-contrib-rustc.git). however, this exact code produced this output:
```python
SublimeLinter: #2 __init__.py:1273    ERROR: Unhandled exception:
Traceback (most recent call last):
  File "C:\Users\lollipopft\sublimetext\Data\Installed Packages\SublimeLinter.sublime-package\lint/backend.py", line 164, in execute_lint_task
    errors = linter.lint(code, view_has_changed)
  File "C:\Users\lollipopft\sublimetext\Data\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1162, in lint
    return self.filter_errors(self.parse_output(output, virtual_view))
  File "C:\Users\lollipopft\sublimetext\Data\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1188, in filter_errors
    for error in errors
  File "C:\Users\lollipopft\sublimetext\Data\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1187, in <listcomp>
    error
  File "C:\Users\lollipopft\sublimetext\Data\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1228, in parse_output_via_regex
    for m in self.find_errors(output):
  File "C:\Users\lollipopft\sublimetext\Data\Installed Packages\SublimeLinter-contrib-rustc.sublime-package\linter.py", line 19, in find_errors
    yield LintMatch(
IndexError: list index out of range
SublimeLinter: sublime_linter.py:593  Linting 'main.rs' took 0.24s
```

this is the json i'm parsing:
```json
{"message":"variable `z` is assigned to, but never used","code":{"code":"unused_variables","explanation":null},"level":"warning","spans":[{"file_name":"main.rs","byte_start":191,"byte_end":192,"line_start":8,"line_end":8,"column_start":9,"column_end":10,"is_primary":true,"text":[{"text":"    let z = \"this is a relatively long string, to see the diff between strings and code.\";","highlight_start":9,"highlight_end":10}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"`#[warn(unused_variables)]` on by default","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"consider using `_z` instead","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"warning: variable `z` is assigned to, but never used\n --> main.rs:8:9\n  |\n8 |     let z = \"this is a relatively long string, to see the diff between strings and code.\";\n  |         ^\n  |\n  = note: `#[warn(unused_variables)]` on by default\n  = note: consider using `_z` instead\n\n"}
{"message":"unused variable: `a`","code":{"code":"unused_variables","explanation":null},"level":"warning","spans":[{"file_name":"main.rs","byte_start":282,"byte_end":283,"line_start":9,"line_end":9,"column_start":9,"column_end":10,"is_primary":true,"text":[{"text":"    let a = \"test\";","highlight_start":9,"highlight_end":10}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"if this is intentional, prefix it with an underscore","code":null,"level":"help","spans":[{"file_name":"main.rs","byte_start":282,"byte_end":283,"line_start":9,"line_end":9,"column_start":9,"column_end":10,"is_primary":true,"text":[{"text":"    let a = \"test\";","highlight_start":9,"highlight_end":10}],"label":null,"suggested_replacement":"_a","suggestion_applicability":"MachineApplicable","expansion":null}],"children":[],"rendered":null}],"rendered":"warning: unused variable: `a`\n --> main.rs:9:9\n  |\n9 |     let a = \"test\";\n  |         ^ help: if this is intentional, prefix it with an underscore: `_a`\n\n"}
{"message":"value assigned to `z` is never read","code":{"code":"unused_assignments","explanation":null},"level":"warning","spans":[{"file_name":"main.rs","byte_start":298,"byte_end":299,"line_start":10,"line_end":10,"column_start":5,"column_end":6,"is_primary":true,"text":[{"text":"    z = \"hello\";","highlight_start":5,"highlight_end":6}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"`#[warn(unused_assignments)]` on by default","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"maybe it is overwritten before being read?","code":null,"level":"help","spans":[],"children":[],"rendered":null}],"rendered":"warning: value assigned to `z` is never read\n  --> main.rs:10:5\n   |\n10 |     z = \"hello\";\n   |     ^\n   |\n   = note: `#[warn(unused_assignments)]` on by default\n   = help: maybe it is overwritten before being read?\n\n"}
{"message":"cannot assign twice to immutable variable `z`","code":{"code":"E0384","explanation":"An immutable variable was reassigned.\n\nErroneous code example:\n\n```compile_fail,E0384\nfn main() {\n    let x = 3;\n    x = 5; // error, reassignment of immutable variable\n}\n```\n\nBy default, variables in Rust are immutable. To fix this error, add the keyword\n`mut` after the keyword `let` when declaring the variable. For example:\n\n```\nfn main() {\n    let mut x = 3;\n    x = 5;\n}\n```\n"},"level":"error","spans":[{"file_name":"main.rs","byte_start":191,"byte_end":192,"line_start":8,"line_end":8,"column_start":9,"column_end":10,"is_primary":false,"text":[{"text":"    let z = \"this is a relatively long string, to see the diff between strings and code.\";","highlight_start":9,"highlight_end":10}],"label":"first assignment to `z`","suggested_replacement":null,"suggestion_applicability":null,"expansion":null},{"file_name":"main.rs","byte_start":298,"byte_end":309,"line_start":10,"line_end":10,"column_start":5,"column_end":16,"is_primary":true,"text":[{"text":"    z = \"hello\";","highlight_start":5,"highlight_end":16}],"label":"cannot assign twice to immutable variable","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"consider making this binding mutable","code":null,"level":"help","spans":[{"file_name":"main.rs","byte_start":191,"byte_end":192,"line_start":8,"line_end":8,"column_start":9,"column_end":10,"is_primary":true,"text":[{"text":"    let z = \"this is a relatively long string, to see the diff between strings and code.\";","highlight_start":9,"highlight_end":10}],"label":null,"suggested_replacement":"mut z","suggestion_applicability":"MachineApplicable","expansion":null}],"children":[],"rendered":null}],"rendered":"error[E0384]: cannot assign twice to immutable variable `z`\n  --> main.rs:10:5\n   |\n8  |     let z = \"this is a relatively long string, to see the diff between strings and code.\";\n   |         -\n   |         |\n   |         first assignment to `z`\n   |         help: consider making this binding mutable: `mut z`\n9  |     let a = \"test\";\n10 |     z = \"hello\";\n   |     ^^^^^^^^^^^ cannot assign twice to immutable variable\n\n"}
{"message":"aborting due to previous error; 3 warnings emitted","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to previous error; 3 warnings emitted\n\n"}
{"message":"For more information about this error, try `rustc --explain E0384`.","code":null,"level":"failure-note","spans":[],"children":[],"rendered":"For more information about this error, try `rustc --explain E0384`.\n"}
```

sorry if it's long, i just can't get it to work...

**Comment by kaste** [comment]
`spans` is sometimes empty hence `spans[0]`would throw.

**Comment by LollipopFt** [comment]
oh, in that case, how am i supposed to access the other variables?

**Comment by kaste** [comment]
That's beyond of what I can help you with.  But probably just skip the error if has no `spans`, 🤔 ?

**Comment by LollipopFt** [comment]
hmmm... ok, thanks!

**Comment by LollipopFt** [comment]
hi, there is now a working version of this, with one minor problem:
![image](https://user-images.githubusercontent.com/62802897/146637378-2d7e551a-ef69-462d-9187-3edbdf047e99.png)
the lint is one line and one column more. setting ```line_col_base = (0, 0)``` did not help, there was no change with ```(1, 1)```. may i know how this could be fixed? code is in the [repository](https://github.com/LollipopFt/SublimeLinter-contrib-rustc.git).

**Comment by kaste** [comment]
Ah.  `line_col_base` is only used for regex based linters.  You have to adjust manually.  

Btw no need to set `near` as you're already telling the exact span with end line and column.  In that case `near` is not used.  

If I understand the output correctly, `spans` can point to multiple locations.  For one of them `is_primary` is set, probably indicating you should mainly show and use this one. 🤷‍♀️

**Comment by LollipopFt** [comment]
oh, this worked, thank you! i think i would just leave ```near``` in, to cover everything. and yes, ```spans``` can point to multiple locations, but from error logs the first one is always ```is_primary``` which makes it convenient for me to just do ```'spans'[0]```. thanks for all the help given!
