### ISSUE TITLE
how to get filepath in if statement?

### ISSUE THREAD

**Issue by LollipopFt** [SublimeLinter/SublimeLinter#1838]
hi, i have a plugin that gets a json output and uses it to lint. however, one of the caveats is that the file name must match. how do i do that in an if statement if ```${file}``` can only be used in command line?
for reference, code is [here](https://github.com/LollipopFt/SublimeLinter-contrib-rustc.git).
<details><summary>snippet of code:</summary>

```
for i in error['spans']:
            if i['file_name'] == '${file}':
                yield LintMatch(
                    line = i['line_start']-1,
                    end_line = i['line_end']-1,
                    message = long_message,
                    col = i['column_start']-1,
                    end_col = i['column_end']-1,
                    error_type = error['level'],
                    near = i['text'][0]['text'],
                    code = code,
                    filename = i['file_name']
                )
            else:
                continue
```

**Comment by kaste** [comment]
`self.context.get('file')` iirc.  

I actually don't think "spans" represent errors in this case.  I think each line represents one error, and "spans" are things to underline and highlight related to this error.  And `is_primary` is basically the anchor.  

Generally, a linter can report errors from multiple files; SublimeLinter should keep them separate.  What is the actual problem here?

**Comment by LollipopFt** [comment]
well, for instance, in a `'spans'` for one file, it can link to another file and have it output there. this makes it more confusing as if you look at the output, there can be 3 nested jsons within each other, within lists of each other. this makes it difficult to parse, and so i have opted to only take the `'spans'` for the main file i am working on to ease parsing. take this for example:
<details><summary>complicated json:</summary>

```json
{
  "message":"no method named `write_fmt` found for struct `BufWriter` in the current scope",
  "code":
  {
    "code":"E0599",
    "explanation":"This error occurs when a method is used on a type which doesn't implement it:\n\nErroneous code example:\n\n```compile_fail,E0599\nstruct Mouth;\n\nlet x = Mouth;\nx.chocolate(); // error: no method named `chocolate` found for type `Mouth`\n               //        in the current scope\n```\n\nIn this case, you need to implement the `chocolate` method to fix the error:\n\n```\nstruct Mouth;\n\nimpl Mouth {\n    fn chocolate(&self) { // We implement the `chocolate` method here.\n        println!(\"Hmmm! I love chocolate!\");\n    }\n}\n\nlet x = Mouth;\nx.chocolate(); // ok!\n```\n"
  },
  "level":"error",
  "spans":
  [{
    "file_name":"C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\core\\src\\macros\\mod.rs",
    "byte_start":18741,"byte_end":18750,"line_start":534,"line_end":534,"column_start":14,"column_end":23,"is_primary":true,
    "text":
    [{
      "text":"        $dst.write_fmt($crate::format_args_nl!($($arg)*))", "highlight_start":14,"highlight_end":23
    }],
    "label":"method not found in `BufWriter<Stdout>`","suggested_replacement":null,"suggestion_applicability":null,
    "expansion":
    {
      "span":
      {
        "file_name":"sqstr.rs","byte_start":843,"byte_end":866,"line_start":21,"line_end":21,"column_start":17,"column_end":40,
        "is_primary":false,
        "text":
        [{
          "text":"                writeln!(handle, \"YES\").ok();","highlight_start":17,"highlight_end":40
        }],
        "label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null
      },
      "macro_decl_name":"writeln!",
      "def_site_span":
      {
        "file_name":"C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\core\\src\\macros\\mod.rs",
        "byte_start":18602,"byte_end":18794,"line_start":529,"line_end":536,"column_start":1,"column_end":2,"is_primary":false,
        "text":
        [
          {"text":"macro_rules! writeln {","highlight_start":1,"highlight_end":1},
          {"text":"    ($dst:expr $(,)?) => (","highlight_start":1,"highlight_end":1},
          {"text":"        $crate::write!($dst, \"\\n\")","highlight_start":1,"highlight_end":1},
          {"text":"    );","highlight_start":1,"highlight_end":1},
          {"text":"    ($dst:expr, $($arg:tt)*) => (","highlight_start":1,"highlight_end":1},
          {"text":"        $dst.write_fmt($crate::format_args_nl!($($arg)*))","highlight_start":1,"highlight_end":1},
          {"text":"    );","highlight_start":1,"highlight_end":1},
          {"text":"}","highlight_start":1,"highlight_end":2}
        ],
        "label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null
      }
    }
  },
  {
    "file_name":"C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\std\\src\\io\\mod.rs",
    "byte_start":56777,"byte_end":56786,"line_start":1675,"line_end":1675,"column_start":8,"column_end":17,"is_primary":false,
    "text":
    [{
      "text":"    fn write_fmt(&mut self, fmt: fmt::Arguments<'_>) -> Result<()> {","highlight_start":8,"highlight_end":17
    }],
    "label":"the method is available for `BufWriter<Stdout>` here","suggested_replacement":null,"suggestion_applicability":null,
    "expansion":null
  }],
  "children":
  [{
    "message":"items from traits can only be used if the trait is in scope","code":null,"level":"help","spans":[],
    "children":[],"rendered":null
  },
  {
    "message":"the following trait is implemented but not in scope; perhaps add a `use` for it:","code":null,"level":"help",
    "spans":
    [{
      "file_name":"sqstr.rs","byte_start":0,"byte_end":0,"line_start":1,"line_end":1,"column_start":1,"column_end":1,"is_primary":true,
      "text":[],"label":null,"suggested_replacement":"use std::io::Write;\n\n",
      "suggestion_applicability":"MaybeIncorrect","expansion":null
    }],
    "children":[],"rendered":null
  }],
  "rendered":"error[E0599]: no method named `write_fmt` found for struct `BufWriter` in the current scope\n    --> sqstr.rs:21:17\n     |\n21   |                 writeln!(handle, \"YES\").ok();\n     |                 ^^^^^^^^^^^^^^^^^^^^^^^ method not found in `BufWriter<Stdout>`\n     |\n    ::: C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\std\\src\\io\\mod.rs:1675:8\n     |\n1675 |     fn write_fmt(&mut self, fmt: fmt::Arguments<'_>) -> Result<()> {\n     |        --------- the method is available for `BufWriter<Stdout>` here\n     |\n     = help: items from traits can only be used if the trait is in scope\n     = note: this error originates in the macro `writeln` (in Nightly builds, run with -Z macro-backtrace for more info)\nhelp: the following trait is implemented but not in scope; perhaps add a `use` for it:\n     |\n1    | use std::io::Write;\n     |\n\n"
}
```

i parsed this by hand, so it may be wrong. anyway, what i want to get is `spans` `->` `children` `->` `spans` `->` check for `file_name`, in this case the file i am working on, `sqstr.rs`, then get `suggested_replacement`, `line_start`, `column_start`, etc. this will be so hard to get as there can be so many paths i can parse, especially since `spans` and `children` are both lists that can contain more of this nonsense, and just makes it so hard to get a proper lint. this is only one of the many strings split with `.split('\n')` and parsed individually as json. thus i hope to use the filename to narrow down the possibilities, at the cost of less linting.
</details>

**Comment by LollipopFt** [comment]
i have an error message:
```json
SublimeLinter: #8 linter.py:1226      rustc: output:
  {"message":"no method named `write_fmt` found for struct `BufWriter` in the current scope","code":{"code":"E0599","explanation":"This error occurs when a method is used on a type which doesn't implement it:\n\nErroneous code example:\n\n```compile_fail,E0599\nstruct Mouth;\n\nlet x = Mouth;\nx.chocolate(); // error: no method named `chocolate` found for type `Mouth`\n               //        in the current scope\n```\n\nIn this case, you need to implement the `chocolate` method to fix the error:\n\n```\nstruct Mouth;\n\nimpl Mouth {\n    fn chocolate(&self) { // We implement the `chocolate` method here.\n        println!(\"Hmmm! I love chocolate!\");\n    }\n}\n\nlet x = Mouth;\nx.chocolate(); // ok!\n```\n"},"level":"error","spans":[{"file_name":"C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\core\\src\\macros\\mod.rs","byte_start":18741,"byte_end":18750,"line_start":534,"line_end":534,"column_start":14,"column_end":23,"is_primary":true,"text":[{"text":"        $dst.write_fmt($crate::format_args_nl!($($arg)*))","highlight_start":14,"highlight_end":23}],"label":"method not found in `BufWriter<Stdout>`","suggested_replacement":null,"suggestion_applicability":null,"expansion":{"span":{"file_name":"C:\\Users\\lollipopft\\rust\\projects\\codeforces\\round_762\\sqstr.rs","byte_start":843,"byte_end":866,"line_start":21,"line_end":21,"column_start":17,"column_end":40,"is_primary":false,"text":[{"text":"                writeln!(handle, \"YES\").ok();","highlight_start":17,"highlight_end":40}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null},"macro_decl_name":"writeln!","def_site_span":{"file_name":"C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\core\\src\\macros\\mod.rs","byte_start":18602,"byte_end":18794,"line_start":529,"line_end":536,"column_start":1,"column_end":2,"is_primary":false,"text":[{"text":"macro_rules! writeln {","highlight_start":1,"highlight_end":1},{"text":"    ($dst:expr $(,)?) => (","highlight_start":1,"highlight_end":1},{"text":"        $crate::write!($dst, \"\\n\")","highlight_start":1,"highlight_end":1},{"text":"    );","highlight_start":1,"highlight_end":1},{"text":"    ($dst:expr, $($arg:tt)*) => (","highlight_start":1,"highlight_end":1},{"text":"        $dst.write_fmt($crate::format_args_nl!($($arg)*))","highlight_start":1,"highlight_end":1},{"text":"    );","highlight_start":1,"highlight_end":1},{"text":"}","highlight_start":1,"highlight_end":2}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}}},{"file_name":"C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\std\\src\\io\\mod.rs","byte_start":56777,"byte_end":56786,"line_start":1675,"line_end":1675,"column_start":8,"column_end":17,"is_primary":false,"text":[{"text":"    fn write_fmt(&mut self, fmt: fmt::Arguments<'_>) -> Result<()> {","highlight_start":8,"highlight_end":17}],"label":"the method is available for `BufWriter<Stdout>` here","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"items from traits can only be used if the trait is in scope","code":null,"level":"help","spans":[],"children":[],"rendered":null},{"message":"the following trait is implemented but not in scope; perhaps add a `use` for it:","code":null,"level":"help","spans":[{"file_name":"C:\\Users\\lollipopft\\rust\\projects\\codeforces\\round_762\\sqstr.rs","byte_start":0,"byte_end":0,"line_start":1,"line_end":1,"column_start":1,"column_end":1,"is_primary":true,"text":[],"label":null,"suggested_replacement":"use std::io::Write;\n\n","suggestion_applicability":"MaybeIncorrect","expansion":null}],"children":[],"rendered":null}],"rendered":"error[E0599]: no method named `write_fmt` found for struct `BufWriter` in the current scope\n    --> C:\\Users\\lollipopft\\rust\\projects\\codeforces\\round_762\\sqstr.rs:21:17\n     |\n21   |                 writeln!(handle, \"YES\").ok();\n     |                 ^^^^^^^^^^^^^^^^^^^^^^^ method not found in `BufWriter<Stdout>`\n     |\n    ::: C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\std\\src\\io\\mod.rs:1675:8\n     |\n1675 |     fn write_fmt(&mut self, fmt: fmt::Arguments<'_>) -> Result<()> {\n     |        --------- the method is available for `BufWriter<Stdout>` here\n     |\n     = help: items from traits can only be used if the trait is in scope\n     = note: this error originates in the macro `writeln` (in Nightly builds, run with -Z macro-backtrace for more info)\nhelp: the following trait is implemented but not in scope; perhaps add a `use` for it:\n     |\n1    | use std::io::Write;\n     |\n\n"}
  {"message":"no method named `write_fmt` found for struct `BufWriter` in the current scope","code":{"code":"E0599","explanation":"This error occurs when a method is used on a type which doesn't implement it:\n\nErroneous code example:\n\n```compile_fail,E0599\nstruct Mouth;\n\nlet x = Mouth;\nx.chocolate(); // error: no method named `chocolate` found for type `Mouth`\n               //        in the current scope\n```\n\nIn this case, you need to implement the `chocolate` method to fix the error:\n\n```\nstruct Mouth;\n\nimpl Mouth {\n    fn chocolate(&self) { // We implement the `chocolate` method here.\n        println!(\"Hmmm! I love chocolate!\");\n    }\n}\n\nlet x = Mouth;\nx.chocolate(); // ok!\n```\n"},"level":"error","spans":[{"file_name":"C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\core\\src\\macros\\mod.rs","byte_start":18741,"byte_end":18750,"line_start":534,"line_end":534,"column_start":14,"column_end":23,"is_primary":true,"text":[{"text":"        $dst.write_fmt($crate::format_args_nl!($($arg)*))","highlight_start":14,"highlight_end":23}],"label":"method not found in `BufWriter<Stdout>`","suggested_replacement":null,"suggestion_applicability":null,"expansion":{"span":{"file_name":"C:\\Users\\lollipopft\\rust\\projects\\codeforces\\round_762\\sqstr.rs","byte_start":912,"byte_end":934,"line_start":23,"line_end":23,"column_start":17,"column_end":39,"is_primary":false,"text":[{"text":"                writeln!(handle, \"NO\").ok();","highlight_start":17,"highlight_end":39}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null},"macro_decl_name":"writeln!","def_site_span":{"file_name":"C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\core\\src\\macros\\mod.rs","byte_start":18602,"byte_end":18794,"line_start":529,"line_end":536,"column_start":1,"column_end":2,"is_primary":false,"text":[{"text":"macro_rules! writeln {","highlight_start":1,"highlight_end":23},{"text":"    ($dst:expr $(,)?) => (","highlight_start":1,"highlight_end":27},{"text":"        $crate::write!($dst, \"\\n\")","highlight_start":1,"highlight_end":35},{"text":"    );","highlight_start":1,"highlight_end":7},{"text":"    ($dst:expr, $($arg:tt)*) => (","highlight_start":1,"highlight_end":34},{"text":"        $dst.write_fmt($crate::format_args_nl!($($arg)*))","highlight_start":1,"highlight_end":58},{"text":"    );","highlight_start":1,"highlight_end":7},{"text":"}","highlight_start":1,"highlight_end":2}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}}},{"file_name":"C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\std\\src\\io\\mod.rs","byte_start":56777,"byte_end":56786,"line_start":1675,"line_end":1675,"column_start":8,"column_end":17,"is_primary":false,"text":[{"text":"    fn write_fmt(&mut self, fmt: fmt::Arguments<'_>) -> Result<()> {","highlight_start":8,"highlight_end":17}],"label":"the method is available for `BufWriter<Stdout>` here","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"items from traits can only be used if the trait is in scope","code":null,"level":"help","spans":[],"children":[],"rendered":null},{"message":"the following trait is implemented but not in scope; perhaps add a `use` for it:","code":null,"level":"help","spans":[{"file_name":"C:\\Users\\lollipopft\\rust\\projects\\codeforces\\round_762\\sqstr.rs","byte_start":0,"byte_end":0,"line_start":1,"line_end":1,"column_start":1,"column_end":1,"is_primary":true,"text":[],"label":null,"suggested_replacement":"use std::io::Write;\n\n","suggestion_applicability":"MaybeIncorrect","expansion":null}],"children":[],"rendered":null}],"rendered":"error[E0599]: no method named `write_fmt` found for struct `BufWriter` in the current scope\n    --> C:\\Users\\lollipopft\\rust\\projects\\codeforces\\round_762\\sqstr.rs:23:17\n     |\n23   |                 writeln!(handle, \"NO\").ok();\n     |                 ^^^^^^^^^^^^^^^^^^^^^^ method not found in `BufWriter<Stdout>`\n     |\n    ::: C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\std\\src\\io\\mod.rs:1675:8\n     |\n1675 |     fn write_fmt(&mut self, fmt: fmt::Arguments<'_>) -> Result<()> {\n     |        --------- the method is available for `BufWriter<Stdout>` here\n     |\n     = help: items from traits can only be used if the trait is in scope\n     = note: this error originates in the macro `writeln` (in Nightly builds, run with -Z macro-backtrace for more info)\nhelp: the following trait is implemented but not in scope; perhaps add a `use` for it:\n     |\n1    | use std::io::Write;\n     |\n\n"}
  {"message":"no method named `write_fmt` found for struct `BufWriter` in the current scope","code":{"code":"E0599","explanation":"This error occurs when a method is used on a type which doesn't implement it:\n\nErroneous code example:\n\n```compile_fail,E0599\nstruct Mouth;\n\nlet x = Mouth;\nx.chocolate(); // error: no method named `chocolate` found for type `Mouth`\n               //        in the current scope\n```\n\nIn this case, you need to implement the `chocolate` method to fix the error:\n\n```\nstruct Mouth;\n\nimpl Mouth {\n    fn chocolate(&self) { // We implement the `chocolate` method here.\n        println!(\"Hmmm! I love chocolate!\");\n    }\n}\n\nlet x = Mouth;\nx.chocolate(); // ok!\n```\n"},"level":"error","spans":[{"file_name":"C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\core\\src\\macros\\mod.rs","byte_start":18741,"byte_end":18750,"line_start":534,"line_end":534,"column_start":14,"column_end":23,"is_primary":true,"text":[{"text":"        $dst.write_fmt($crate::format_args_nl!($($arg)*))","highlight_start":14,"highlight_end":23}],"label":"method not found in `BufWriter<Stdout>`","suggested_replacement":null,"suggestion_applicability":null,"expansion":{"span":{"file_name":"C:\\Users\\lollipopft\\rust\\projects\\codeforces\\round_762\\sqstr.rs","byte_start":987,"byte_end":1009,"line_start":26,"line_end":26,"column_start":13,"column_end":35,"is_primary":false,"text":[{"text":"            writeln!(handle, \"NO\").ok();","highlight_start":13,"highlight_end":35}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null},"macro_decl_name":"writeln!","def_site_span":{"file_name":"C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\core\\src\\macros\\mod.rs","byte_start":18602,"byte_end":18794,"line_start":529,"line_end":536,"column_start":1,"column_end":2,"is_primary":false,"text":[{"text":"macro_rules! writeln {","highlight_start":1,"highlight_end":23},{"text":"    ($dst:expr $(,)?) => (","highlight_start":1,"highlight_end":27},{"text":"        $crate::write!($dst, \"\\n\")","highlight_start":1,"highlight_end":35},{"text":"    );","highlight_start":1,"highlight_end":7},{"text":"    ($dst:expr, $($arg:tt)*) => (","highlight_start":1,"highlight_end":34},{"text":"        $dst.write_fmt($crate::format_args_nl!($($arg)*))","highlight_start":1,"highlight_end":58},{"text":"    );","highlight_start":1,"highlight_end":7},{"text":"}","highlight_start":1,"highlight_end":2}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}}},{"file_name":"C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\std\\src\\io\\mod.rs","byte_start":56777,"byte_end":56786,"line_start":1675,"line_end":1675,"column_start":8,"column_end":17,"is_primary":false,"text":[{"text":"    fn write_fmt(&mut self, fmt: fmt::Arguments<'_>) -> Result<()> {","highlight_start":8,"highlight_end":17}],"label":"the method is available for `BufWriter<Stdout>` here","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"items from traits can only be used if the trait is in scope","code":null,"level":"help","spans":[],"children":[],"rendered":null},{"message":"the following trait is implemented but not in scope; perhaps add a `use` for it:","code":null,"level":"help","spans":[{"file_name":"C:\\Users\\lollipopft\\rust\\projects\\codeforces\\round_762\\sqstr.rs","byte_start":0,"byte_end":0,"line_start":1,"line_end":1,"column_start":1,"column_end":1,"is_primary":true,"text":[],"label":null,"suggested_replacement":"use std::io::Write;\n\n","suggestion_applicability":"MaybeIncorrect","expansion":null}],"children":[],"rendered":null}],"rendered":"error[E0599]: no method named `write_fmt` found for struct `BufWriter` in the current scope\n    --> C:\\Users\\lollipopft\\rust\\projects\\codeforces\\round_762\\sqstr.rs:26:13\n     |\n26   |             writeln!(handle, \"NO\").ok();\n     |             ^^^^^^^^^^^^^^^^^^^^^^ method not found in `BufWriter<Stdout>`\n     |\n    ::: C:\\Users\\lollipopft\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\std\\src\\io\\mod.rs:1675:8\n     |\n1675 |     fn write_fmt(&mut self, fmt: fmt::Arguments<'_>) -> Result<()> {\n     |        --------- the method is available for `BufWriter<Stdout>` here\n     |\n     = help: items from traits can only be used if the trait is in scope\n     = note: this error originates in the macro `writeln` (in Nightly builds, run with -Z macro-backtrace for more info)\nhelp: the following trait is implemented but not in scope; perhaps add a `use` for it:\n     |\n1    | use std::io::Write;\n     |\n\n"}
  {"message":"aborting due to 3 previous errors","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to 3 previous errors\n\n"}
  {"message":"For more information about this error, try `rustc --explain E0599`.","code":null,"level":"failure-note","spans":[],"children":[],"rendered":"For more information about this error, try `rustc --explain E0599`.\n"}
SublimeLinter: #8 __init__.py:1273    ERROR: Unhandled exception:
Traceback (most recent call last):
  File "C:\Users\lollipopft\sublimetext\Data\Installed Packages\SublimeLinter.sublime-package\lint/backend.py", line 164, in execute_lint_task
    errors = linter.lint(code, view_has_changed)
  File "C:\Users\lollipopft\sublimetext\Data\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1162, in lint
    return self.filter_errors(self.parse_output(output, virtual_view))
  File "C:\Users\lollipopft\sublimetext\Data\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1188, in filter_errors
    for error in errors
  File "C:\Users\lollipopft\sublimetext\Data\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1187, in <listcomp>
    error
  File "C:\Users\lollipopft\sublimetext\Data\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1228, in parse_output_via_regex
    for m in self.find_errors(output):
TypeError: 'NoneType' object is not iterable
SublimeLinter: sublime_linter.py:593  Linting 'sqstr.rs' took 0.30s
```
why do i receive `TypeError: 'NoneType' object is not iterable`?

**Comment by kaste** [comment]
Ah, whenever you call just `recurse(child)` you actually don't return anything from it.  You want `yield from recurse(child)` here.

**Comment by LollipopFt** [comment]
i see, thanks!
