### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_filename'

### ISSUE THREAD

**Issue by davidhq** [SublimeLinter/SublimeLinter#1840]
Hi, I've been recently getting these errors in SublimeText 4126:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 944, in on_activated_async
    run_view_callbacks('on_activated_async', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 708, in run_view_callbacks
    callback(v, *args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 190, in exception_handler
    return event_handler(*args)
  File "/Users/david/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/status_bar_view.py", line 58, in on_activated_async
    'active_filename': util.get_filename(active_view),
AttributeError: 'module' object has no attribute 'get_filename'
```

This line: https://github.com/SublimeLinter/SublimeLinter/blob/master/status_bar_view.py#L58

Cannot figure the solution, thank you for any tips.

**Comment by kaste** [comment]
Restart Sublime Text and look at the console output on the restart.

Maybe delete the sublime-package file to force a redownload on the next restart.

**Comment by ykqmain** [comment]
Similar problems,

SublimeText 4126
Python 3.10.1
flake8 4.0.1 (mccabe: 0.6.1, pycodestyle: 2.8.0, pyflakes: 2.4.0) CPython 3.10.1 on Darwin

```
SublimeLinter: #1 flake8 date.py ERROR:
=======================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flake8/__init__.py", line 12, in <module>
    import logging
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
  File "/Users/yang/Developer/Code/Python/Demo/re.py", line 5, in <module>
    from pathlib import Path
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 14, in <module>
    from urllib.parse import quote_from_bytes as urlquote_from_bytes
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/parse.py", line 642, in <module>
    _asciire = re.compile('([\x00-\x7f]+)')
AttributeError: partially initialized module 're' has no attribute 'compile' (most likely due to a circular import)
```

**Comment by kaste** [comment]
@ykqmain No that's just flake8, the linter itself, crashing.

**Comment by ykqmain** [comment]
> @ykqmain No that's just flake8, the linter itself, crashing.  

Thank you for your answer.

**Comment by kaste** [comment]
Closing as probably solved or outdated.
