### ISSUE TITLE
No place to put a CA Certificate

### ISSUE THREAD

**Issue by arianf** [SublimeLinter/SublimeLinter#1846]
I have a `.rubocop.yml` file that has a link out to a shared style guide for all our projects. But am unable to find a place to put a CA Cert. I tried to put a CA PEM in `Package Control.user-ca-bundle` but that didn't work.

```yaml
inherit_from:
  - https://pages.github.enterprise-website.com/my-team/style-guide/rubocop.yml
```

SublimeLinter results:
```
SublimeLinter: #2012 linter.py:1226   ruby: output:
  Syntax OK
SublimeLinter: #2012 linter.py:1266   ruby: No matches for regex: ^(?P<file>.+?):(?P<line>\d+): (?:(?P<error>.*?error)|(?P<warning>warning))[,:] (?P<message>[^\r\n]+)\r?\n(?:^[^\r\n]+\r?\n^(?P<col>.*?)\^)?
SublimeLinter: #2011 linter.py:808    WARNING: rubocop output:
SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:985:in `connect'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:909:in `start'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:1458:in `request'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/remote_config.rb:49:in `block in request'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/remote_config.rb:61:in `generate_request'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/remote_config.rb:48:in `request'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/remote_config.rb:22:in `file'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/config_loader.rb:185:in `file_path'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/config_loader.rb:39:in `load_file'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/config_loader_resolver.rb:214:in `block in base_configs'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/config_loader_resolver.rb:213:in `map'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/config_loader_resolver.rb:213:in `base_configs'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/config_loader_resolver.rb:25:in `resolve_inheritance'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/config_loader.rb:51:in `load_file'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/config_loader.rb:103:in `configuration_from_file'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/config_store.rb:68:in `for_dir'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/config_store.rb:58:in `for'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/target_finder.rb:190:in `block in process_explicit_path'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/target_finder.rb:189:in `reject'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/target_finder.rb:189:in `process_explicit_path'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/target_finder.rb:40:in `block in find'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/target_finder.rb:36:in `each'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/target_finder.rb:36:in `find'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:77:in `find_target_files'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:42:in `run'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/cli/command.rb:11:in `run'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/cli/environment.rb:18:in `run'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/cli.rb:71:in `run_command'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/cli.rb:78:in `execute_runners'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/lib/rubocop/cli.rb:47:in `run'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/exe/rubocop:12:in `block in <top (required)>'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/Users/arian/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rubocop-1.23.0/exe/rubocop:12:in `<top (required)>'
/Users/arian/.rvm/gems/ruby-2.5.8@myapp/bin/rubocop:23:in `load'
/Users/arian/.rvm/gems/ruby-2.5.8@myapp/bin/rubocop:23:in `<main>'
```

**Comment by arianf** [comment]
When I run `rubocop` in console it works fine...

**Comment by kaste** [comment]
SublimeLinter runs `rubocop` as a child process of Sublime Text.  As such it (the process) inherits the environment ("ENV") of Sublime Text itself.  (For example, it does *not* use `Package Control` certificates.)  

Can it be that you have a special environment on the Terminal/console where it works fine but a different one running Sublime?  Maybe shut down Sublime Text completely, and start it from the console using `subl .`, from the correct working dir with everything set up.  Doing so Sublime should inherit the environment from the Terminal.

**Comment by kaste** [comment]
Implementing #1795 would probably solve this automatically. (?)

**Comment by kaste** [comment]
Closing as stale
