### ISSUE TITLE
Errors loading linter

### ISSUE THREAD

**Issue by corporatedigger** [SublimeLinter/SublimeLinter#1876]
Having an issue loading the linter. I see the output from the console saying no module names jsonschema, but when i yum install that, yum tells me its already installed. 

```
sudo yum install python-jsonschema
Loaded plugins: aliases, changelog, kabi, langpacks, ovl, product-id, search-disabled-repos, tmprepo, verify,
              : versionlock
Loading support for Red Hat kernel ABI
Package python2-jsonschema-2.5.1-4.el7.noarch already installed and latest version
Nothing to do
```

Error from plugin:
```
.config/sublime-text/Packages/SublimeLinter/lint/settings.py", line 6, in <module>
    from jsonschema import validate, FormatChecker, ValidationError
ImportError: No module named 'jsonschema'
```

Further errors down the console:
```
.config/sublime-text/Packages/SublimeLinter/lint/settings.py", line 4, in <module>
    from . import events, util
ImportError: cannot import name events
```

**Comment by kaste** [comment]
Have you restarted Sublime.  Watch the console from the restart on.  Maybe it couldn't download jsonschema.  We don't use your system python modules in any way so yum doesn't help here.

Is that manual install perhaps?  Then you have to call Satisfy dependencies... from the Command Palette.

**Comment by corporatedigger** [comment]
> Have you restarted Sublime. Watch the console from the restart on. Maybe it couldn't download jsonschema. We don't use your system python modules in any way so yum doesn't help here.
> 
> Is that manual install perhaps? Then you have to call Satisfy dependencies... from the Command Palette.

Yes, tried restarting sublime a multiple times, and even tried restarting my entire system. 
Yes its a manual install b.c the env I'm working in has no external network access. How I installed was just d/l the .zip file and copy the extracted file to .config/sublime_text/Packages/. 
No way to use package control as I dont even have access to a http proxy. I can only copy files from a network drive. 

Is there something special I have to do to get this working when installing manually?

**Comment by kaste** [comment]
Yeah, you would need to run `Satisfy Dependencies` command from Package Control which you can't.   You can grab a copy of jsonschema  https://github.com/kylebebak/sublime-jsonschema 

What you want is the folder inside the `all` directory.  You extract that also in "Packages".  

You don't have Package Control running at all I guess?

**Comment by corporatedigger** [comment]
> Yeah, you would need to run `Satisfy Dependencies` command from Package Control which you can't. You can grab a copy of jsonschema https://github.com/kylebebak/sublime-jsonschema
> 
> What you want is the folder inside the `all` directory. You extract that also in "Packages".
> 
> You don't have Package Control running at all I guess?

Okay this is looking like progress! Moving the "jsonschema" folder from sublime-jsonschema>all>jsonschema to my packages now has cleared up it not being able to find the package. 

Now Im seeing another error, I'll provide the whole text dump:
```
Traceback (most recent call last):
  File "~/TOOLS/sublime_text/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "~/.config/sublime-text/Packages/jsonschema/__main__.py", line 1, in <module>
    from jsonschema.cli import main
  File "~/.config/sublime-text/Packages/jsonschema/cli.py", line 22, in <module>
    description="JSON Schema Validation CLI",
  File "./python3.3/argparse.py", line 1600, in __init__
AttributeError: 'module' object has no attribute 'argv'
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading python 3.3 plugin jsonschema._format
reloading plugin Default.indentation
reloading python 3.3 plugin jsonschema._reflect
reloading plugin Default.install_package_control
reloading python 3.3 plugin jsonschema._utils
reloading python 3.3 plugin jsonschema._validators
reloading python 3.3 plugin jsonschema._version
reloading python 3.3 plugin jsonschema.cli
Traceback (most recent call last):
  File "~/TOOLS/sublime_text/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "~/.config/sublime-text/Packages/jsonschema/cli.py", line 22, in <module>
    description="JSON Schema Validation CLI",
  File "./python3.3/argparse.py", line 1600, in __init__
AttributeError: 'module' object has no attribute 'argv'
reloading python 3.3 plugin jsonschema.compat
reloading python 3.3 plugin jsonschema.exceptions
reloading python 3.3 plugin jsonschema.validators
reloading python 3.3 plugin SublimeLinter.__init__
reloading python 3.3 plugin SublimeLinter._init
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading python 3.3 plugin SublimeLinter.active_linters_view
reloading python 3.3 plugin SublimeLinter.busy_indicator_view
reloading python 3.3 plugin SublimeLinter.goto_commands
reloading python 3.3 plugin SublimeLinter.highlight_view
reloading python 3.3 plugin SublimeLinter.log_handler
reloading python 3.3 plugin SublimeLinter.message_view
reloading python 3.3 plugin SublimeLinter.panel_view
reloading python 3.3 plugin SublimeLinter.quick_actions
reloading python 3.3 plugin SublimeLinter.status_bar_view
reloading python 3.3 plugin SublimeLinter.sublime_linter
reloading python 3.3 plugin SublimeLinter-contrib-verilator.linter
reloading python 3.3 plugin SystemVerilog.__init__
reloading python 3.3 plugin SystemVerilog.verilog_align
reloading python 3.3 plugin SystemVerilog.verilog_completion
reloading python 3.3 plugin SystemVerilog.verilog_module
reloading python 3.3 plugin SystemVerilog.verilog_navigation
plugins loaded
Traceback (most recent call last):
  File "~/TOOLS/sublime_text/Lib/python33/sublime_plugin.py", line 528, in on_api_ready
    plc()
  File "~/.config/sublime-text/Packages/SublimeLinter/sublime_linter.py", line 74, in plugin_loaded
    persist.settings.load()
  File "~/.config/sublime-text/Packages/SublimeLinter/lint/settings.py", line 24, in load
    self.on_update()
  File "~/.config/sublime-text/Packages/SublimeLinter/lint/settings.py", line 78, in on_update
    validate_global_settings()
  File "~/.config/sublime-text/Packages/SublimeLinter/lint/settings.py", line 90, in validate_global_settings
    return validate_settings(get_settings_objects())
  File "~/.config/sublime-text/Packages/SublimeLinter/lint/settings.py", line 103, in validate_settings
    validate(settings, schema, format_checker=FormatChecker())
  File "~/.config/sublime-text/Packages/jsonschema/validators.py", line 540, in validate
    cls.check_schema(schema)
  File "~/.config/sublime-text/Packages/jsonschema/validators.py", line 82, in check_schema
    for error in cls(cls.META_SCHEMA).iter_errors(schema):
  File "~/.config/sublime-text/Packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "~/.config/sublime-text/Packages/jsonschema/_validators.py", line 304, in properties_draft4
    schema_path=property,
  File "~/.config/sublime-text/Packages/jsonschema/validators.py", line 121, in descend
    for error in self.iter_errors(instance, schema):
  File "~/.config/sublime-text/Packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "~/.config/sublime-text/Packages/jsonschema/_validators.py", line 29, in additionalProperties
    for error in validator.descend(instance[extra], aP, path=extra):
  File "~/.config/sublime-text/Packages/jsonschema/validators.py", line 121, in descend
    for error in self.iter_errors(instance, schema):
  File "~/.config/sublime-text/Packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "~/.config/sublime-text/Packages/jsonschema/_validators.py", line 216, in ref
    for error in validator.descend(instance, resolved):
  File "~/.config/sublime-text/Packages/jsonschema/validators.py", line 121, in descend
    for error in self.iter_errors(instance, schema):
  File "~/.config/sublime-text/Packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "~/.config/sublime-text/Packages/jsonschema/_validators.py", line 304, in properties_draft4
    schema_path=property,
  File "~/.config/sublime-text/Packages/jsonschema/validators.py", line 121, in descend
    for error in self.iter_errors(instance, schema):
  File "~/.config/sublime-text/Packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "~/.config/sublime-text/Packages/jsonschema/_validators.py", line 364, in anyOf_draft4
    errs = list(validator.descend(instance, subschema, schema_path=index))
  File "~/.config/sublime-text/Packages/jsonschema/validators.py", line 121, in descend
    for error in self.iter_errors(instance, schema):
  File "~/.config/sublime-text/Packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "~/.config/sublime-text/Packages/jsonschema/_validators.py", line 291, in type_draft4
    yield ValidationError(_utils.types_msg(instance, types))
  File "~/.config/sublime-text/Packages/jsonschema/exceptions.py", line 30, in __init__
    super(_Error, self).__init__(
TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by kaste** [comment]
Ah shit.  Of course, it now handles jsonschema as a normal package/plugin and autoloads it.  🙄 

(Maybe you just make a full, portable install at a computer with network, and then copy-paste the complete installation with all the downloaded packages from the drive.?)

So you basically put the `jsonschema` dir somewhere, and write a short loader plugin which adds the `jsonschema` to `sys.path`.  Possible if you know python.  

From here it might be even easier to make a patch (PR) against SublimeLinter which optionally loads jsonschema because it is only used in settings.py to validate what the user typed in their settings.  (Which is not a bad thing to have, but hey)

**Comment by corporatedigger** [comment]
When you use package control where are the actual packages installed? Just want to make sure I know what to copy when I set it up on a computer with a network.

 Everything is just in the .config/sublime_text/Packages dir?

**Comment by kaste** [comment]
Closing as stale
