### ISSUE TITLE
RuntimeError since April 16th release

### ISSUE THREAD

**Issue by fschulze** [SublimeLinter/SublimeLinter#1933]
I'm getting this RuntimeError with ST build 4169 since todays 4.24.0 release:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 1105, in on_text_command
    res = callback(v, name, args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 162, in profiler
    return event_handler(*args)
  File "/Users/fschulze/Library/Application Support/Sublime Text/Installed Packages/SublimeLinter.sublime-package/highlight_view.py", line 679, in on_text_command
    restore_from_everstore(view)
  File "/Users/fschulze/Library/Application Support/Sublime Text/Installed Packages/SublimeLinter.sublime-package/lint/util.py", line 82, in wrapped
    raise RuntimeError(msg)
RuntimeError: 'restore_from_everstore' must be called from the UI thread
```

**Comment by kaste** [comment]
Have you restarted Sublime Text?

**Comment by fschulze** [comment]
Doh, I thought I did, but I only closed all windows. Thanks!
