### ISSUE TITLE
RuntimeError: 'erase_view_region' must be called from the UI thread

### ISSUE THREAD

**Issue by yaroslavyaroslav** [SublimeLinter/SublimeLinter#1937]
I got this error on a `Reload SublimeLinter and its Plugins` command run.

Here's the traceback:

```
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.__allo__
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter._init
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 256, in unload_module
    module.plugin_unloaded()
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/SublimeLinter.sublime-package/highlight_view.py", line 99, in plugin_unloaded
    undraw(view)
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/SublimeLinter.sublime-package/highlight_view.py", line 446, in undraw
    erase_view_region(view, key)
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/SublimeLinter.sublime-package/lint/util.py", line 82, in wrapped
    raise RuntimeError(msg)
RuntimeError: 'erase_view_region' must be called from the UI thread
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.quick_actions
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.vendor
reloading plugin SublimeLinter-contrib-swiftlint.linter
```

**Comment by kaste** [comment]
Oh shit, that's reproducible.

**Comment by kaste** [comment]
Let's see if 4.24.2 is better.  Thanks for reporting.
