### ISSUE TITLE
ImportError: No module named 'SublimeLinter'

### ISSUE THREAD

**Issue by moritzmoxter** [SublimeLinter/SublimeLinter#1944]
Hi,

I'm trying to build a custom linter plugin for javac with support for Maven dependencies fetched from a local `pom.xml`. Unfortunately when starting with the plugin template I get the following error:
```sh
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/tupel/.config/sublime-text/Packages/sublime-linter-javac/linter.py", line 3, in <module>
    from SublimeLinter.lint import Linter
ImportError: No module named 'SublimeLinter'
```

I have installed the `SublimeLinter` package with package control, I tried restarting Sublime, re-installing SublimeLinter and re-installing my custom plugin several times in different orders. No luck so far.

I'm running
- Sublime build 4169 (latest)
- SublimeLinter 4.24.3
- on Arch Linux

It would be great if you can give me any help,

cheers Moritz

**Comment by kaste** [comment]
Check `	"ignored_packages":` in the main (Sublime Text) Preferences.

**Comment by kaste** [comment]
No, `sublime-linter-javac` should be `SublimeLinter-javac` or rather `SublimeLinter-contrib-javac`.  The sorting matters and `sublime-` probably comes before `SublimeL`?

**Comment by moritzmoxter** [comment]
Thanks a lot, that seems to do the trick :)
