### ISSUE TITLE
version 4.26 no attribute 'get_delay'

### ISSUE THREAD

**Issue by mike-ball** [SublimeLinter/SublimeLinter#1962]
SublimeText updated my SublimeLinter to version 4.26 yesterday. Since then my Linter has been broken.
I use the SublimeLinter-rubocop package. This is the only Linter I have installed

Here are the logs in my console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 958, in on_modified_async
    run_view_callbacks('on_modified_async', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 741, in run_view_callbacks
    callback(v, *args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 202, in exception_handler
    return event_handler(*args)
  File "/Users/mikeball/Library/Application Support/Sublime Text/Installed Packages/SublimeLinter.sublime-package/lint/util.py", line 206, in wrapper
    method(self, view)
  File "/Users/mikeball/Library/Application Support/Sublime Text/Installed Packages/SublimeLinter.sublime-package/sublime_linter.py", line 167, in on_modified_async
    hit(view, 'on_modified')
  File "/Users/mikeball/Library/Application Support/Sublime Text/Installed Packages/SublimeLinter.sublime-package/sublime_linter.py", line 333, in hit
    delay = backend.get_delay() if reason == 'on_modified' else 0.0
AttributeError: module 'SublimeLinter.lint.backend' has no attribute 'get_delay'
```

**Comment by kaste** [comment]
Have you restarted Sublime Text after the update?  (As `backend clearly has that function https://github.com/SublimeLinter/SublimeLinter/blob/c7d381b316cc7ad17bbf52e25067e2fdd1b88761/lint/backend.py#L263-L263 it would look like an older version of backend to be still loaded and in control.)

Or you have a local override in the *Packages/* folder.

**Comment by mike-ball** [comment]
@kaste Thanks for the response. Sure enough restarting Sublime fixed it. I thought I had already restarted since it seemed like the last restart is when the problem started.
It is working now. Thanks!

**Comment by kaste** [comment]
💯
