### ISSUE TITLE
SyntaxError: invalid syntax on installation

### ISSUE THREAD

**Issue by cgunther** [SublimeLinter/SublimeLinter#21]
After trying to install the plugin, I'm getting the following error in the console:

```
reloading plugin SublimeLinter.SublimeLinter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "SublimeLinter in /Users/chrisgunther/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 393
    print 'SublimeLinter: {0} {1} ({2})'.format(language, 'enabled' if enabled else 'disabled', message)
                                       ^
SyntaxError: invalid syntax
```

The package control message does successfully show after installation, but this is in the console.

I'm running Sublime Text 3 Build 3047 on OS X 10.9.1.

Thanks for the package!

**Comment by hamedaghapanah** [comment]
install package Alignment  in subline is working?
