### ISSUE TITLE
ValueError: path is on mount 'D:', start on mount 'C:'

### ISSUE THREAD

**Issue by tobiasdiez** [SublimeLinter/SublimeLinter#721]
After installing [SublimeLinter-annotations](https://github.com/SublimeLinter/SublimeLinter-annotations), I get the following error in the console:
````
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "lint.queue in C:\Users\Tobias\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 47, in loop
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lint.queue in C:\Users\Tobias\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 55, in loop
  File "lint.queue in C:\Users\Tobias\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 101, in lint
  File "sublime_linter in C:\Users\Tobias\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 253, in lint
  File "lint.linter in C:\Users\Tobias\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 1002, in lint_view
  File "sublime_linter in C:\Users\Tobias\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 312, in highlight
  File "panel.panel in C:\Users\Tobias\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 116, in fill_panel
  File "panel.panel in C:\Users\Tobias\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 62, in create_path_dict
  File "panel.panel in C:\Users\Tobias\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 62, in <dictcomp>
  File "./python3.3/ntpath.py", line 564, in relpath
ValueError: path is on mount 'D:', start on mount 'C:'
````

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by tobiasdiez** [comment]
Thanks for you efforts with 4.0. I really enjoy the new features! However, the above problem (with exactly the same stack trace) still occurs in version `4.0.0-rc.9`.

**Comment by FichteFoll** [comment]
This was fixed in a later release, but it seems like Package Control doesn't pick that up. This'll need some separate investigation.

**Comment by braver** [comment]
Should be fixed now!
