### ISSUE TITLE
[beta] AttributeError: 'Daemon' object has no attribute '_callback'

### ISSUE THREAD

**Issue by mandx** [SublimeLinter/SublimeLinter#793]
I'm guessing this is happening after 3444f58fa5ede7261b7f8a8356bc3e5b8d4bafa7

This line:
https://github.com/SublimeLinter/SublimeLinter/blob/e7a01475feeb1cdd813dfb9f76fffe91bad28061/lint/queue.py#L19
Triggers an attribute error, instead of an assertion error:
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 538, in on_activated_async
    callback.on_activated_async(v)
  File "sublime_linter in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 111, in on_activated_async
  File "sublime_linter in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 281, in hit
  File "lint.queue in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 19, in hit
AttributeError: 'Daemon' object has no attribute '_callback'
```
This is happening with the stable version of `SublimeLinter-pylint` and `SublimeLinter-eslint`. Should I also add them to Package Control's `install_prereleases` setting?

**Comment by mandx** [comment]
Not at all a permanent solution, just providing more info: If I add this conditional just before the `assert` statement, everything works again:
```python
if not hasattr(self, '_callback'):
    return
```

**Comment by braver** [comment]
> Should I also add them to Package Control's install_prereleases setting?

No their stable releases should be compatible. Although especially eslint is a bit wonky. We'll just have to look into it.

**Comment by braver** [comment]
Any idea on how to reproduce this error? 

@kaste have an opinion on this?

**Comment by mandx** [comment]
Well, yesterday everything was working, and today Package Control downloaded the update, and then it stopped working. What environment info you want me to share?

**Comment by braver** [comment]
Can you run SL with debug mode on and share the output up to this error?

**Comment by mandx** [comment]
Funny, I can't reproduce it now, and I think is because I just restarted ST3 (to ensure a clean debug output and not one with days worth of messages). Could it be that Package Control upgraded STLinter, but the "daemon" or some other code old code was still running?

In any case, if the reporter (me) can't reproduce the problem, we could close this for now, and reopen if necessary.

Thanks!

**Comment by braver** [comment]
Could definitely be that something tripped up in the update and the restart cleared it. Please report back if you run into it again!

**Comment by mandx** [comment]
Got a similar error (in some other module), and it went away after a restart. I guess you might have to start recommending restarting ST3 in every Package Control's update message. I wonder if this would be a feature/bug on Package Control's side (completely unload a plugin, then load that plugin again from scratch), since that's the one replacing files with a running instance of ST3.

**Comment by braver** [comment]
I'll make the note about restarting bigger. 

All linter plugins depend on the core package, and there are other complexities that make fully hot-reloading it a challenge.

**Comment by FichteFoll** [comment]
Would something like this help? https://github.com/SublimeText/PackageDev/blob/master/main.py

**Comment by drcongo** [comment]
I've just upgraded to SL4 and I'm getting this error, every after several restarts of SublimeText and a restart of my Mac.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "commands in /Users/andy/Dropbox/Libraries/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 36, in run
  File "sublime_linter in /Users/andy/Dropbox/Libraries/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 280, in hit
  File "lint.queue in /Users/andy/Dropbox/Libraries/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 19, in hit
AttributeError: 'Daemon' object has no attribute '_callback'```

The upgrade also didn't create a new `SublimeLinter old.sublime-settings` or back up my settings to `SublimeLinter old.sublime-settings`, so my manual migration of the settings following the instructions may be a cause of this. My settings file now looks like this...

```{

    "debug": false,
    "delay": 0,
    "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
    "lint_mode": "background",
    "linters": {
        "annotations": {
            "@disable": false,
            "args": [],
            "errors": [
                "FIXME"
            ],
            "excludes": [],
            "warnings": [
                "NOTE",
                "README",
                "TODO",
                "@todo",
                "XXX",
                "WIP"
            ]
        },
        "ansiblelint": {
            "@disable": false,
            "R": "",
            "args": [],
            "exclude": "",
            "excludes": [],
            "r": "",
            "t": "",
            "x": ""
        },
        "apiblueprint": {
            "@disable": false,
            "args": [],
            "excludes": []
        },
        "flake8": {
            "@disable": false,
            "args": [],
            "builtins": "",
            "excludes": [],
            "executable": "",
            "ignore": "E402",
            "jobs": "1",
            "max-complexity": 10,
            "max-line-length": 100,
            "select": "",
            "show-code": false
        },
        "htmltidy": {
            "@disable": false,
            "args": [],
            "excludes": []
        },
        "jshint": {
            "@disable": false,
            "args": [],
            "excludes": []
        },
        "phplint": {
            "@disable": false,
            "args": [],
            "excludes": []
        },
        "proselint": {
            "@disable": false,
            "args": [],
            "excludes": []
        },

        "no_column_highlights_line": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "coffeescript (gulpfile)": "coffeescript",
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (eslint)": "javascript",
            "javascript (gruntfile)": "javascript",
            "javascript (gulpfile)": "javascript",
            "javascript (postcss)": "javascript",
            "javascript (stylelint)": "javascript",
            "javascript (webpack)": "javascript",
            "json (babel)": "json",
            "json (bower)": "json",
            "json (composer)": "json",
            "json (eslint)": "json",
            "json (npm)": "json",
            "json (postcss)": "json",
            "json (settings)": "json",
            "json (stylelint)": "json",
            "json (sublime)": "json",
            "json (tern js)": "json",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python",
            "xml (config)": "xml",
            "xml (svg)": "xml",
            "yaml (circleci)": "yaml",
            "yaml (docker)": "yaml",
            "yaml (eslint)": "yaml",
            "yaml (lock)": "yaml",
            "yaml (procfile)": "yaml",
            "yaml (stylelint)": "yaml",
            "yaml (yarn)": "yaml"
        },
        "use_current_shell_path": false,
    }
}
```

**Comment by drcongo** [comment]
Follow up, it's disappeared after copying over the `SublimeLinter.sublime-settings` from this repo
