### ISSUE TITLE
[beta]console log error

### ISSUE THREAD

**Issue by Jax0rz** [SublimeLinter/SublimeLinter#815]
I got this error in console when sublime text startup;
my ST version is `3156`,my SublimeLinter version is `4.0.0-rc.9.8`
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "sublime_linter in /Users/johnnyyang/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 65, in plugin_loaded
  File "sublime_linter in /Users/johnnyyang/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 282, in hit
KeyError: 13
```

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 538, in on_activated_async
    callback.on_activated_async(v)
  File "sublime_linter in /Users/johnnyyang/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 112, in on_activated_async
  File "sublime_linter in /Users/johnnyyang/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 282, in hit
KeyError: 4
```

**Comment by FichteFoll** [comment]
Please wrap tracebacks in fenced code blocks (```` ``` ````): https://guides.github.com/features/mastering-markdown/#syntax-highlighting

**Comment by Jax0rz** [comment]
@FichteFoll I've changed it.

**Comment by braver** [comment]
I believe #807 fixes this, not 100% but at least I'm not getting this anymore. @kaste?

**Comment by kaste** [comment]
Yes, fixed
