### ISSUE TITLE
[beta] How to use gutter themes in 4.0rc 9.9.2

### ISSUE THREAD

**Issue by douglas** [SublimeLinter/SublimeLinter#877]
How to use gutter themes in beta, @braver?

With these settings:

```json
// SublimeLinter Settings - User
{
  "lint_mode": "load_save",
  "gutter_theme": "Default",
  "styles": [
      {
          "mark_style": "solid_underline",
          "priority": 1,
          "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
          "icon": "cog",
          "types": [
              "warning"
          ]
      },
      {
          "mark_style": "solid_underline",
          "priority": 1,
          "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
          "icon": "cog",
          "types": [
              "error"
          ]
      }
  ]
}
```
I have this error:

<img width="1141" alt="screen shot 2018-01-23 at 19 47 33" src="https://user-images.githubusercontent.com/411301/35308591-5a863d90-0076-11e8-8529-6331bc98b797.png">

In fact, I want to use the `Hands` theme, how can I do this with beta?

**Comment by braver** [comment]
Those settings should work. Have you restarted Sublime Text after installing the beta? It seems unable to load the default settings, which should never happen.

Use this for the Hands theme:

```json
"gutter_theme": "Hands",
  "styles": [
      {
          "mark_style": "solid_underline",
          "priority": 1,
          "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
          "icon": "error",
          "types": [
              "warning"
          ]
      },
      {
          "mark_style": "solid_underline",
          "priority": 1,
          "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
          "icon": "error",
          "types": [
              "error"
          ]
      }
  ]
```

**Comment by willrowe** [comment]
When I set the gutter theme to this:
```json
    "gutter_theme": "Default",
    "styles": [
        {
            "mark_style": "outline",
            "priority": 1,
            "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
            "icon": "triangle",
            "types": [
                "warning"
            ]
        },
        {
            "mark_style": "outline",
            "priority": 1,
            "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
            "icon": "x",
            "types": [
                "error"
            ]
        }
    ]
```

I get the following error:
```
Traceback (most recent call last):
  File "lint.events in /**REDACTED**/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 28, in broadcast
  File "highlight_view in /**REDACTED**/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 73, in on_lint_result
  File "highlight_view in /**REDACTED**/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 146, in prepare_gutter_data
  File "highlight_view in /**REDACTED**/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 211, in get_icon
  File "lint.style in /**REDACTED**/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 99, in wrapper
KeyError: 'error'
```
I get the warning/error count in the status bar, but no gutter icon is drawn.

I did some testing and found out the following:
1. When installed from Package Control, SublimeLinter is placed into `Sublime Text 3/Installed Packages/SublimeLinter.sublime-package` (as can be seen in the traceback).
2. If I clone this repo into `Sublime Text 3/Packages`, it works as expected.
3. I may be wrong, but it seems that loading the icons depends on the plugin being installed in `Sublime Text 3/Packages` as reported by `sublime.find_resources`.
4. v3 of SublimeLinter has the `.no-sublime-package` file, whereas this version does not.
5. Leaving the default settings for icons works correctly.

**Comment by braver** [comment]
Hmmm 🤔

**Comment by braver** [comment]
@willrowe Does something like the Hands theme work for you, ie. is it just the Default that doesn't work?

**Comment by willrowe** [comment]
When I set it to this:

```json
{
    "gutter_theme": "Hands",
    "styles": [
        {
            "mark_style": "outline",
            "priority": 1,
            "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
            "icon": "warning",
            "types": [
                "warning"
            ]
        },
        {
            "mark_style": "outline",
            "priority": 1,
            "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
            "icon": "error",
            "types": [
                "error"
            ]
        }
    ]
}
```

I get the same error:
```
Traceback (most recent call last):
  File "lint.events in /**REDACTED**/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 28, in broadcast
  File "highlight_view in /**REDACTED**/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 73, in on_lint_result
  File "highlight_view in /**REDACTED**/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 146, in prepare_gutter_data
  File "highlight_view in /**REDACTED**/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 211, in get_icon
  File "lint.style in /**REDACTED**/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 99, in wrapper
KeyError: 'error'
```

**Comment by braver** [comment]
Thanks, I got it. We're constructing paths instead of using `find_resource`, which doesn't work if installed in packaged format. Working on it!

**Comment by willrowe** [comment]
I can confirm that it is now working as expected, thanks!

**Comment by braver** [comment]
w00t 🎉
