### ISSUE TITLE
UnboundLocalError: local variable 'executable' referenced before assignment

### ISSUE THREAD

**Issue by nachiketmistry** [SublimeLinter/SublimeLinter#88]
I see these traceback in my console 

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 303, in on_activated
    callback.on_activated(v)
  File "/Users/nmistry/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 266, in on_activated
    self.check_syntax(view)
  File "/Users/nmistry/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 207, in check_syntax
    Linter.assign(view, reset=True)
  File "/Users/nmistry/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 650, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "X/functools.py", line 233, in wrapper
  File "/Users/nmistry/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1414, in can_lint
    status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)
UnboundLocalError: local variable 'executable' referenced before assignment
```

 A quick look at linter.py, executable is set on line 1367 and is not in the scope when read at 1413. 

Let me know if you need any more information.

**Comment by chiefy** [comment]
:+1: thanks, this helped me out, using .zshrc in OSX, never realized I was doing it wrong :stuck_out_tongue_winking_eye:

**Comment by Xunnamius** [comment]
For those of us (un)fortunate enough to be on Windows and encounter this issue, start by checking that you don't have the executable in your local path AND the system path. For some reason, this makes SublimeLinter very angry. In my case, the issue was php.exe being in the local path AND the system path. Removing it from the local path made SublimeLinter happy.

:+1: Cheers!
