### ISSUE TITLE
AssertionError: must have a panel now!

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#905]
```
Traceback (most recent call last):
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/panel_view.py", line 70, in <lambda>
    sublime.set_timeout_async(lambda: fill_panel(window, update=True))
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/panel_view.py", line 275, in fill_panel
    assert panel, "must have a panel now!"
AssertionError: must have a panel now!
```

1. Open a file with highlights
2. Open SublimeLinter settings (e.g. via command palette)
3. Change the style, e.g. specifically for "pylint"
4. Quickly close the settings window
5. Inspect the console

**Comment by kaste** [comment]
Thanks for that. I saw this once but could not reproduce. But now with this detailed steps, this actually what I did.
