### ISSUE TITLE
another error when quickly closing windows

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#933]
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 96, in on_activated_async
    self.check_syntax(view)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 285, in check_syntax
    self.clear(view)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 291, in clear
    Linter.clear_view(view)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1122, in clear_view
    highlight_view.clear_view(view)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/highlight_view.py", line 33, in clear_view
    for key in get_regions_keys(view):
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/highlight_view.py", line 29, in get_regions_keys
    return set(view.settings().get(REGION_KEYS.format(view.id()), []))
TypeError: 'NoneType' object is not iterable
```

**Comment by kaste** [comment]
That's on master, right? Before #887

**Comment by braver** [comment]
Yes, on master.

**Comment by kaste** [comment]
Ok, I also had this once, then never again, so I thought Supernova

**Comment by braver** [comment]
`view.settings().get(REGION_KEYS.format(view.id()))` is None if I open settings, give it a second, and then close it. Seems like it's in the middle of something when I kill it. 😕
