### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#937]
```
Traceback (most recent call last):
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/backend.py", line 177, in await_futures
    yield future.result()
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/backend.py", line 72, in execute_lint_task
    errors = linter.lint(code, hit_time) or []
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 945, in lint
    error = self.process_match(m, vv)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1018, in process_match
    start, end = vv.full_line(m.line)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 69, in full_line
    start = self._newlines[line]
IndexError: list index out of range
```

This on master. Happens a lot... I used #887 all afternoon and never got this. Weird.

**Comment by kaste** [comment]
mypy?

**Comment by braver** [comment]
no, just pylint and flake8 this time

**Comment by braver** [comment]
Oh, maybe it's the json linter? Seems to be related to opening the settings.

**Comment by kaste** [comment]
What json linter is that.

**Comment by braver** [comment]
SublimeLinter-json, uses ST's parser.

**Comment by kaste** [comment]
I use the same, never seen this. Also: I could not reproduce the other bugs you filed. I just did a defensive refactoring in #936 E.g. https://github.com/SublimeLinter/SublimeLinter/pull/936/commits/70b7035c81ba9ba3ac7337105fa9b3477dea5c66 I could only reproduce this doing interactive rebases of SublimeLinter itself which is not really fair.

**Comment by kaste** [comment]
Please take a look at the output. This should only happen, when the reported line:col numbers are greater than the actual view.

**Comment by braver** [comment]
🤷‍♂️
