### ISSUE TITLE
TypeError: can't specify None for path argument

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#938]
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 102, in on_activated_async
    self.on_new_async(view)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublime_linter.py", line 109, in on_new_async
    if not util.is_lintable(view):
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 87, in is_lintable
    not os.path.exists(view.file_name())
  File "./python3.3/genericpath.py", line 18, in exists
TypeError: can't specify None for path argument
```

Is my ST install borked? I don't even know what triggered it.

**Comment by kaste** [comment]
I have here 

https://github.com/SublimeLinter/SublimeLinter/blob/93eb98b50135377e44e38732408f1f0faa50cee9/lint/util.py#L84-L87

**Comment by braver** [comment]
🤷‍♂️

**Comment by braver** [comment]
I seem to have had a dependency version mismatch for flake8, that may not have helped... who knows.
