### ISSUE TITLE
If settings are invalid at start, they're still loaded, leading to breakage

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#958]
When you update settings they have to pass validation before being applied. If you have invalid settings and quit ST, the invalid settings are applied at startup without passing validation. This may lead to breakage, e.g. with missing mark_style:

```
Traceback (most recent call last):
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/events.py", line 28, in broadcast
    fn(**payload)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/highlight_view.py", line 78, in on_lint_result
    view, linter_name, errors_for_the_highlights)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/highlight_view.py", line 190, in prepare_highlights_data
    flags = MARK_STYLES[mark_style]
KeyError: None
```

**Comment by kaste** [comment]
A typical LOL bug. Sorry.

**Comment by braver** [comment]
#959 is all we're going to do about it
