### ISSUE TITLE
Annotations stoppped working

### ISSUE THREAD

**Issue by vkrajacic89** [SublimeLinter/SublimeLinter#963]
For some reasons my annotations stopped working. This is output of debug log.

```
DPI scale: 1
startup, version: 3143 windows x64 channel: stable
executable: /C/Users/Vjekoslav/Apps/Sublime/sublime_text.exe
working dir: /C/Users/Vjekoslav/Apps/Sublime
packages path: /C/Users/Vjekoslav/Apps/Sublime/Data/Packages
state path: /C/Users/Vjekoslav/Apps/Sublime/Data/Local
zip path: /C/Users/Vjekoslav/Apps/Sublime/Packages
zip path: /C/Users/Vjekoslav/Apps/Sublime/Data/Installed Packages
ignored_packages: ["Vintage"]
Unable to decode Packages/Theme - Default/arrow_right.png
Unable to decode Packages/Theme - Default/arrow_right_over.png
Unable to decode Packages/Theme - Default/arrow_down.png
Unable to decode Packages/Theme - Default/arrow_down_over.png
pre session restore time: 0.0841571
startup time: 0.119157
first paint time: 0.121157
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Case Conversion.case_conversion
reloading plugin Case Conversion.case_parse
reloading plugin ColorSchemeEditor.ColorSchemeEditor-ST2
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin SublimeLinter-annotations.linter
Traceback (most recent call last):
  File "C:\Users\Vjekoslav\Apps\Sublime\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Users\Vjekoslav\Apps\Sublime\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in C:\Users\Vjekoslav\Apps\Sublime\Data\Installed Packages\SublimeLinter-annotations.sublime-package", line 17, in <module>
AttributeError: 'module' object has no attribute 'lint'
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin User._dual_panel
reloading plugin User._list_user_macros
reloading plugin User._run_entelechy
reloading plugin User._word_expand_selection
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2018-02-06 08:23:01, next run at 2018-02-06 09:23:01 or after
```

**Comment by braver** [comment]
It seems to load `SublimeLinter-annotations.linter` before it's done loading SL, which is really weird. What version of SL are you using?

**Comment by vkrajacic89** [comment]
I removed and installed both packages this morning in order to try and fix this problem. So I quess I'm using latest version.

**Comment by braver** [comment]
You could try using [SublimeLinter 4](https://github.com/SublimeLinter/SublimeLinter#sublimelinter-4-is-imminent) to see what that does?

**Comment by vkrajacic89** [comment]
Is this not the latest version which I already have?

**Comment by braver** [comment]
Not if you didn't opt-in to the prerelease. SL4 is in an advanced state of "beta".

**Comment by vkrajacic89** [comment]
Problem still persists. I've reinstalled [annotations](https://github.com/SublimeLinter/SublimeLinter-annotations) too, and changed new user settings for Linter.

`// SublimeLinter Settings - User
{
    "debug": true,
    "linters": {
        "annotations": {
            "@disable": false,
            "args": [],
            "errors": [
                "FIXME"
            ],
            "excludes": [],
            "warnings": [
                "NOTE",
                "README",
                "TODO",
                "IMPORTANT",
                "STUDY"
            ]
        }
    }
}
`

**Comment by braver** [comment]
Please share your full SublimeLinter settings, enable debug mode, and share the log after a restart of ST.

**Comment by vkrajacic89** [comment]
User settings:
```
// SublimeLinter Settings - User
{
    "debug": true,
    "linters": {
        "annotations": {
            "@disable": false,
            "args": [],
            "errors": [
                "FIXME"
            ],
            "excludes": [],
            "warnings": [
                "NOTE",
                "README",
                "TODO",
                "IMPORTANT",
                "STUDY"
            ]
        }
    }
}
```
Log:
```
DPI scale: 1
startup, version: 3143 windows x64 channel: stable
executable: /C/Users/Vjekoslav/Apps/Sublime/sublime_text.exe
working dir: /C/Users/Vjekoslav/Apps/Sublime
packages path: /C/Users/Vjekoslav/Apps/Sublime/Data/Packages
state path: /C/Users/Vjekoslav/Apps/Sublime/Data/Local
zip path: /C/Users/Vjekoslav/Apps/Sublime/Packages
zip path: /C/Users/Vjekoslav/Apps/Sublime/Data/Installed Packages
ignored_packages: ["Vintage"]
Unable to decode Packages/Theme - Default/arrow_right.png
Unable to decode Packages/Theme - Default/arrow_right_over.png
Unable to decode Packages/Theme - Default/arrow_down.png
Unable to decode Packages/Theme - Default/arrow_down_over.png
pre session restore time: 0.0549435
startup time: 0.0889435
first paint time: 0.0909435
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin Case Conversion.case_conversion
reloading plugin Case Conversion.case_parse
reloading plugin ColorSchemeEditor.ColorSchemeEditor-ST2
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin SublimeLinter-annotations.linter
Traceback (most recent call last):
  File "C:\Users\Vjekoslav\Apps\Sublime\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Users\Vjekoslav\Apps\Sublime\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in C:\Users\Vjekoslav\Apps\Sublime\Data\Installed Packages\SublimeLinter-annotations.sublime-package", line 17, in <module>
AttributeError: 'module' object has no attribute 'lint'
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin User._dual_panel
reloading plugin User._list_user_macros
reloading plugin User._run_entelechy
reloading plugin User._word_expand_selection
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: version: 4.0.0-rc.9.9.7 
SublimeLinter: detected syntax: c# 
SublimeLinter: detected syntax: c# 
Package Control: Skipping automatic upgrade, last run at 2018-02-06 10:18:29, next run at 2018-02-06 11:18:29 or after
```

**Comment by braver** [comment]
That's just crazy, why isn't it loading packages in alphabetical order like it should? @FichteFoll know anything about that?

Could you try disabling and then re-enabling annotations via package control?

-----
Minor thing: `"@disable": false,` is without the `@` in SL4 and if `false` also not required.

**Comment by vkrajacic89** [comment]
Same log on startup after enabling/disabling annotations.

**Comment by FichteFoll** [comment]
Load order shouldn't matter because plugins import the sub-package directly and that is supported by ST. In fact, my SL always imports after almost all plugins since it's unpackaged and those are loaded after package packages.

The actual problem is an errorneous check for `SublimeLinter.lint.VERSION` where you import `SublimeLinter` but not `SublimeLinter.lint`, as I mentioned in https://github.com/fredcallaway/SublimeLinter-contrib-mypy/pull/23#discussion_r165977082. It's a bug in the annotations plugin.

**Comment by braver** [comment]
Oh, damn, you're right. Sorry, should've paid more attention there.

**Comment by FichteFoll** [comment]
https://github.com/SublimeLinter/SublimeLinter-annotations/pull/17

**Comment by vkrajacic89** [comment]
Thanks for the solution. I see [bug fix](https://github.com/SublimeLinter/SublimeLinter-annotations/commit/a3f0473fbff5a80c685b36d5f08bce390db12109) was made an hour ago. How long does it take to become available through ST package control system?

**Comment by braver** [comment]
Usually about an hour, unless I messed up our package control entries again.
