### ISSUE TITLE
TypeError: can only assign an iterable

### ISSUE THREAD

**Issue by mandx** [SublimeLinter/SublimeLinter#987]
Linting triggers automatically, and I get this output in the console:
```
SublimeLinter: ERROR:

 Lint task failed.
Traceback (most recent call last):
  File "lint.backend in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 201, in await_futures
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "lint.backend in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 96, in execute_lint_task
  File "lint.linter in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 908, in lint
  File "lint.linter in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 631, in get_cmd
  File "lint.linter in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 667, in build_cmd
TypeError: can only assign an iterable
```

**Comment by braver** [comment]
Can you share the output that you get when you enable debug mode and restart ST?

**Comment by mandx** [comment]
Interestingly, I have been able to reproduce this only with the ESLint linter (the Pylint based one works fine).

Simply open a new buffer/view (Ctrl+N, you get a blank file with no name and "Plain text" as the syntax type). Write some gibberish, then, using the command palette, change the syntax to Javascript, to trigger the linting, then the console is cleared and I get the above message only. And this in within a ST project that has ESLint configured and working properly for existing files.

I'm posting it here because I don't see any ESLint-related path in the traceback.

Here's the output of the console after a restart in debug mode (before triggering the error) https://gist.github.com/mandx/1f6c653d8d08434cf4024662edfa6910

**Comment by kaste** [comment]
PR is #988 

Note that what you see is the new error panel. You can open the console again to see more logs.

**Comment by mandx** [comment]
@kaste Oh, ok, good to know. Do you still want me to paste those logs after triggering the error? Or the PR fully addresses the issue?

**Comment by kaste** [comment]
You should see another warning before everything crashes 😄 So maybe check that.

**Comment by mandx** [comment]
Got this:
```
SublimeLinter: SublimeLinter.sublime-package:549: detected syntax: javascript
SublimeLinter: #3 SublimeLinter.sublime-package:896: 'eslint' is linting '<untitled 42>'
SublimeLinter: #3 SublimeLinter.sublime-package:104: PATH:
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin
    /usr/games
    /usr/local/games
    /usr/lib/go-1.9/bin
    /home/mandx/.cargo/bin
SublimeLinter: WARNING: eslint cannot locate 'eslint' 
SublimeLinter: __init__.py:1273: ERROR: Lint task failed.
Traceback (most recent call last):
  File "lint.backend in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 201, in await_futures
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "lint.backend in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 96, in execute_lint_task
  File "lint.linter in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 908, in lint
  File "lint.linter in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 631, in get_cmd
  File "lint.linter in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 667, in build_cmd
TypeError: can only assign an iterable
```
Which makes sense, since my project settings have STLinter configured using the `${folder}` variablem; since the view is not saved, there's no folder to properly compute the `PATH`.

So does this means that linting unsaved views is only possible when STLinter's `PATH` is configured globally?

**Comment by kaste** [comment]
No, shouldn't be so. ${folder} should point to the first open folder.

**Comment by mandx** [comment]
Well, then I'll try linting unsaved views as soon as the PR is merged!

**Comment by kaste** [comment]
E.g. I get 

![image](https://user-images.githubusercontent.com/8558/36179122-73cb43ee-111b-11e8-814f-86f6a1a35aea.png)

if I set 

![image](https://user-images.githubusercontent.com/8558/36179138-80ce91ea-111b-11e8-9484-acb3443e1690.png)

**Comment by kaste** [comment]
No, the PR will not solve that warning. I only failed at catching that warning so it crashed completely. How did you set up SL-eslint? Does it not just take the local eslint from node_modules?

**Comment by mandx** [comment]
My global STLinter settings only have the `styles` key set. Now this is the contents of my project file:
```json
{
  "SublimeLinter": {
    "paths": {
      "linux": [
        "${folder}/node_modules/.bin"
      ],
      "osx": [
        "${folder}/node_modules/.bin"
      ]
    }
  },
  "folders": [
    {
      "path": "."
    }
  ]
}
```
Nothing else needs configuration, I just make sure the ESLint executable is inside `./node_modules/.bin`.

**Comment by kaste** [comment]
Surprisingly, SL-eslint falls back to using the global eslint for unsaved views. So, PR #989 for that. (Did not find an issue on the eslint repo, surprisingly as well.)

Note @mandx your project settings don't do anything here. `paths` is a setting which can only be applied globally (in the User Settings). Then again, `${folder}` etc variable substitutions only work for linter settings. 😕
