### ISSUE TITLE
AttributeError: 'module' object has no attribute 'debounce'

### ISSUE THREAD

**Issue by btrd** [SublimeLinter/SublimeLinter#990]
Hi ! First of all thanks for your work, the lastest version of SublimeLinter is relay fantastic, exactly what I needed.

Sadly, it doesn't work anymore and I don't know why 😞 I get this error in the console : 

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 480, in on_post_save_async
    callback.on_post_save_async(v)
  File "sublime_linter in /Users/jean/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 135, in on_post_save_async
  File "sublime_linter in /Users/jean/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 419, in file_was_saved
  File "sublime_linter in /Users/jean/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 226, in hit
AttributeError: 'module' object has no attribute 'debounce'
```

I'm using `SublimeLinter-rubocop`.

**Comment by kaste** [comment]
Can you restart Sublime say a couple of hundred times 😸 I have the `debounce` call on line 186 not on line 226

**Comment by btrd** [comment]
Ok, just one restart was enough. Thanks !
